namespace AFMediaBar.Classes.Services.Localization.Strings;

/// <summary>
/// 繁体中文（台湾用语）文案。
///
/// 一种语言一份文件：翻译与校对只碰这一个文件，新增语言就是再增一个同构文件，并在 <c>Translations</c> 的登记列表里加一行。
/// 键必须与另外两份语言文件完全一致：缺一条时该语言会回退到简体中文，所以漏翻译只能靠逐行对照三份文件发现；
/// 三份文件的键顺序也相同，因此同一行号在三份文件里指的是同一条文案。
/// Traditional Chinese (Taiwan usage) text.
///
/// One file per language: translating and proofreading touch only this file, and adding a language means adding one more
/// file of the same shape plus a line in the registration list inside <c>Translations</c>. The keys have to match the other
/// two files exactly: a missing entry falls back to simplified Chinese, so a gap is found by comparing the three files, and
/// because all three files share one key order the same line number means the same string in every one of them.
/// </summary>
internal static class StringsZhHant
{
    /// <summary>登记本语言文案。/ Registers the text of this language.</summary>
    /// <param name="table">该语言的文案表。/ The text table of this language.</param>
    internal static void Register(LanguageTable table)
    {
        // ---- About ----
        table.Add("About.Header.Subtitle", "開發人員、贊助者與開源授權");
        table.Add("About.Language.Description", "介面文字的顯示語言；選「跟隨系統」時依 Windows 顯示語言決定，切換後立即生效");
        table.Add("About.Language.English", "English");
        table.Add("About.Language.FollowSystem", "跟隨系統");
        table.Add("About.Language.SimplifiedChinese", "简体中文");
        table.Add("About.Language.Title", "介面語言");
        table.Add("About.Language.TraditionalChinese", "繁體中文");
        table.Add("About.Language.Vietnamese", "越南語");
        table.Add("About.ResetScope", "所有設定");
        table.Add("About.Row.AutoCheck.Description", "啟動約 20 秒後讀取公開版本清單；成功後 24 小時內不再自動檢查，失敗 1 小時後重試。發現新版本時顯示一次系統通知，點擊通知開啟本頁");
        table.Add("About.Row.AutoCheck.Title", "自動檢查更新");
        table.Add("About.Row.ClearDefaults.Description", "刪除已儲存的預設設定，重設入口回到程式內建預設值");
        table.Add("About.Row.ClearDefaults.Title", "清除我的預設設定");
        table.Add("About.Row.Download.Download", "下載並安裝");
        table.Add("About.Row.DownloadPage.Description", "GitHub 直連無法連線時，可用加速站台開啟同一個下載頁");
        table.Add("About.Row.DownloadPage.Mirror", "加速鏡像");
        table.Add("About.Row.DownloadPage.Title", "開啟下載頁");
        table.Add("About.Row.Install.Description", "下載與驗證完成後，下次啟動程式時會先安裝再啟動新版本；也可以現在立即安裝");
        table.Add("About.Row.Install.Now", "立即重新啟動並安裝");
        table.Add("About.Row.Install.Title", "安裝更新");
        table.Add("About.Row.OpenFolder.Description", "開啟 settings.json 所在的資料夾，可直接備份或取代");
        table.Add("About.Row.OpenFolder.Title", "開啟設定資料夾");
        table.Add("About.Row.LogFolder.Description", "日誌是 logs\\app.log 一個檔案，只保留最近 1000 條；出現錯誤時請把這個檔案送出來");
        table.Add("About.Row.LogFolder.Title", "日誌檔案");
        table.Add("About.Row.TrimMemory.Button", "立即壓縮");
        table.Add("About.Row.TrimMemory.Description", "把工作集（佔用的實體記憶體）交還給系統：工作管理員裡的讀數會立刻下降，下次用到這部分時程式需要重新讀回，可能有短暫卡頓；認可大小不變");
        table.Add("About.Row.TrimMemory.Title", "壓縮記憶體佔用");
        table.Add("Common.Group.Developers", "開發人員");
        table.Add("Common.Group.Diagnostics", "診斷與日誌");
        table.Add("About.Row.Portable.Badge", "免安裝版");
        table.Add("About.Row.Portable.Description", "目前不是安裝版本，無法自動取代檔案；請從下載頁取得安裝程式或手動取代程式檔案");
        table.Add("About.Row.Portable.Title", "自動更新無法使用");
        table.Add("About.Row.Progress.Title", "下載進度");
        table.Add("About.Row.Project.Description", "Windows 工作列媒體體驗 · 版本 1.0.0");
        table.Add("About.Row.Project.Issues", "問題回報");
        table.Add("About.Row.Project.Star", "在 GitHub 按 Star");
        table.Add("About.Row.ResetAll.Button", "重設全部");
        table.Add("About.Row.ResetAll.Description", "顯示模式、互動、歌詞、外觀與媒體通知全部恢復預設值");
        table.Add("About.Row.ResetAll.Title", "重設全部設定");
        table.Add("About.Row.SaveDefaults.NotSaved", "未儲存：各頁的「恢復預設設定」回到程式內建預設值");
        table.Add("About.Row.SaveDefaults.Saved", "已儲存：各頁的「恢復預設設定」都會回到這份快照");
        table.Add("About.Row.SaveDefaults.Title", "將目前設定儲存為預設");
        table.Add("About.Row.Skip.Clear", "取消略過");
        table.Add("About.Row.Skip.Description", "略過只影響自動提示，手動檢查仍會顯示該版本");
        table.Add("About.Licenses.Open", "查看專案");
        table.Add("About.Support.Afdian", "愛發電");
        table.Add("About.Support.Alipay", "支付寶");
        table.Add("About.Support.Open", "開啟連結");
        table.Add("About.Support.Pending", "收款碼與贊助連結由作者後續補充；上方的路徑就是檔案應當放入的位置");
        table.Add("About.Support.SponsorNote", "大於 10 元的贊助可以進入贊助者名單，請在備註中留下 id");
        table.Add("About.Support.WeChat", "微信");
        table.Add("Credits.Contributions", "提交 {0} 次");
        table.Add("Credits.Reason.ContributorsEmpty", "貢獻者清單為空");
        table.Add("Credits.Reason.ContributorsShape", "貢獻者清單結構不正確");
        table.Add("Credits.Reason.Empty", "名單內容為空");
        table.Add("Credits.Reason.InvalidJson", "名單內容不是有效的 JSON");
        table.Add("Credits.Reason.SchemaTooNew", "贊助名單的結構版本（{0}）高於本程式支援的版本（{1}）");
        table.Add("Credits.Reason.SponsorsShape", "贊助名單結構不正確");
        table.Add("Credits.Sponsors.Count", "共 {0} 位贊助者");
        table.Add("Credits.Sponsors.None", "尚無贊助者。如果這份名單沒有出現，請點「重試」，或在倉庫的 docs/sponsors.json 裡補充");
        table.Add("Credits.SponsorSeparator", "、");
        table.Add("Credits.Status.Failed", "暫時無法取得名單：{0}");
        table.Add("Credits.Status.Partial", "部分名單暫時無法取得：{0}");
        table.Add("Credits.Status.PartialCached", "上次只取到一部分名單");
        table.Add("Credits.Status.Loading", "正在取得開發人員與贊助者名單…");
        table.Add("Credits.Retry", "重試");
        table.Add("About.Row.Startup.Description", "登入 Windows 後自動執行 AF Media Bar（只寫入目前使用者的啟動項目）");
        table.Add("About.Row.Startup.Title", "開機自動啟動");
        table.Add("About.Row.Version.Check", "檢查更新");
        table.Add("About.Row.Version.Description", "目前安裝的版本，以及公開清單中的最新版本");
        table.Add("About.Row.Version.Title", "版本");
        table.Add("About.Status.ClearDefaultsFailed", "無法刪除預設設定：{0}");
        table.Add("About.Status.SaveDefaultsFailed", "無法儲存預設設定：{0}");
        table.Add("About.Status.StartupFailed", "無法修改啟動項目：{0}");

        // ---- Appearance ----
        table.Add("Appearance.Accent.Custom", "自訂");
        table.Add("Appearance.Accent.FollowSystem", "跟隨系統");
        table.Add("Appearance.Accent.HexLabel", "色值");
        table.Add("Appearance.Accent.Hint", "主題色會用到所有強調色的位置：設定頁的選取狀態、開關、滑桿、兩類進度列、媒體列與浮層的醒目提示，以及完整層的強調段。選「自訂」只影響本程式，Windows 的個人化設定不會被修改；高對比度下仍然使用系統醒目色。");
        table.Add("Appearance.Accent.PaletteLabel", "選擇主題色");
        table.Add("Appearance.Backdrop.Acrylic", "壓克力（Acrylic）");
        table.Add("Appearance.Backdrop.Mica", "雲母（Mica）");
        table.Add("Appearance.Backdrop.MicaAlt", "雲母 Alt（Mica Alt）");
        table.Add("Appearance.Backdrop.Solid", "純色");
        table.Add("Appearance.BackdropTint.Hint", "只在材質由本程式繪製時生效：Windows 10 上的視窗，以及永不取得焦點的曲目通知（系統材質要求視窗位於前景，通知從不啟用，因此它的模糊由本程式繪製）。Windows 11 的雲母與壓克力由系統繪製，不受此值影響。值越低越通透，過高則接近純色。");
        table.Add("Appearance.CjkFont.FollowSystem", "跟隨系統");
        table.Add("Appearance.LatinFont.FollowSystem", "跟隨系統");
        table.Add("Appearance.Header.Subtitle", "字型、佈景主題、視窗背景與媒體列文字");
        table.Add("Appearance.Motion.Detail.Full", "保留展開、回饋與頻譜轉場");
        table.Add("Appearance.Motion.Detail.Instant", "跟隨系統設定，避免轉場延遲");
        table.Add("Appearance.Motion.Detail.Reduced", "已關閉模糊、跑馬燈與連續頻譜");
        table.Add("Appearance.Motion.Mode.Full", "完整動效");
        table.Add("Appearance.Motion.Mode.Instant", "即時更新");
        table.Add("Appearance.Motion.Mode.Reduced", "輕量動效");
        table.Add("Appearance.Preview.DarkWallpaper", "深色桌布");
        table.Add("Appearance.Preview.Hint", "自動模式的結果取決於工作列那一區的實際顏色，因此兩塊預覽僅為示意；強制模式在兩塊上使用同一種文字顏色。");
        table.Add("Appearance.Preview.LightWallpaper", "淺色桌布");
        table.Add("Appearance.Row.Accent.Description", "預設跟隨系統；自訂只改本程式，不改 Windows 設定");
        table.Add("Appearance.Row.Accent.Title", "主題色");
        table.Add("Appearance.Row.Backdrop.Description", "統一設定視窗、托盤彈出視窗與右鍵功能表的背襯");
        table.Add("Appearance.Row.Backdrop.Title", "視窗背景材質");
        table.Add("Appearance.Row.BackdropTint.Description", "本程式自行繪製的材質底色濃度（30%–100%）");
        table.Add("Appearance.Row.BackdropTint.Title", "材質濃度");
        table.Add("Appearance.Row.CjkFont.Description", "漢字使用的字型");
        table.Add("Appearance.Row.CjkFont.Title", "中文字型");
        table.Add("Appearance.Row.FontWeight.Description", "設定視窗、媒體列與通知共用的文字粗細");
        table.Add("Appearance.Row.FontWeight.Title", "字型粗細");
        table.Add("Appearance.Row.LatinFont.Description", "字母與數字使用的字型");
        table.Add("Appearance.Row.LatinFont.Title", "西文字型");
        table.Add("Appearance.Row.MediaFontSize.Description", "依百分比縮放靜置層的標題、歌手與歌詞字級（80%–125%）");
        table.Add("Appearance.Row.MediaFontSize.Title", "媒體文字大小");
        table.Add("Appearance.Row.Motion.Title", "互動動效");
        table.Add("Appearance.Row.TextColor.Description", "自動依文字背後的實際顏色選擇深淺");
        table.Add("Appearance.Row.TextColor.Title", "文字顏色");
        table.Add("Appearance.Row.Theme.Description", "自動跟隨 Windows 的淺色 / 深色設定");
        table.Add("Appearance.Row.Theme.Title", "應用程式佈景主題");
        table.Add("Appearance.Specimen.Label", "字樣預覽");
        table.Add("Appearance.TextColor.Automatic", "自動（依背景）");
        table.Add("Appearance.TextColor.DarkText", "一律深色文字");
        table.Add("Appearance.TextColor.LightText", "一律淺色文字");
        table.Add("Appearance.Theme.Automatic", "自動（跟隨系統）");
        table.Add("Appearance.Theme.Dark", "深色");
        table.Add("Appearance.Theme.Light", "淺色");

        // ---- Audio ----
        table.Add("Audio.Application.SystemSounds", "系統音效");
        table.Add("Audio.Error.CreateDeviceEnumerator", "無法建立 Windows 音訊裝置列舉器。");
        table.Add("Audio.Error.CreatePolicyConfig", "無法建立 Windows 音訊原則服務。");
        table.Add("Audio.OutputDevice.Unavailable", "輸出裝置：無法使用");
        table.Add("Audio.OutputDevice.Unchanged", "輸出裝置：未變更");
        table.Add("Audio.OutputDevice.Value", "輸出裝置：{0}");
        table.Add("Audio.Spatial.Enabled", "已啟用");
        table.Add("Audio.Spatial.NoDevice", "沒有輸出裝置");
        table.Add("Audio.Spatial.Off", "關閉");
        table.Add("Audio.Spatial.Unavailable", "狀態無法使用");
        table.Add("Audio.Spatial.Unsupported", "此裝置不支援");
        table.Add("Audio.Status.AdjustApplicationVolumeFailed", "調整 {0} 音量失敗：{1}");
        table.Add("Audio.Status.NoSessions", "目前沒有應用程式音訊工作階段");
        table.Add("Audio.Status.OpenSoundSettingsFailed", "無法開啟系統音效設定：{0}");
        table.Add("Audio.Status.ReadFailed", "讀取音訊狀態失敗：{0}");
        table.Add("Audio.Status.SwitchOutputDeviceFailed", "切換輸出裝置失敗：{0}");
        table.Add("Audio.Tooltip.AdjustVolumeFailed", "音量調整失敗");
        table.Add("Audio.Tooltip.SwitchOutputDeviceFailed", "切換輸出裝置失敗");
        table.Add("Audio.Tooltip.WheelDisabled", "托盤滾輪已停用");
        table.Add("Audio.Volume.CurrentValue", "{0} {1}%");
        table.Add("Audio.Volume.Unavailable", "目前媒體音量：無法使用");
        table.Add("Audio.Volume.Unchanged", "目前媒體音量：未變更");
        table.Add("Audio.Volume.Value", "{0}：{1}%");

        // ---- Common ----
        table.Add("Common.ActivateSourceApplication", "開啟播放中的程式");
        table.Add("Common.AdjustCurrentMediaVolume", "調整目前媒體音量");
        table.Add("Common.AlignCenter", "置中");
        table.Add("Common.AlignLeft", "靠左對齊");
        table.Add("Common.AlignRight", "靠右對齊");
        table.Add("Common.AudioControl", "音訊控制");
        table.Add("Common.Cancel", "取消");
        table.Add("Common.Clear", "清除");
        table.Add("Common.DynamicIsland", "動態島");
        table.Add("Common.Exit", "結束");
        table.Add("Common.FullLayer", "完整層");
        table.Add("Common.Group.Application", "應用程式");
        table.Add("Common.Group.ChooseDisplayMode", "選擇顯示模式");
        table.Add("Common.Group.Fonts", "字型");
        table.Add("Common.Group.InAppRestLayer", "程式內（靜置層）");
        table.Add("Common.Group.IslandAppearance", "動態島外觀");
        table.Add("Common.Group.Licenses", "開源授權");
        table.Add("Common.Group.LyricsAlignment", "對齊");
        table.Add("Common.Group.LyricsDisplay", "顯示");
        table.Add("Common.Group.LyricsSources", "取詞來源");
        table.Add("Common.Group.MediaBarText", "媒體列文字");
        table.Add("Common.Group.MediaBarWidth", "媒體列寬度");
        table.Add("Common.Group.ProjectInfo", "專案資訊");
        table.Add("Common.Group.QuickLaunch", "快速啟動");
        table.Add("Common.Group.RestLayerComponents", "靜置層元件");
        table.Add("Common.Group.ScreenAndPlacement", "螢幕與位置");
        table.Add("Common.Group.SettingsFile", "設定檔");
        table.Add("Common.Group.SharedModifier", "共用的按鍵");
        table.Add("Common.Group.Sponsors", "贊助者名單");
        table.Add("Common.Group.Support", "贊助我");
        table.Add("Common.Group.ThemeAndBackdrop", "佈景主題與背景");
        table.Add("Common.Group.TrackChangeNotification", "曲目切換通知");
        table.Add("Common.HoverLayer", "懸停層");
        table.Add("Common.MediaSource", "媒體來源");
        table.Add("Common.Modifier.LeftMouseButton", "滑鼠左鍵");
        table.Add("Common.Modifier.RightMouseButton", "滑鼠右鍵");
        table.Add("Common.Modifier.Shift", "Shift 鍵");
        table.Add("Common.Monitor.PrimarySuffix", "（主顯示器）");
        table.Add("Common.NextTrack", "下一首");
        table.Add("Common.NotBound", "未繫結");
        table.Add("Common.NotImplemented", "尚未實作");
        table.Add("Common.OpenFolder", "開啟資料夾");
        table.Add("Common.OpenFullPanel", "開啟完整層");
        table.Add("Common.OutputDevice", "輸出裝置");
        table.Add("Common.Page.About", "關於");
        table.Add("Common.Page.Application", "應用程式");
        table.Add("Common.Page.Appearance", "外觀");
        table.Add("Common.Page.DisplayModes", "顯示模式");
        table.Add("Common.Page.Interaction", "互動");
        table.Add("Common.Page.Lyrics", "歌詞");
        table.Add("Common.Page.MediaAndNotifications", "媒體與通知");
        table.Add("Common.PlayPause", "播放 / 暫停");
        table.Add("Common.PreviousNextTrack", "上一首 / 下一首");
        table.Add("Common.PreviousTrack", "上一首");
        table.Add("Common.ReconnectSmtc", "重新連線 SMTC");
        table.Add("Common.ReloadTaskbarHost", "重新載入工作列媒體列");
        table.Add("Common.ResetDialog.Confirm", "還原");
        table.Add("Common.ResetDialog.Content", "將重設「{0}」中的全部選項，其他頁面與目前播放不受影響。");
        table.Add("Common.ResetDialog.Title", "恢復預設設定");
        table.Add("Common.ResetPageDefaults", "恢復本頁預設設定");
        table.Add("Common.ResetPosition", "重設位置");
        table.Add("Common.RestLayer", "靜置層");
        table.Add("Common.Save", "儲存");
        table.Add("Common.Settings", "設定");
        table.Add("Common.SkipVersion", "略過此版本");
        table.Add("Common.SwitchMediaSource", "切換媒體來源");
        table.Add("Common.SwitchOutputDevice", "切換輸出裝置");
        table.Add("Common.SwitchPlayer", "切換播放器");
        table.Add("Common.TargetMonitor", "目標顯示器");
        table.Add("Common.TrayIcon", "托盤圖示");

        // ---- Diagram ----
        table.Add("Diagram.DynamicIslandSurface.Caption", "動態島模式尚未實作，因此下面三項目前唯讀；它的外觀與工作列互不影響。");
        table.Add("Diagram.InputGestures.Caption", "媒體列上僅這兩個區域可以點擊，並且可分別設定；展開面板中的按鈕不受影響。");
        table.Add("Diagram.InputGestures.Label.ArtworkClick", "點擊封面");
        table.Add("Diagram.InputGestures.Label.TextClick", "點擊標題或歌詞");
        table.Add("Diagram.LayerFull.Caption", "點擊媒體列展開的面板，四個分區可分別關閉，至少保留一個。");
        table.Add("Diagram.LayerFull.Label.MediaInfo", "媒體資訊");
        table.Add("Diagram.LayerFull.Label.Performance", "效能");
        table.Add("Diagram.LayerFull.Label.Playback", "播放控制");
        table.Add("Diagram.LayerHover.Caption", "滑鼠移入時出現播放、切換、輸出裝置、音量與進度控制，可在下一頁逐項開關。");
        table.Add("Diagram.LayerRest.Caption", "永遠顯示封面與標題；頻譜與效能元件重疊在右側，其開關位於「媒體與通知 → 靜置層元件」。");
        table.Add("Diagram.LyricsAlignment.Caption", "僅決定歌詞靠哪一側；標題與歌手的對齊是「顯示模式」頁中的另一項設定。");
        table.Add("Diagram.LyricsTwoLine.Caption", "第一行為目前句；第二行為下一句或翻譯，靜置層空間不足時不顯示。");
        table.Add("Diagram.LyricsTwoLine.Label.FirstLine", "第一行");
        table.Add("Diagram.LyricsTwoLine.Label.SecondLine", "第二行");
        table.Add("Diagram.NotificationPlacement.Caption", "共六個位置可選，高亮方塊為目前選擇；切換顯示器只改變出現位置。");
        table.Add("Diagram.NotificationPlacement.Label.AvoidTaskbar", "底部位置會自動避開工作列");
        table.Add("Diagram.NotificationPlacement.Label.InsideMonitor", "通知出現在選取的顯示器內");
        table.Add("Diagram.Spectrum.Caption", "圖示為 9 根頻譜柱，最右一根處於關閉狀態。更新頻率決定反應速度，靈敏度決定相同音量下的柱高。");
        table.Add("Diagram.TaskbarLength.Caption", "跟隨內容時寬度會自動變化；關閉跟隨後可指定固定寬度，取值範圍由目前工作列決定。");
        table.Add("Diagram.TaskbarLength.Label.MinimumWidth", "所需最小寬度");
        table.Add("Diagram.TaskbarLength.Label.TaskbarLimit", "工作列安全上限");
        table.Add("Diagram.TaskbarPlacement.Caption", "媒體列自動避開工作列圖示；邊緣位移用於調整它與圖示區之間的間距。");
        table.Add("Diagram.TaskbarPlacement.Label.EdgeOffset", "邊緣位移 −20 ~ +20 像素");
        table.Add("Diagram.TaskbarPlacement.Label.TaskbarIcons", "工作列圖示");
        table.Add("Diagram.TrayOverflow.Caption", "高亮方塊為本程式，預設位於隱藏圖示區；需在 Windows 工作列設定中將其拖出，托盤點擊與滾輪才會生效。");
        table.Add("Diagram.TrayOverflow.Label.OverflowArrow", "收進小箭頭");
        table.Add("Diagram.TrayOverflow.Label.TrayArea", "托盤區");
        table.Add("Diagram.WheelGestures.Caption", "向上與向下沒有固定含義，取決於繫結的動作。切換裝置時先顯示候選，停止捲動約 1.2 秒後套用。");
        table.Add("Diagram.WheelGestures.Label.MediaBar", "媒體列上");
        table.Add("Diagram.WheelGestures.Label.MediaBarResults", "四種結果都能繫結：上下首、切換裝置或播放器、調整音量");
        table.Add("Diagram.WheelGestures.Label.TrayResults", "只有切換裝置和調整音量兩種結果");

        // ---- DisplayModes ----
        table.Add("DisplayModes.Full.Expander.Description", "選擇面板包含的分區，至少保留一個");
        table.Add("DisplayModes.Full.Expander.Title", "完整層內容");
        table.Add("DisplayModes.Full.Group.Description", "點擊媒體列展開的完整控制面板");
        table.Add("DisplayModes.Full.Preset.Compact", "精簡");
        table.Add("DisplayModes.Full.Preset.Custom", "自訂");
        table.Add("DisplayModes.Full.Preset.Full", "完整");
        table.Add("DisplayModes.Full.Row.Enable.Description", "點擊媒體列展開完整控制面板");
        table.Add("DisplayModes.Full.Row.Enable.Title", "啟用完整層");
        table.Add("DisplayModes.Full.Row.MediaControls.Title", "播放控制");
        table.Add("DisplayModes.Full.Row.MediaInfo.Title", "媒體資訊");
        table.Add("DisplayModes.Full.Row.Performance.Title", "效能資訊");
        table.Add("DisplayModes.Full.Row.Preset.Description", "一次套用一組分區顯示方案");
        table.Add("DisplayModes.Full.Row.Preset.Title", "套用預設");
        table.Add("DisplayModes.Header.Subtitle", "媒體列的顯示位置、寬度與三種顯示狀態");
        table.Add("DisplayModes.Hover.Expander.Description", "選擇懸停時出現的控制項");
        table.Add("DisplayModes.Hover.Expander.Title", "懸停層控制");
        table.Add("DisplayModes.Hover.Group.Description", "滑鼠移入媒體列時出現的快捷控制");
        table.Add("DisplayModes.Hover.Row.Enable.Description", "滑鼠移入媒體列時顯示快捷控制按鈕");
        table.Add("DisplayModes.Hover.Row.Enable.Title", "啟用懸停層");
        table.Add("DisplayModes.Hover.Row.Progress.Title", "進度條");
        table.Add("DisplayModes.Island.Group.Description", "動態島本身的外觀，與工作列互不影響");
        table.Add("DisplayModes.Island.Notice", "動態島模式尚未實作，因此下面的選項目前為唯讀，變更不會影響正在執行的工作列媒體列。");
        table.Add("DisplayModes.Island.Row.Corner.Description", "0–24 DIP");
        table.Add("DisplayModes.Island.Row.Corner.Title", "圓角");
        table.Add("DisplayModes.Island.Row.Opacity.Description", "數值越高越不透明");
        table.Add("DisplayModes.Island.Row.Opacity.Title", "背景不透明度");
        table.Add("DisplayModes.Island.Row.Surface.Description", "動態島本身的背景樣式");
        table.Add("DisplayModes.Island.Row.Surface.Title", "背景樣式");
        table.Add("DisplayModes.Island.Surface.Automatic", "自動");
        table.Add("DisplayModes.Island.Surface.Solid", "純色");
        table.Add("DisplayModes.Island.Surface.ThemeTint", "佈景主題色調");
        table.Add("DisplayModes.Mode.Current", "目前模式");
        table.Add("DisplayModes.Mode.DesktopCard", "桌面卡片");
        table.Add("DisplayModes.Mode.DesktopCard.Caption", "在桌面放置可自由配置的媒體卡片");
        table.Add("DisplayModes.Mode.DynamicIsland.Caption", "以螢幕邊緣浮層承載媒體狀態");
        table.Add("DisplayModes.Mode.FloatingBall", "懸浮球");
        table.Add("DisplayModes.Mode.FloatingBall.Caption", "以精簡懸浮入口展開控制");
        table.Add("DisplayModes.Mode.PreviewNotice", "目前執行模式固定為工作列。選擇其他模式只切換本頁顯示的內容，不會切換正在執行的視窗。");
        table.Add("DisplayModes.Mode.Taskbar", "工作列");
        table.Add("DisplayModes.Mode.Taskbar.Caption", "置於 Windows 工作列，含靜置層、懸停層與完整層");
        table.Add("DisplayModes.Monitor.DisconnectedSuffix", "（目前未連接）");
        table.Add("DisplayModes.Placement.Group.Description", "媒體列所在的顯示器與工作列位置");
        table.Add("DisplayModes.Placement.Orientation.Auto", "自動（跟隨工作列）");
        table.Add("DisplayModes.Placement.Orientation.Horizontal", "強制橫向");
        table.Add("DisplayModes.Placement.Orientation.Vertical", "強制縱向");
        table.Add("DisplayModes.Placement.ResetAction", "重設");
        table.Add("DisplayModes.Placement.Row.AvoidIcons.Description", "自動避開工作列圖示區域，避免遮擋");
        table.Add("DisplayModes.Placement.Row.AvoidIcons.Title", "避開工作列圖示");
        table.Add("DisplayModes.Placement.Row.Lock.Description", "鎖定後阻止拖曳");
        table.Add("DisplayModes.Placement.Row.Lock.Title", "鎖定位置");
        table.Add("DisplayModes.Placement.Row.Monitor.Description", "勾選一個或多個顯示器；至少保留一個目標");
        table.Add("DisplayModes.Placement.Row.Offset.Description", "沿跨軸微調媒體列與圖示區之間的間距");
        table.Add("DisplayModes.Placement.Row.Offset.Title", "邊緣位移");
        table.Add("DisplayModes.Placement.Row.Orientation.Description", "自動跟隨工作列方向，也可強制橫向或縱向");
        table.Add("DisplayModes.Placement.Row.Orientation.Title", "排列方向");
        table.Add("DisplayModes.Placement.Row.Reset.Description", "恢復到自動避讓計算出的位置");
        table.Add("DisplayModes.Rest.Component.Artwork", "封面");
        table.Add("DisplayModes.Rest.Component.Artwork.Description", "目前曲目的封面；沒有媒體時是音符，點擊它或在它上面滾動可挑選播放器");
        table.Add("DisplayModes.Rest.Component.MediaText", "媒體文字");
        table.Add("DisplayModes.Rest.Component.MediaText.Description", "標題與歌手；有歌詞時取代為歌詞兩行");
        table.Add("DisplayModes.Rest.Component.OutputDevice", "輸出裝置按鈕");
        table.Add("DisplayModes.Rest.Component.OutputDevice.Description", "點擊開啟輸出裝置選單，在它上面滾動切換裝置");
        table.Add("DisplayModes.Rest.Component.Performance", "效能監控");
        table.Add("DisplayModes.Rest.Component.Performance.Description", "依取樣間隔輪換顯示記憶體、處理器等指標");
        table.Add("DisplayModes.Rest.Component.QuickLaunchNote", "快速啟動小音符");
        table.Add("DisplayModes.Rest.Component.QuickLaunchNote.Description", "沒有媒體時顯示的音符，點擊它或在它上面滾動可挑選播放器");
        table.Add("DisplayModes.Rest.Component.Spectrum", "頻譜");
        table.Add("DisplayModes.Rest.Component.Spectrum.Description", "目前輸出裝置的即時頻譜；有聲音就動，與前台播放器無關");
        table.Add("DisplayModes.Rest.Component.Volume", "音量按鈕");
        table.Add("DisplayModes.Rest.Component.Volume.Description", "點擊開啟音量選單，在它上面滾動調整目前來源的音量");
        table.Add("DisplayModes.Rest.ContentLayout.AdaptiveStack", "自適應堆疊");
        table.Add("DisplayModes.Rest.ContentLayout.CompactInline", "精簡行內");
        table.Add("DisplayModes.Rest.Density.Balanced", "均衡");
        table.Add("DisplayModes.Rest.Density.Information", "資訊優先");
        table.Add("DisplayModes.Rest.Density.Minimal", "精簡");
        table.Add("DisplayModes.Rest.Group.Description", "始終顯示的基本層，承載封面、標題與歌詞");
        table.Add("DisplayModes.Rest.Group.Status", "始終開啟");
        table.Add("DisplayModes.Rest.Idle.Expander.Description", "沒有媒體來源時媒體列上還留哪些元件；一個都不勾選時整條媒體列隱藏");
        table.Add("DisplayModes.Rest.Idle.Expander.Title", "沒有媒體時顯示");
        table.Add("DisplayModes.Rest.Idle.Notice", "封面與媒體文字不在這裡：沒有媒體時它們沒有任何內容可顯示，因此一定不顯示；只留小音符時仍可從它上面滾動挑選播放器。");
        table.Add("DisplayModes.Rest.Notice", "頻譜與效能元件的開關和參數在「媒體與通知 → 靜置層元件」；媒體文字大小在「外觀 → 媒體列文字」。頻譜採集的是目前輸出裝置的全部聲音。");
        table.Add("DisplayModes.Rest.Order.Expander.Description", "順序即媒體列裡由左至右的排列；封面與媒體文字固定在最前面，其餘四個可以上下移動");
        table.Add("DisplayModes.Rest.Order.Expander.Title", "靜置層元件順序");
        table.Add("DisplayModes.Rest.Order.Notice", "封面與媒體文字固定在媒體列最前面，不參與排序（前兩行沒有上下移按鈕）。");
        table.Add("DisplayModes.Rest.Order.Reset.Description", "頻譜、效能監控、輸出裝置按鈕、音量按鈕");
        table.Add("DisplayModes.Rest.Order.Reset.Title", "恢復預設順序");
        table.Add("DisplayModes.Rest.Row.Alignment.Description", "設定媒體文字在媒體列內的對齊方式");
        table.Add("DisplayModes.Rest.Row.Alignment.Title", "標題與歌手對齊");
        table.Add("DisplayModes.Rest.Row.Density.Description", "調整靜置層中各按鈕、進度條之間的間隔");
        table.Add("DisplayModes.Rest.Row.Density.Title", "靜置層間隔");
        table.Add("DisplayModes.Rest.Row.DeviceButton.Description", "點擊開啟輸出裝置選單，在它上面滾動切換裝置；常駐會佔掉媒體文字的位置");
        table.Add("DisplayModes.Rest.Row.DeviceButton.Title", "靜置層顯示輸出裝置按鈕");
        table.Add("DisplayModes.Rest.Row.Entry.Description", "滑鼠移入媒體列或點擊文字區頂部細槓時開啟完整層");
        table.Add("DisplayModes.Rest.Row.Entry.Title", "顯示進入完整層的入口");
        table.Add("DisplayModes.Rest.Row.Layout.Description", "標題與歌手並排一行，或上下堆疊");
        table.Add("DisplayModes.Rest.Row.Layout.Title", "內容排列");
        table.Add("DisplayModes.Rest.Row.Progress.Description", "靜置層底部的唯讀播放進度條；媒體未回報長度時不顯示");
        table.Add("DisplayModes.Rest.Row.Progress.Title", "顯示播放進度");
        table.Add("DisplayModes.Rest.Row.VolumeButton.Description", "點擊開啟音量選單，在它上面滾動調整目前來源的音量；常駐會佔掉媒體文字的位置");
        table.Add("DisplayModes.Rest.Row.VolumeButton.Title", "靜置層顯示音量按鈕");
        table.Add("DisplayModes.Status.Current", "目前：{0}");
        table.Add("DisplayModes.Unimplemented.DesktopCard", "桌面卡片模式尚未實作，暫時沒有可調整的設定。每個模式將擁有各自的設定頁。");
        table.Add("DisplayModes.Unimplemented.FloatingBall", "懸浮球模式尚未實作，暫時沒有可調整的設定。每個模式將擁有各自的設定頁。");
        table.Add("DisplayModes.Width.Group.Description", "媒體列的寬度與內部間距");
        table.Add("DisplayModes.Width.RangeText", "可用範圍：{0:0}–{1:0} DIP");
        table.Add("DisplayModes.Width.Row.Fixed.Badge", "需先關閉跟隨");
        table.Add("DisplayModes.Width.Row.Fixed.Description", "在所需最小寬度與工作列可用寬度之間取值");
        table.Add("DisplayModes.Width.Row.Fixed.Title", "固定寬度");
        table.Add("DisplayModes.Width.Row.Follow.Description", "媒體列寬度隨標題長度自動變化");
        table.Add("DisplayModes.Width.Row.Follow.Title", "跟隨內容長度");
        table.Add("DisplayModes.Width.Row.Spacing.Description", "封面區、文字區與附加元件之間的水平間距");
        table.Add("DisplayModes.Width.Row.Spacing.Title", "元件間距");

        // ---- Interaction ----
        table.Add("Interaction.Header.Subtitle", "為媒體列與托盤上的每種操作指定結果");
        table.Add("Interaction.InApp.Group.Description", "點在靜置層上的結果");
        table.Add("Interaction.Row.ArtworkClick.Description", "與下一個項目可分別設定");
        table.Add("Interaction.Row.ArtworkClick.Title", "點擊封面");
        table.Add("Interaction.Row.ChordWheel.Description", "按住上述按鍵再捲動滾輪");
        table.Add("Interaction.Row.Modifier.Description", "媒體列與托盤共用同一個按鍵");
        table.Add("Interaction.Row.Modifier.Title", "組合滾輪按鍵");
        table.Add("Interaction.Row.PrimaryWheel.Description", "不按組合鍵時的滾輪行為");
        table.Add("Interaction.Row.TextClick.Title", "點擊標題或歌詞");
        table.Add("Interaction.Row.TrayChordWheel.Description", "先顯示裝置候選，停止捲動約 1.2 秒後套用");
        table.Add("Interaction.Row.TrayClick.Description", "右鍵始終開啟功能表；此處設定左鍵單擊行為");
        table.Add("Interaction.Row.TrayClick.Title", "點擊托盤圖示");
        table.Add("Interaction.Row.TrayPrimaryWheel.Description", "僅在指標位於托盤圖示上時生效");
        table.Add("Interaction.SharedModifier.Callout", "使用滑鼠左鍵或右鍵作為按鍵時，滾輪後產生的點擊或功能表會被抑制，避免誤觸。");
        table.Add("Interaction.SharedModifier.Group.Description", "按住該按鍵再捲動滾輪，觸發「組合滾輪」");
        table.Add("Interaction.Disabled", "停用");
        table.Add("Interaction.TrayAction.OpenAudioControl", "開啟音訊控制功能表");
        table.Add("Interaction.TrayAction.OpenContextMenu", "開啟右鍵功能表");
        table.Add("Interaction.TrayAction.OpenCurrentAppVolumeMenu", "開啟目前應用程式音量功能表");
        table.Add("Interaction.TrayAction.OpenOutputDeviceMenu", "開啟輸出裝置功能表");
        table.Add("Interaction.TrayAction.OpenSettings", "開啟設定頁");
        table.Add("Interaction.Wheel.Chord.Title", "組合滾輪");
        table.Add("Interaction.Wheel.Primary.Title", "一般滾輪");

        // ---- Layout ----
        table.Add("Layout.Arrangement.Auto", "自動");
        table.Add("Layout.Arrangement.Horizontal", "橫向");
        table.Add("Layout.Arrangement.Vertical", "縱向");
        table.Add("Layout.Group.Position", "位置");
        table.Add("Layout.Group.Size", "尺寸");
        table.Add("Layout.Group.Window", "視窗");
        table.Add("Layout.IslandBackground.SystemTheme", "系統佈景主題背景");
        table.Add("Layout.IslandBackground.Transparent", "透明背景");
        table.Add("Layout.Page.Subtitle", "調整視窗模式、排列方式與尺寸");
        table.Add("Layout.Page.Title", "版面配置");
        table.Add("Layout.Preset.DynamicIslandHorizontal", "動態島主題（橫向）：可拖曳並支援桌面邊緣收合");
        table.Add("Layout.Preset.DynamicIslandVertical", "動態島主題（直向）：可拖曳並支援桌面邊緣收合");
        table.Add("Layout.Preset.TaskbarHorizontal", "工作列主題（橫向）：配合工作列在螢幕頂端或底部");
        table.Add("Layout.Preset.TaskbarVertical", "工作列主題（直向）：配合工作列在螢幕左側或右側");
        table.Add("Layout.Reset.Button", "還原預設值");
        table.Add("Layout.Row.Arrangement.Description", "設定媒體內容的排列方向");
        table.Add("Layout.Row.Arrangement.Title", "排列方式");
        table.Add("Layout.Row.AvoidIcons.Description", "自動限制長度與位置，避免遮擋工作列圖示");
        table.Add("Layout.Row.AvoidIcons.Title", "避開工作列圖示");
        table.Add("Layout.Row.EdgeOffset.Description", "水平工作列上下移動，垂直工作列左右移動");
        table.Add("Layout.Row.EdgeOffset.Title", "邊緣位移");
        table.Add("Layout.Row.IslandBackground.Description", "使用系統佈景主題配色或透明背景");
        table.Add("Layout.Row.IslandBackground.Title", "背景樣式");
        table.Add("Layout.Row.LengthScale.Description", "調整封面、歌詞、標題等元件之間的間距");
        table.Add("Layout.Row.LengthScale.Title", "元件間距縮放");
        table.Add("Layout.Row.LockPosition.Description", "固定媒體列目前位置");
        table.Add("Layout.Row.LockPosition.Title", "鎖定位置");
        table.Add("Layout.Row.ResetPage.Description", "恢復視窗、方向、縮放、工作列與動態島設定");
        table.Add("Layout.Row.ResetPosition.Description", "恢復預設位置");
        table.Add("Layout.Row.ThicknessScale.Description", "按比例縮放所有元件大小，保持元件間距不變");
        table.Add("Layout.Row.ThicknessScale.Title", "粗細縮放");
        table.Add("Layout.Row.WindowMode.Description", "選擇媒體列顯示的位置");
        table.Add("Layout.Row.WindowMode.Title", "視窗模式");
        table.Add("Layout.WindowMode.Taskbar", "停靠工作列");

        // ---- Lyrics ----
        table.Add("Lyrics.Adoption.FirstArrival", "先到先得");
        table.Add("Lyrics.Adoption.PreferDefaultSource", "偏心預設來源");
        table.Add("Lyrics.Adoption.PreferDefaultSourceWithDeadline", "偏心預設來源（限時）");
        table.Add("Lyrics.DefaultBindings.Add", "添加播放器");
        table.Add("Lyrics.DefaultBindings.Remark.Placeholder", "備註名");
        table.Add("Lyrics.DefaultBindings.Add.Placeholder", "輸入 AppID（AUMID 或其片段）");
        table.Add("Lyrics.DefaultBindings.Expander.Description", "識別正在播放的播放器，並指定它的預設取詞介面；未綁定的播放器沒有預設介面");
        table.Add("Lyrics.DefaultBindings.Expander.Title", "預設取詞介面綁定");
        table.Add("Lyrics.DefaultBindings.None", "不綁定（無預設介面）");
        table.Add("Lyrics.DefaultBindings.Player.Kugou", "酷狗音樂");
        table.Add("Lyrics.DefaultBindings.Player.Netease", "網易雲音樂");
        table.Add("Lyrics.DefaultBindings.Player.QQMusic", "QQ 音樂");
        table.Add("Lyrics.DefaultBindings.Player.SodaMusic", "汽水音樂");
        table.Add("Lyrics.DefaultBindings.Remove", "移除此行");
        table.Add("Lyrics.DefaultBindings.Scan", "掃描正在播放");
        table.Add("Lyrics.QueryStrategy.Concurrent", "同時查詢");
        table.Add("Lyrics.QueryStrategy.Sequential", "按序查詢");
        table.Add("Lyrics.Callout.Display", "有歌詞時，媒體列顯示歌詞；沒有歌詞時顯示標題與歌手。");
        table.Add("Lyrics.Header.Subtitle", "在工作列靜置層顯示目前歌詞");
        table.Add("Lyrics.Row.QueryStrategy.Description", "按序逐個嘗試來源，或同時發出（預設介面與優先級批次同時查詢）；按序時只保留優先級順序");
        table.Add("Lyrics.Row.QueryStrategy.Title", "查詢策略");
        table.Add("Lyrics.Row.AdoptionMode.Description", "並發取詞時如何採納結果；「偏心預設來源」優先採用播放器對應的取詞介面");
        table.Add("Lyrics.Row.AdoptionMode.Title", "結果採納策略");
        table.Add("Lyrics.Row.BatchSize.Description", "每批同時取詞的來源個數；目前批次全部未命中才會請求下一批");
        table.Add("Lyrics.Row.BatchSize.Title", "並發批次數");
        table.Add("Lyrics.Row.Deadline.Description", "優先級來源先返回結果後，再給預設介面這麼長的時間；僅「偏心預設來源（限時）」時生效");
        table.Add("Lyrics.Row.Deadline.Title", "預設介面倒數");
        table.Add("Lyrics.Row.Alignment.Description", "歌詞在靜置層的對齊方式；標題與歌手的對齊在顯示模式頁");
        table.Add("Lyrics.Row.Alignment.Title", "歌詞對齊");
        table.Add("Lyrics.Row.InfoLines.Description", "隱藏作者、作曲、製作等署名行");
        table.Add("Lyrics.Row.InfoLines.Title", "過濾署名行");
        table.Add("Lyrics.Row.MatchStrictness.Description", "依曲名搜尋歌詞時要求的符合程度；越嚴格越不容易配到同名的現場版或翻唱");
        table.Add("Lyrics.Row.MatchStrictness.Title", "搜尋符合嚴格度");
        table.Add("Lyrics.Row.SecondLine.Description", "第二行顯示目前句翻譯、目前句音譯或下一句歌詞；順序即優先順序，缺少的來源自動略過");
        table.Add("Lyrics.Row.SecondLine.Note", "順序即優先順序：排在上面的來源優先使用，沒有內容時往下取");
        table.Add("Lyrics.Row.SecondLine.OrderRow.Description", "上移即提高優先順序");
        table.Add("Lyrics.Row.SecondLine.Title", "第二行內容");
        table.Add("Lyrics.Row.ShowLyrics.Description", "依播放進度同步顯示目前句；關閉後顯示標題與歌手");
        table.Add("Lyrics.Row.ShowLyrics.Title", "顯示即時歌詞");
        table.Add("Lyrics.Row.SyllableHighlight.Description", "目前行帶逐字時間軸時隨播放逐字亮起；暫停、高對比度或系統關閉動畫時不做擦亮");
        table.Add("Lyrics.Row.SyllableHighlight.Title", "逐字擦亮");
        table.Add("Lyrics.Row.TwoLine.Badge", "需先啟用歌詞");
        table.Add("Lyrics.Row.TwoLine.Description", "在目前句下方再顯示一行");
        table.Add("Lyrics.Row.TwoLine.Title", "雙行歌詞");
        table.Add("Lyrics.Row.UnsungOpacity.Badge", "需先開啟逐字擦亮");
        table.Add("Lyrics.Row.UnsungOpacity.Description", "尚未唱到的文字的不透明度；越低對比越明顯（預設 45%）");
        table.Add("Lyrics.Row.UnsungOpacity.Title", "未唱部分不透明度");
        table.Add("Lyrics.Row.LineGap.Badge", "需先開啟雙行歌詞");
        table.Add("Lyrics.Row.LineGap.Description", "按字號的百分比在現有兩行版面之上額外增加的間距，隨字號等比縮放；空間不足時自動收緊，不會裁切文字或縮小字號（預設 0）");
        table.Add("Lyrics.Row.LineGap.Title", "行距");
        table.Add("Lyrics.Row.CharacterSpacing.Description", "按字號的百分比拉開字距，隨字號等比縮放；中文與英文都生效，但不會拆斷單詞（預設 0）");
        table.Add("Lyrics.Row.CharacterSpacing.Title", "字間距");
        table.Add("Lyrics.Row.FixedWidth.Badge", "需先啟用歌詞");
        table.Add("Lyrics.Row.FixedWidth.Description", "開啟後歌詞框保持固定長度，不再隨每句歌詞伸縮；關閉時隨內容自動伸縮（預設關閉）");
        table.Add("Lyrics.Row.FixedWidth.Title", "固定歌詞框長度");
        table.Add("Lyrics.Row.FixedWidth.Length.Description", "固定模式下的歌詞框長度（DIP）；工作列空間不足時自動夾取（預設 240）");
        table.Add("Lyrics.Row.FixedWidth.Length.Title", "歌詞框長度");
        table.Add("Lyrics.SecondLine.NextLine", "下一句歌詞");
        table.Add("Lyrics.SecondLine.Reset.Description", "把順序恢復為 翻譯 → 音譯 → 下一句");
        table.Add("Lyrics.SecondLine.Reset.Title", "恢復預設順序");
        table.Add("Lyrics.SecondLine.Romanization", "目前句音譯");
        table.Add("Lyrics.SecondLine.Translation", "目前句翻譯");
        table.Add("Lyrics.Source.Kugou", "酷狗音樂");
        table.Add("Lyrics.Source.LRCLIB", "LRCLIB");
        table.Add("Lyrics.Source.Netease", "網易雲音樂");
        table.Add("Lyrics.Source.NeteaseSearch", "網易雲音樂（搜尋）");
        table.Add("Lyrics.Source.QQMusic", "QQ 音樂");
        table.Add("Lyrics.Source.SodaMusic", "汽水音樂");
        table.Add("Lyrics.Source.Unknown", "未知來源");
        table.Add("Lyrics.Sources.AllDisabled.Callout", "已關閉全部歌詞來源：不會再發出任何歌詞請求，媒體列只顯示標題與歌手。");
        table.Add("Lyrics.Sources.Callout", "依下面的順序向已啟用的來源請求歌詞，命中即停止；每個來源只發一次請求。");
        table.Add("Lyrics.Sources.Expander.Description", "啟用哪些來源，以及它們的優先順序");
        table.Add("Lyrics.Sources.Expander.Title", "備用來源優先級順序");
        table.Add("Lyrics.Sources.Expander.Title.Sequential", "優先級順序");
        table.Add("Lyrics.Sources.MoveDown", "下移");
        table.Add("Lyrics.Sources.MoveUp", "上移");
        table.Add("Lyrics.Sources.Reset.Action", "恢復預設");
        table.Add("Lyrics.Sources.Reset.Description", "重新啟用全部來源，並依預設優先順序排序");
        table.Add("Lyrics.Sources.Reset.Title", "恢復預設順序");
        table.Add("Lyrics.Sources.Row.Description", "關閉後不再向該來源請求歌詞");
        table.Add("Lyrics.Strictness.Balanced", "均衡");
        table.Add("Lyrics.Strictness.Exact", "精確");
        table.Add("Lyrics.Strictness.Strict", "嚴格");

        // ---- Media ----
        table.Add("Media.Badge.EnableFirst", "需先啟用");
        table.Add("Media.Dialog.Browse.Filter", "應用程式和捷徑 (*.exe;*.lnk)|*.exe;*.lnk");
        table.Add("Media.Dialog.Browse.Title", "選擇媒體應用程式或捷徑");
        table.Add("Media.Header.Subtitle", "媒體來源、快速啟動、靜置層元件與曲目通知");
        table.Add("Media.Metric.ProcessMemory.Title", "本程式記憶體");
        table.Add("Media.Metric.SystemMemory.Description", "至少保留一項，最後一項無法取消");
        table.Add("Media.Metric.SystemMemory.Title", "系統記憶體");
        table.Add("Media.Notification.Details.Description", "選擇位置、停留時間與目標顯示器");
        table.Add("Media.Notification.Details.Title", "通知詳細資料");
        table.Add("Media.Notification.Duration.Title", "停留時間");
        table.Add("Media.Notification.Duration.Value", "{0} 秒");
        table.Add("Media.Notification.Enabled.Description", "曲目切換並開始播放時顯示目前曲目");
        table.Add("Media.Notification.Enabled.Title", "啟用通知");
        table.Add("Media.Notification.FixedMonitor.Title", "固定到哪一台顯示器");
        table.Add("Media.Notification.Fullscreen.Description", "預設在全螢幕視窗前抑制通知");
        table.Add("Media.Notification.Fullscreen.Title", "全螢幕時仍然顯示");
        table.Add("Media.Notification.Position.BottomCenter", "中下");
        table.Add("Media.Notification.Position.BottomLeft", "左下");
        table.Add("Media.Notification.Position.BottomRight", "右下");
        table.Add("Media.Notification.Position.Title", "顯示位置");
        table.Add("Media.Notification.Position.TopCenter", "中上");
        table.Add("Media.Notification.Position.TopLeft", "左上");
        table.Add("Media.Notification.Position.TopRight", "右上");
        table.Add("Media.Notification.TargetMode.Description", "固定顯示器，或跟隨前景視窗所在的顯示器");
        table.Add("Media.Notification.TargetMode.Fixed", "固定顯示器");
        table.Add("Media.Notification.TargetMode.ForegroundWindow", "跟隨前景視窗所在的顯示器");
        table.Add("Media.Performance.Metrics.Description", "選取多個時輪流顯示");
        table.Add("Media.Performance.Metrics.Title", "顯示哪些指標");
        table.Add("Media.Performance.OpenTaskManager.Description", "關閉後點擊效能元件不執行任何操作");
        table.Add("Media.Performance.OpenTaskManager.Title", "點擊效能元件時開啟工作管理員");
        table.Add("Media.Performance.RefreshInterval.Description", "取樣間隔，越小越靈敏（0.5–5 秒）");
        table.Add("Media.Performance.RefreshInterval.Title", "更新間隔");
        table.Add("Media.Performance.RefreshInterval.Value", "{0:0.#} 秒");
        table.Add("Media.Performance.Visible.Description", "在靜置層右側輪流顯示選取的指標");
        table.Add("Media.Performance.Visible.Title", "顯示效能元件");
        table.Add("Media.QuickLaunch.Browse", "瀏覽程式或捷徑");
        table.Add("Media.QuickLaunch.Entries.Description", "調整順序只影響本清單的啟動優先順序");
        table.Add("Media.QuickLaunch.Entries.Title", "已新增的啟動項目");
        table.Add("Media.QuickLaunch.EntryCount", "{0} 項");
        table.Add("Media.QuickLaunch.FromNote.Description", "點擊音符開啟快速啟動清單；滾輪預覽，停止約 1.2 秒後啟動最後一項");
        table.Add("Media.QuickLaunch.FromNote.Title", "無媒體時從音符啟動");
        table.Add("Media.QuickLaunch.MoveDown", "下移一位");
        table.Add("Media.QuickLaunch.MoveUp", "上移一位");
        table.Add("Media.QuickLaunch.Remove", "從快速啟動中移除");
        table.Add("Media.RestComponents.Description", "疊加在靜置層右側的兩個小元件");
        table.Add("Media.SourceFilter.Description", "僅接收清單內的應用程式；關閉後清單仍然保留");
        table.Add("Media.SourceFilter.Title", "來源允許清單");
        table.Add("Media.SourceList.AddToQuickLaunch", "加入快速啟動");
        table.Add("Media.SourceList.AddToQuickLaunch.ToolTip", "只有能自動找到啟動方式的播放器才能加入；找不到時請用「瀏覽程式或捷徑」。");
        table.Add("Media.SourceList.Allow", "允許");
        table.Add("Media.SourceList.Description", "先執行一次播放器，它才會出現在這裡");
        table.Add("Media.SourceList.Title", "已偵測來源");
        table.Add("Media.Spectrum.BandCount.Description", "頻譜柱的數量（9–24）；柱寬固定，柱數越多頻譜越寬");
        table.Add("Media.Spectrum.BandCount.Title", "柱數");
        table.Add("Media.Spectrum.BandCount.Value", "{0} 根");
        table.Add("Media.Spectrum.ContentHeight.Description", "頻譜的高度（14–34 DIP，垂直於工作列方向）；越高柱子越高，頻譜整體不因此變寬");
        table.Add("Media.Spectrum.ContentHeight.Title", "頻譜高度");
        table.Add("Media.Spectrum.ContentHeight.Value", "{0:0} DIP");
        table.Add("Media.Spectrum.Parameters.Description", "柱數、高度、更新頻率與靈敏度");
        table.Add("Media.Spectrum.Parameters.Title", "頻譜參數");
        table.Add("Media.Spectrum.RefreshRate.Description", "頻譜更新頻率（5–30 Hz）");
        table.Add("Media.Spectrum.RefreshRate.Title", "更新頻率");
        table.Add("Media.Spectrum.Sensitivity.Description", "頻譜柱達到最大高度時對應的音訊音量（10%–400%）");
        table.Add("Media.Spectrum.Sensitivity.Title", "靈敏度");
        table.Add("Media.Spectrum.Style.Bars", "柱狀圖");
        table.Add("Media.Spectrum.Style.Description", "頻譜的繪製方式，不改變柱數與佔用寬度");
        table.Add("Media.Spectrum.Style.MirroredBars", "上下對稱柱狀圖");
        table.Add("Media.Spectrum.Style.PixelBars", "像素柱狀圖");
        table.Add("Media.Spectrum.Style.Title", "樣式");
        table.Add("Media.Spectrum.Style.Waveform", "波形圖");
        table.Add("Media.Spectrum.Visible.Description", "在靜置層右側顯示即時音訊頻譜");
        table.Add("Media.Spectrum.Visible.Title", "顯示頻譜");
        table.Add("Media.Status.AddedToQuickLaunch", "已新增至快速啟動。");
        table.Add("Media.Status.AlreadyFirst", "已經在清單最前面。");
        table.Add("Media.Status.AlreadyInQuickLaunch", "該應用程式已在快速啟動清單中。");
        table.Add("Media.Status.AlreadyLast", "已經在清單最後面。");
        table.Add("Media.Status.OnlyExistingFiles", "只能新增現有的 EXE 或 LNK 檔案。");
        table.Add("Media.Status.SourceLaunchUnresolved", "無法解析該來源的安全啟動方式，請瀏覽 EXE 或 LNK。");

        // ---- Panel ----
        table.Add("Panel.AudioFlyout.AppVolume", "應用程式音量");
        table.Add("Panel.AudioFlyout.Refresh", "重新整理音訊狀態");
        table.Add("Panel.AudioFlyout.SpatialAudio", "空間音效");
        table.Add("Panel.CompactMenu.WindowTitle", "工作列快捷選單");
        table.Add("Panel.FullPanel.NoMedia", "暫無媒體");
        table.Add("Panel.FullPanel.LyricsSource", "歌詞來源：{0}");
        table.Add("Panel.FullPanel.RepeatMode", "循環模式");
        table.Add("Panel.FullPanel.WindowTitle", "媒體完整面板");
        table.Add("Panel.Notification.NowPlaying", "正在播放");
        table.Add("Panel.Notification.WindowTitle", "曲目切換通知");
        table.Add("Panel.Performance.Memory", "記憶體");
        table.Add("Panel.Performance.ProcessMemory", "本程式記憶體");
        table.Add("Panel.QuickLaunch.Empty", "尚未新增應用程式");
        table.Add("Panel.QuickLaunch.Preview", "快速啟動：{0}");
        table.Add("Panel.QuickLaunch.Title", "快速啟動");
        table.Add("Panel.Repeat.All", "清單循環");
        table.Add("Panel.Repeat.Off", "循環關閉");
        table.Add("Panel.Repeat.One", "單曲循環");
        table.Add("Panel.Repeat.Unavailable", "循環無法使用");
        table.Add("Panel.Volume.CurrentAppVolume", "目前應用程式音量");
        table.Add("Panel.Volume.CurrentMedia", "目前媒體");
        table.Add("Panel.Volume.Tooltip", "目前應用程式音量 / 音量混音器");
        table.Add("Panel.Volume.Unavailable", "無法使用");

        // ---- Search ----
        table.Add("Search.About.Developers.Description", "開發人員名單，取自 GitHub 的貢獻者清單");
        table.Add("Search.About.Licenses.Description", "本程式使用的開源套件與衍生程式碼及其授權");
        table.Add("Search.About.ProjectInfo.Description", "倉庫、意見反應入口與使用說明");
        table.Add("Search.About.Sponsors.Description", "贊助者名單，取自倉庫裡的名單檔案");
        table.Add("Search.About.Support.Description", "微信與支付寶收款碼、愛發電贊助連結");
        table.Add("Search.Application.Application.Description", "版本資訊、檢查更新、自動更新、開機自動啟動與介面語言");
        table.Add("Search.Application.Diagnostics.Description", "開啟日誌資料夾（logs\\app.log，出現錯誤時送這個檔案），或把工作集交還給系統");
        table.Add("Search.Application.SettingsFile.Description", "開啟設定資料夾與重設全部設定");
        table.Add("Application.Header.Subtitle", "版本與更新、介面語言、開機自動啟動、設定檔與診斷日誌");
        table.Add("Search.Appearance.Fonts.Description", "英文字型、中文字型與字型粗細");
        table.Add("Search.Appearance.MediaBarText.Description", "媒體列上文字的顏色與大小");
        table.Add("Search.Appearance.ThemeAndBackdrop.Description", "淺色還是深色，以及視窗背景材質");
        table.Add("Search.DisplayModes.ChooseDisplayMode.Description", "選擇工作列、動態島、桌面卡片或懸浮球");
        table.Add("Search.DisplayModes.FullLayer.Description", "點選媒體列展開的面板包含哪些分區");
        table.Add("Search.DisplayModes.HoverLayer.Description", "滑鼠移入媒體列時出現的快速控制");
        table.Add("Search.DisplayModes.IslandAppearance.Description", "動態島的背景樣式、不透明度與圓角，目前唯讀");
        table.Add("Search.DisplayModes.MediaBarWidth.Description", "寬度跟隨內容、固定寬度與元件間距");
        table.Add("Search.DisplayModes.RestLayer.Description", "始終顯示的基礎層：資訊密度、內容排列、對齊、進度顯示與完整層入口");
        table.Add("Search.DisplayModes.ScreenAndPlacement.Description", "媒體列所在的螢幕與工作列位置");
        table.Add("Search.Interaction.InAppRestLayer.Description", "點在靜置層上的結果：點封面、點文字、滾輪");
        table.Add("Search.Interaction.SharedModifier.Description", "媒體列與托盤共用的組合滾輪按鍵");
        table.Add("Search.Interaction.TrayIcon.Description", "托盤圖示的點選與滾輪行為");
        table.Add("Search.Lyrics.Alignment.Description", "歌詞靠左、置中還是靠右");
        table.Add("Search.Lyrics.Display.Description", "顯示歌詞、顯示兩行、第二行顯示什麼、逐字擦亮與署名行過濾");
        table.Add("Search.Lyrics.Sources.Description", "選擇歌詞來源、它們的優先順序與搜尋符合嚴格度");
        table.Add("Search.MediaAndNotifications.MediaSource.Description", "來源允許清單與已偵測來源");
        table.Add("Search.MediaAndNotifications.QuickLaunch.Description", "沒有媒體時從音符啟動播放器");
        table.Add("Search.MediaAndNotifications.RestLayerComponents.Description", "疊加在靜置層右側的頻譜與效能元件");
        table.Add("Search.MediaAndNotifications.TrackChangeNotification.Description", "曲目切換並開始播放時顯示目前曲目");

        // ---- Service ----
        table.Add("Service.MediaSource.Kugou", "酷狗音樂");
        table.Add("Service.MediaSource.NetEaseCloudMusic", "網易雲音樂");
        table.Add("Service.MediaSource.QQMusic", "QQ 音樂");
        table.Add("Service.MediaSource.Unknown", "未知來源");
        table.Add("Service.Startup.ExecutablePathUnavailable", "無法確定程式路徑，無法寫入啟動項目");
        table.Add("Service.Startup.RegistryKeyUnavailable", "無法開啟啟動項目登錄機碼");

        // ---- Settings ----
        table.Add("Settings.Legacy.About", "關於 AFMediaBar");
        table.Add("Settings.Legacy.Personalization", "個人化");
        table.Add("Settings.Legacy.Theme", "佈景主題");
        table.Add("Settings.Legacy.ThemeDark", "深色");
        table.Add("Settings.Legacy.ThemeLight", "淺色");
        table.Add("Settings.Search.Placeholder", "搜尋設定");
        table.Add("Settings.Search.Suggestion.Title", "{0} › {1}");

        // ---- Shell ----
        table.Add("Shell.QuickLaunch.Status.Failed", "無法啟動此應用程式，請檢查應用程式是否仍可用。");
        table.Add("Shell.QuickLaunch.Status.InvalidTarget", "啟動目標已失效，請在媒體與通知中重新新增。");

        // ---- Startup ----
        table.Add("Startup.SingleInstance.AlreadyRunning", "AF Media Bar 已在執行，請查看右下角的系統匣圖示（或點選小箭頭展開隱藏圖示）。");

        // ---- Update ----
        table.Add("Update.Channel.Accelerated", "加速站台 {0}");
        table.Add("Update.Channel.Direct", "GitHub 直連");
        table.Add("Update.Install.Blocked.OtherInstances", "程式還有其他執行個體正在執行");
        table.Add("Update.Install.Blocked.Portable", "目前是免安裝版，無法自動安裝");
        table.Add("Update.Navigation.Available", "發現新版本 v{0}");
        table.Add("Update.Navigation.Downloading", "正在下載更新 {0}%");
        table.Add("Update.Navigation.Ready", "更新已就緒（v{0}）");
        table.Add("Update.Navigation.Verifying", "正在校驗更新");
        table.Add("Update.Notification.Body", "發現 v{0}（目前 v{1}）。點擊開啟設定，查看亮點並下載安裝。");
        table.Add("Update.Notification.Title", "AF Media Bar 有新版本");
        table.Add("Update.Reason.DownloadFailed", "下載失敗（網路或磁碟錯誤）");
        table.Add("Update.Reason.DownloadHashMismatch", "安裝程式校驗失敗（SHA-256 不符，收到 {0} 位元組）");
        table.Add("Update.Reason.DownloadHttp", "下載失敗（HTTP {0}）");
        table.Add("Update.Reason.DownloadTimeout", "下載逾時");
        table.Add("Update.Reason.ManifestEmpty", "清單內容為空");
        table.Add("Update.Reason.ManifestEndpointInvalid", "清單網址無效");
        table.Add("Update.Reason.ManifestHttp", "無法存取版本清單（HTTP {0}）");
        table.Add("Update.Reason.ManifestInvalidJson", "清單不是合法的 JSON");
        table.Add("Update.Reason.ManifestNetwork", "無法存取版本清單（網路錯誤）");
        table.Add("Update.Reason.ManifestRootNotObject", "清單根節點不是物件");
        table.Add("Update.Reason.ManifestSchemaInvalid", "清單的 schemaVersion 不是有效版本號");
        table.Add("Update.Reason.ManifestSchemaTooNew", "清單 schemaVersion {0} 高於目前程式支援的 {1}");
        table.Add("Update.Reason.ManifestUnreachable", "無法存取版本清單");
        table.Add("Update.Reason.ManifestVersionMissing", "清單缺少 version");
        table.Add("Update.Reason.ManifestVersionUnparsable", "清單的 version（{0}）無法解析");
        table.Add("Update.Reason.NoUsableSource", "所有下載網址都無法使用");
        table.Add("Update.Reason.PendingRecordMissing", "已下載的安裝程式記錄遺失");
        table.Add("Update.Reason.Unknown", "未知原因");
        table.Add("Update.Reason.VerifyHashMismatch", "已下載的安裝程式 SHA-256 與清單不符，已刪除");
        table.Add("Update.Reason.VerifyUnreadable", "已下載的安裝程式無法讀取，已刪除");
        table.Add("Update.Relative.Days", "{0} 天前");
        table.Add("Update.Relative.Hours", "{0} 小時前");
        table.Add("Update.Relative.JustNow", "剛剛");
        table.Add("Update.Relative.Minutes", "{0} 分鐘前");
        table.Add("Update.Status.Available", "發現新版本 v{0}（目前 v{1}）");
        table.Add("Update.Status.Checking", "正在檢查更新…");
        table.Add("Update.Status.Downloading", "正在下載並校驗安裝程式 {0}%");
        table.Add("Update.Status.Failed", "更新失敗：{0}");
        table.Add("Update.Status.Idle", "尚未檢查更新");
        table.Add("Update.Status.ManualOnly", "發現新版本 v{0}，但清單未提供可自動安裝的安裝程式");
        table.Add("Update.Status.Ready", "更新已就緒（v{0}）· 下次啟動程式時自動安裝，或立即重新啟動並安裝");
        table.Add("Update.Status.ReadyBlocked", "已下載 v{0}，但{1}；可從下載頁手動更新");
        table.Add("Update.Status.Skipped", "已略過 v{0}（目前 v{1}）· 手動檢查仍會顯示該版本");
        table.Add("Update.Status.UpToDate", "已是最新版本（v{0}）");
        table.Add("Update.Status.Verifying", "正在校驗安裝程式 {0}%");
        table.Add("Update.Suffix.Channel", " · {0}");
        table.Add("Update.Suffix.LastCheck", " · 上次檢查 {0}");
        table.Add("Update.Suffix.Mandatory", " · 該版本必須更新");
        table.Add("Update.Tray.Available", "發現新版本 v{0}（點擊查看）");
        table.Add("Update.Tray.Check", "檢查更新");
        table.Add("Update.Tray.Checking", "正在檢查更新…");
        table.Add("Update.Tray.Downloading", "正在下載更新 {0}%");
        table.Add("Update.Tray.Failed", "更新失敗，點擊重試");
        table.Add("Update.Tray.Ready", "更新已就緒（v{0}），點擊重新啟動並安裝");
        table.Add("Update.Tray.Verifying", "正在校驗安裝程式 {0}%");

        // ---- Wheel ----
        table.Add("Wheel.Action.CurrentMediaVolume", "目前媒體音量");
        table.Add("Wheel.Action.MediaSource", "播放來源");
        table.Add("Wheel.Hint.Chord", "{0} + 滾輪：{1}");
        table.Add("Wheel.Hint.Plain", "一般滾輪：{0}");
        table.Add("Wheel.Hint.WithValue", "{0}（目前：{1}）");
        table.Add("Wheel.Line.WithValue", "{0}：{1}");
    }
}



