namespace AFMediaBar.Classes.Services.Localization.Strings;

/// <summary>
/// 简体中文文案。
///
/// 一种语言一份文件：翻译与校对只碰这一个文件，新增语言就是再增一个同构文件，并在 <c>Translations</c> 的登记列表里加一行。
/// 键必须与另外两份语言文件完全一致：缺一条时该语言会回退到简体中文，所以漏翻译只能靠逐行对照三份文件发现；
/// 三份文件的键顺序也相同，因此同一行号在三份文件里指的是同一条文案。
/// Simplified Chinese text.
///
/// One file per language: translating and proofreading touch only this file, and adding a language means adding one more
/// file of the same shape plus a line in the registration list inside <c>Translations</c>. The keys have to match the other
/// two files exactly: a missing entry falls back to simplified Chinese, so a gap is found by comparing the three files, and
/// because all three files share one key order the same line number means the same string in every one of them.
/// </summary>
internal static class StringsZhHans
{
    /// <summary>登记本语言文案。/ Registers the text of this language.</summary>
    /// <param name="table">该语言的文案表。/ The text table of this language.</param>
    internal static void Register(LanguageTable table)
    {
        // ---- About ----
        table.Add("About.Header.Subtitle", "开发人员、赞助者与开源许可");
        table.Add("About.Language.Description", "界面文字的显示语言；选「跟随系统」时按 Windows 显示语言决定，切换后立即生效");
        table.Add("About.Language.English", "English");
        table.Add("About.Language.FollowSystem", "跟随系统");
        table.Add("About.Language.SimplifiedChinese", "简体中文");
        table.Add("About.Language.Title", "界面语言");
        table.Add("About.Language.TraditionalChinese", "繁體中文");
        table.Add("About.Language.Vietnamese", "越南语");
        table.Add("About.ResetScope", "所有设置");
        table.Add("About.Row.AutoCheck.Description", "启动约 20 秒后读取公开版本清单；成功后 24 小时内不再自动检查，失败 1 小时后重试。发现新版本时显示一次系统通知，点击通知打开本页");
        table.Add("About.Row.AutoCheck.Title", "自动检查更新");
        table.Add("About.Row.ClearDefaults.Description", "删除已保存的默认设置，重置入口回到程序内置默认值");
        table.Add("About.Row.ClearDefaults.Title", "清除我的默认设置");
        table.Add("About.Row.Download.Download", "下载并安装");
        table.Add("About.Row.DownloadPage.Description", "GitHub 直连不可达时，可用加速站点打开同一个下载页");
        table.Add("About.Row.DownloadPage.Mirror", "加速镜像");
        table.Add("About.Row.DownloadPage.Title", "打开下载页");
        table.Add("About.Row.Install.Description", "下载与校验完成后，下次启动程序时先安装再启动新版本；也可以现在立即安装");
        table.Add("About.Row.Install.Now", "立即重启并安装");
        table.Add("About.Row.Install.Title", "安装更新");
        table.Add("About.Row.OpenFolder.Description", "打开 settings.json 所在文件夹，可直接备份或替换");
        table.Add("About.Row.OpenFolder.Title", "打开设置文件夹");
        table.Add("About.Row.LogFolder.Description", "日志是 logs\\app.log 一个文件，只保留最近 1000 条；出现错误时请把这个文件发出来");
        table.Add("About.Row.LogFolder.Title", "日志文件");
        table.Add("About.Row.TrimMemory.Button", "立即压缩");
        table.Add("About.Row.TrimMemory.Description", "把工作集（占用的物理内存）交还给系统：任务管理器里的读数会立刻下降，下次用到这部分时程序需要重新读回，可能有短暂卡顿；提交大小不变");
        table.Add("About.Row.TrimMemory.Title", "压缩内存占用");
        table.Add("Common.Group.Developers", "开发人员");
        table.Add("Common.Group.Diagnostics", "诊断与日志");
        table.Add("About.Row.Portable.Badge", "便携版");
        table.Add("About.Row.Portable.Description", "当前不是安装版本，无法自动替换文件；请从下载页获取安装包或手动替换程序文件");
        table.Add("About.Row.Portable.Title", "自动更新不可用");
        table.Add("About.Row.Progress.Title", "下载进度");
        table.Add("About.Row.Project.Description", "Windows 任务栏媒体体验 · 版本 1.0.0");
        table.Add("About.Row.Project.Issues", "问题反馈");
        table.Add("About.Row.Project.Star", "在 GitHub 点 Star");
        table.Add("About.Row.ResetAll.Button", "重置全部");
        table.Add("About.Row.ResetAll.Description", "显示模式、交互、歌词、外观与媒体通知全部恢复默认值");
        table.Add("About.Row.ResetAll.Title", "重置全部设置");
        table.Add("About.Row.SaveDefaults.NotSaved", "未保存：各页的「恢复默认设置」回到程序内置默认值");
        table.Add("About.Row.SaveDefaults.Saved", "已保存：各页的「恢复默认设置」都会回到这份快照");
        table.Add("About.Row.SaveDefaults.Title", "保存当前设置为默认");
        table.Add("About.Row.Skip.Clear", "取消跳过");
        table.Add("About.Row.Skip.Description", "跳过只影响自动提示，手动检查仍会显示该版本");
        table.Add("About.Licenses.Open", "查看项目");
        table.Add("About.Support.Afdian", "爱发电");
        table.Add("About.Support.Alipay", "支付宝");
        table.Add("About.Support.Open", "打开链接");
        table.Add("About.Support.Pending", "收款码与赞助链接由作者后续补充；上方的路径就是文件应当放入的位置");
        table.Add("About.Support.SponsorNote", "大于 10 元的赞助可以进入赞助者名单，请在备注中留下 id");
        table.Add("About.Support.WeChat", "微信");
        table.Add("Credits.Contributions", "提交 {0} 次");
        table.Add("Credits.Reason.ContributorsEmpty", "贡献者列表为空");
        table.Add("Credits.Reason.ContributorsShape", "贡献者列表结构不正确");
        table.Add("Credits.Reason.Empty", "名单内容为空");
        table.Add("Credits.Reason.InvalidJson", "名单内容不是有效的 JSON");
        table.Add("Credits.Reason.SchemaTooNew", "赞助名单的结构版本（{0}）高于本程序支持的版本（{1}）");
        table.Add("Credits.Reason.SponsorsShape", "赞助名单结构不正确");
        table.Add("Credits.Sponsors.Count", "共 {0} 位赞助者");
        table.Add("Credits.Sponsors.None", "暂无赞助者。如果这份名单没有出现，请点「重试」，或在仓库的 docs/sponsors.json 里补充");
        table.Add("Credits.SponsorSeparator", "、");
        table.Add("Credits.Status.Failed", "暂时无法获取名单：{0}");
        table.Add("Credits.Status.Partial", "部分名单暂时无法获取：{0}");
        table.Add("Credits.Status.PartialCached", "上次只取到一部分名单");
        table.Add("Credits.Status.Loading", "正在获取开发人员与赞助者名单…");
        table.Add("Credits.Retry", "重试");
        table.Add("About.Row.Startup.Description", "登录 Windows 后自动运行 AF Media Bar（只写入当前用户的启动项）");
        table.Add("About.Row.Startup.Title", "开机自动启动");
        table.Add("About.Row.Version.Check", "检查更新");
        table.Add("About.Row.Version.Description", "当前安装的版本，以及公开清单中的最新版本");
        table.Add("About.Row.Version.Title", "版本");
        table.Add("About.Status.ClearDefaultsFailed", "无法删除默认设置：{0}");
        table.Add("About.Status.SaveDefaultsFailed", "无法保存默认设置：{0}");
        table.Add("About.Status.StartupFailed", "无法修改启动项：{0}");

        // ---- Appearance ----
        table.Add("Appearance.Accent.Custom", "自定义");
        table.Add("Appearance.Accent.FollowSystem", "跟随系统");
        table.Add("Appearance.Accent.HexLabel", "色值");
        table.Add("Appearance.Accent.Hint", "主题色会用到所有强调色的位置：设置页的选中态、开关、滑杆、两类进度条、媒体栏与浮层的高亮，以及完整层的强调段。选「自定义」只影响本程序，Windows 的个性化设置不会被修改；高对比度下仍然使用系统高亮色。");
        table.Add("Appearance.Accent.PaletteLabel", "选择主题色");
        table.Add("Appearance.Backdrop.Acrylic", "亚克力（Acrylic）");
        table.Add("Appearance.Backdrop.Mica", "云母（Mica）");
        table.Add("Appearance.Backdrop.MicaAlt", "云母 Alt（Mica Alt）");
        table.Add("Appearance.Backdrop.Solid", "纯色");
        table.Add("Appearance.BackdropTint.Hint", "只在材质由本程序绘制时生效：Windows 10 上的窗口，以及永不获取焦点的曲目通知（系统材质要求窗口处于前台，通知从不激活，因此它的模糊由本程序绘制）。Windows 11 的云母与亚克力由系统绘制，不受此值影响。值越低越通透，过高则接近纯色。");
        table.Add("Appearance.CjkFont.FollowSystem", "跟随系统");
        table.Add("Appearance.LatinFont.FollowSystem", "跟随系统");
        table.Add("Appearance.Header.Subtitle", "字体、主题、窗口背景与媒体栏文字");
        table.Add("Appearance.Motion.Detail.Full", "保留展开、反馈和频谱过渡");
        table.Add("Appearance.Motion.Detail.Instant", "跟随系统设置，避免过渡延迟");
        table.Add("Appearance.Motion.Detail.Reduced", "已关闭模糊、跑马灯和连续频谱");
        table.Add("Appearance.Motion.Mode.Full", "完整动效");
        table.Add("Appearance.Motion.Mode.Instant", "即时更新");
        table.Add("Appearance.Motion.Mode.Reduced", "轻量动效");
        table.Add("Appearance.Preview.DarkWallpaper", "深色壁纸");
        table.Add("Appearance.Preview.Hint", "自动模式的结果取决于任务栏那一块的实际颜色，因此两块预览为示意；强制模式在两块上使用同一种文字颜色。");
        table.Add("Appearance.Preview.LightWallpaper", "浅色壁纸");
        table.Add("Appearance.Row.Accent.Description", "默认跟随系统；自定义只改本程序，不改 Windows 设置");
        table.Add("Appearance.Row.Accent.Title", "主题色");
        table.Add("Appearance.Row.Backdrop.Description", "统一设置窗口、托盘弹窗与右键菜单的背衬");
        table.Add("Appearance.Row.Backdrop.Title", "窗口背景材质");
        table.Add("Appearance.Row.BackdropTint.Description", "应用自己绘制的材质底色浓度（30%–100%）");
        table.Add("Appearance.Row.BackdropTint.Title", "材质浓度");
        table.Add("Appearance.Row.CjkFont.Description", "汉字使用的字体");
        table.Add("Appearance.Row.CjkFont.Title", "中文字体");
        table.Add("Appearance.Row.FontWeight.Description", "设置窗口、媒体栏与通知共用的文字粗细");
        table.Add("Appearance.Row.FontWeight.Title", "字体粗细");
        table.Add("Appearance.Row.LatinFont.Description", "字母与数字使用的字体");
        table.Add("Appearance.Row.LatinFont.Title", "西文字体");
        table.Add("Appearance.Row.MediaFontSize.Description", "按百分比缩放静置层的标题、歌手与歌词字号（80%–125%）");
        table.Add("Appearance.Row.MediaFontSize.Title", "媒体文字大小");
        table.Add("Appearance.Row.Motion.Title", "交互动效");
        table.Add("Appearance.Row.TextColor.Description", "自动依据文字背后的实际颜色选择深浅");
        table.Add("Appearance.Row.TextColor.Title", "文字颜色");
        table.Add("Appearance.Row.Theme.Description", "自动跟随 Windows 的浅色 / 深色设置");
        table.Add("Appearance.Row.Theme.Title", "应用主题");
        table.Add("Appearance.Specimen.Label", "字样预览");
        table.Add("Appearance.TextColor.Automatic", "自动（根据背景）");
        table.Add("Appearance.TextColor.DarkText", "始终深色文字");
        table.Add("Appearance.TextColor.LightText", "始终浅色文字");
        table.Add("Appearance.Theme.Automatic", "自动（跟随系统）");
        table.Add("Appearance.Theme.Dark", "深色");
        table.Add("Appearance.Theme.Light", "浅色");

        // ---- Audio ----
        table.Add("Audio.Application.SystemSounds", "系统声音");
        table.Add("Audio.Error.CreateDeviceEnumerator", "无法创建 Windows 音频设备枚举器。");
        table.Add("Audio.Error.CreatePolicyConfig", "无法创建 Windows 音频策略服务。");
        table.Add("Audio.OutputDevice.Unavailable", "输出设备：不可用");
        table.Add("Audio.OutputDevice.Unchanged", "输出设备：未改变");
        table.Add("Audio.OutputDevice.Value", "输出设备：{0}");
        table.Add("Audio.Spatial.Enabled", "已启用");
        table.Add("Audio.Spatial.NoDevice", "无输出设备");
        table.Add("Audio.Spatial.Off", "关闭");
        table.Add("Audio.Spatial.Unavailable", "状态不可用");
        table.Add("Audio.Spatial.Unsupported", "此设备不支持");
        table.Add("Audio.Status.AdjustApplicationVolumeFailed", "调节 {0} 音量失败：{1}");
        table.Add("Audio.Status.NoSessions", "当前没有应用音频会话");
        table.Add("Audio.Status.OpenSoundSettingsFailed", "无法打开系统声音设置：{0}");
        table.Add("Audio.Status.ReadFailed", "读取音频状态失败：{0}");
        table.Add("Audio.Status.SwitchOutputDeviceFailed", "切换输出设备失败：{0}");
        table.Add("Audio.Tooltip.AdjustVolumeFailed", "音量调节失败");
        table.Add("Audio.Tooltip.SwitchOutputDeviceFailed", "输出设备切换失败");
        table.Add("Audio.Tooltip.WheelDisabled", "托盘滚轮已禁用");
        table.Add("Audio.Volume.CurrentValue", "{0} {1}%");
        table.Add("Audio.Volume.Unavailable", "当前媒体音量：不可用");
        table.Add("Audio.Volume.Unchanged", "当前媒体音量：未改变");
        table.Add("Audio.Volume.Value", "{0}：{1}%");

        // ---- Common ----
        table.Add("Common.ActivateSourceApplication", "打开播放中的程序");
        table.Add("Common.AdjustCurrentMediaVolume", "调节当前媒体音量");
        table.Add("Common.AlignCenter", "居中");
        table.Add("Common.AlignLeft", "左对齐");
        table.Add("Common.AlignRight", "右对齐");
        table.Add("Common.AudioControl", "音频控制");
        table.Add("Common.Cancel", "取消");
        table.Add("Common.Clear", "清除");
        table.Add("Common.DynamicIsland", "灵动岛");
        table.Add("Common.Exit", "退出");
        table.Add("Common.FullLayer", "完整层");
        table.Add("Common.Group.Application", "应用");
        table.Add("Common.Group.ChooseDisplayMode", "选择显示模式");
        table.Add("Common.Group.Fonts", "字体");
        table.Add("Common.Group.InAppRestLayer", "程序内（静置层）");
        table.Add("Common.Group.IslandAppearance", "灵动岛外观");
        table.Add("Common.Group.Licenses", "开源许可");
        table.Add("Common.Group.LyricsAlignment", "对齐");
        table.Add("Common.Group.LyricsDisplay", "显示");
        table.Add("Common.Group.LyricsSources", "取词来源");
        table.Add("Common.Group.MediaBarText", "媒体栏文字");
        table.Add("Common.Group.MediaBarWidth", "媒体栏宽度");
        table.Add("Common.Group.ProjectInfo", "项目信息");
        table.Add("Common.Group.QuickLaunch", "快速启动");
        table.Add("Common.Group.RestLayerComponents", "静置层组件");
        table.Add("Common.Group.ScreenAndPlacement", "屏幕与位置");
        table.Add("Common.Group.SettingsFile", "设置文件");
        table.Add("Common.Group.SharedModifier", "共用的按键");
        table.Add("Common.Group.Sponsors", "赞助者名单");
        table.Add("Common.Group.Support", "赞助我");
        table.Add("Common.Group.ThemeAndBackdrop", "主题与背景");
        table.Add("Common.Group.TrackChangeNotification", "曲目切换通知");
        table.Add("Common.HoverLayer", "悬停层");
        table.Add("Common.MediaSource", "媒体来源");
        table.Add("Common.Modifier.LeftMouseButton", "鼠标左键");
        table.Add("Common.Modifier.RightMouseButton", "鼠标右键");
        table.Add("Common.Modifier.Shift", "Shift 键");
        table.Add("Common.Monitor.PrimarySuffix", "（主显示器）");
        table.Add("Common.NextTrack", "下一首");
        table.Add("Common.NotBound", "未绑定");
        table.Add("Common.NotImplemented", "未实现");
        table.Add("Common.OpenFolder", "打开文件夹");
        table.Add("Common.OpenFullPanel", "打开完整层");
        table.Add("Common.OutputDevice", "输出设备");
        table.Add("Common.Page.About", "关于");
        table.Add("Common.Page.Application", "应用");
        table.Add("Common.Page.Appearance", "外观");
        table.Add("Common.Page.DisplayModes", "显示模式");
        table.Add("Common.Page.Interaction", "交互");
        table.Add("Common.Page.Lyrics", "歌词");
        table.Add("Common.Page.MediaAndNotifications", "媒体与通知");
        table.Add("Common.PlayPause", "播放 / 暂停");
        table.Add("Common.PreviousNextTrack", "上一首 / 下一首");
        table.Add("Common.PreviousTrack", "上一首");
        table.Add("Common.ReconnectSmtc", "重新连接 SMTC");
        table.Add("Common.ReloadTaskbarHost", "重新加载任务栏媒体栏");
        table.Add("Common.ResetDialog.Confirm", "恢复");
        table.Add("Common.ResetDialog.Content", "将重置「{0}」中的全部选项，其它页面与当前播放不受影响。");
        table.Add("Common.ResetDialog.Title", "恢复默认设置");
        table.Add("Common.ResetPageDefaults", "恢复本页默认设置");
        table.Add("Common.ResetPosition", "重置位置");
        table.Add("Common.RestLayer", "静置层");
        table.Add("Common.Save", "保存");
        table.Add("Common.Settings", "设置");
        table.Add("Common.SkipVersion", "跳过此版本");
        table.Add("Common.SwitchMediaSource", "切换媒体源");
        table.Add("Common.SwitchOutputDevice", "切换输出设备");
        table.Add("Common.SwitchPlayer", "切换播放器");
        table.Add("Common.TargetMonitor", "目标显示器");
        table.Add("Common.TrayIcon", "托盘图标");

        // ---- Diagram ----
        table.Add("Diagram.DynamicIslandSurface.Caption", "灵动岛模式尚未实现，因此下面三项当前只读；它的外观与任务栏互不影响。");
        table.Add("Diagram.InputGestures.Caption", "媒体栏上仅这两个区域可以点击，并且可分别设置；展开面板中的按钮不受影响。");
        table.Add("Diagram.InputGestures.Label.ArtworkClick", "点击封面");
        table.Add("Diagram.InputGestures.Label.TextClick", "点击标题或歌词");
        table.Add("Diagram.LayerFull.Caption", "点击媒体栏展开的面板，四个分区可分别关闭，至少保留一个。");
        table.Add("Diagram.LayerFull.Label.MediaInfo", "媒体信息");
        table.Add("Diagram.LayerFull.Label.Performance", "性能");
        table.Add("Diagram.LayerFull.Label.Playback", "播放控制");
        table.Add("Diagram.LayerHover.Caption", "鼠标移入时出现播放、切换、输出设备、音量与进度控制，可在下页逐项开关。");
        table.Add("Diagram.LayerRest.Caption", "始终显示封面与标题；频谱和性能组件叠加在右侧，其开关位于「媒体与通知 → 静置层组件」。");
        table.Add("Diagram.LyricsAlignment.Caption", "仅决定歌词靠哪一侧；标题与歌手的对齐是「显示模式」页中的另一项设置。");
        table.Add("Diagram.LyricsTwoLine.Caption", "第一行为当前句；第二行为下一句或翻译，静置层空间不足时不显示。");
        table.Add("Diagram.LyricsTwoLine.Label.FirstLine", "第一行");
        table.Add("Diagram.LyricsTwoLine.Label.SecondLine", "第二行");
        table.Add("Diagram.NotificationPlacement.Caption", "共六个位置可选，高亮方块为当前选择；切换显示器只改变出现位置。");
        table.Add("Diagram.NotificationPlacement.Label.AvoidTaskbar", "底部位置会自动避开任务栏");
        table.Add("Diagram.NotificationPlacement.Label.InsideMonitor", "通知出现在选中的显示器内");
        table.Add("Diagram.Spectrum.Caption", "图示为 9 根频谱柱，最右一根处于关闭状态。刷新率决定响应速度，灵敏度决定相同音量下的柱高。");
        table.Add("Diagram.TaskbarLength.Caption", "跟随内容时宽度自动变化；关闭跟随后可指定固定宽度，取值范围由当前任务栏决定。");
        table.Add("Diagram.TaskbarLength.Label.MinimumWidth", "所需最小宽度");
        table.Add("Diagram.TaskbarLength.Label.TaskbarLimit", "任务栏安全上限");
        table.Add("Diagram.TaskbarPlacement.Caption", "媒体栏自动避开任务栏图标；边缘偏移用于调整它与图标区之间的间距。");
        table.Add("Diagram.TaskbarPlacement.Label.EdgeOffset", "边缘偏移 −20 ~ +20 像素");
        table.Add("Diagram.TaskbarPlacement.Label.TaskbarIcons", "任务栏图标");
        table.Add("Diagram.TrayOverflow.Caption", "高亮方块为本程序，默认位于隐藏图标区；需在 Windows 任务栏设置中将其拖出，托盘点击与滚轮才会生效。");
        table.Add("Diagram.TrayOverflow.Label.OverflowArrow", "收进小箭头");
        table.Add("Diagram.TrayOverflow.Label.TrayArea", "托盘区");
        table.Add("Diagram.WheelGestures.Caption", "向上与向下没有固定含义，取决于绑定的动作。切换设备时先显示候选，停止滚动约 1.2 秒后应用。");
        table.Add("Diagram.WheelGestures.Label.MediaBar", "媒体栏上");
        table.Add("Diagram.WheelGestures.Label.MediaBarResults", "四种结果都能绑：上下首、切换设备或播放器、调节音量");
        table.Add("Diagram.WheelGestures.Label.TrayResults", "只有切换设备和调节音量两种结果");

        // ---- DisplayModes ----
        table.Add("DisplayModes.Full.Expander.Description", "选择面板包含的分区，至少保留一个");
        table.Add("DisplayModes.Full.Expander.Title", "完整层内容");
        table.Add("DisplayModes.Full.Group.Description", "点击媒体栏展开的完整控制面板");
        table.Add("DisplayModes.Full.Preset.Compact", "紧凑");
        table.Add("DisplayModes.Full.Preset.Custom", "自定义");
        table.Add("DisplayModes.Full.Preset.Full", "完整");
        table.Add("DisplayModes.Full.Row.Enable.Description", "点击媒体栏展开完整控制面板");
        table.Add("DisplayModes.Full.Row.Enable.Title", "启用完整层");
        table.Add("DisplayModes.Full.Row.MediaControls.Title", "播放控制");
        table.Add("DisplayModes.Full.Row.MediaInfo.Title", "媒体信息");
        table.Add("DisplayModes.Full.Row.Performance.Title", "性能信息");
        table.Add("DisplayModes.Full.Row.Preset.Description", "一次应用一组分区显隐方案");
        table.Add("DisplayModes.Full.Row.Preset.Title", "套用预设");
        table.Add("DisplayModes.Header.Subtitle", "媒体栏的显示位置、宽度与三种显示状态");
        table.Add("DisplayModes.Hover.Expander.Description", "选择悬停时出现的控制项");
        table.Add("DisplayModes.Hover.Expander.Title", "悬停层控制");
        table.Add("DisplayModes.Hover.Group.Description", "鼠标移入媒体栏时出现的快捷控制");
        table.Add("DisplayModes.Hover.Row.Enable.Description", "鼠标移入媒体栏时显示快捷控制按钮");
        table.Add("DisplayModes.Hover.Row.Enable.Title", "启用悬停层");
        table.Add("DisplayModes.Hover.Row.Progress.Title", "进度条");
        table.Add("DisplayModes.Island.Group.Description", "灵动岛自己的外观，与任务栏互不影响");
        table.Add("DisplayModes.Island.Notice", "灵动岛模式尚未实现，因此下面的选项当前只读，改动不会影响正在运行的任务栏媒体栏。");
        table.Add("DisplayModes.Island.Row.Corner.Description", "0–24 DIP");
        table.Add("DisplayModes.Island.Row.Corner.Title", "圆角");
        table.Add("DisplayModes.Island.Row.Opacity.Description", "数值越高越不透明");
        table.Add("DisplayModes.Island.Row.Opacity.Title", "背景不透明度");
        table.Add("DisplayModes.Island.Row.Surface.Description", "灵动岛自身的背景样式");
        table.Add("DisplayModes.Island.Row.Surface.Title", "背景样式");
        table.Add("DisplayModes.Island.Surface.Automatic", "自动");
        table.Add("DisplayModes.Island.Surface.Solid", "纯色");
        table.Add("DisplayModes.Island.Surface.ThemeTint", "主题色调");
        table.Add("DisplayModes.Mode.Current", "当前模式");
        table.Add("DisplayModes.Mode.DesktopCard", "桌面卡片");
        table.Add("DisplayModes.Mode.DesktopCard.Caption", "在桌面放置可自由布局的媒体卡片");
        table.Add("DisplayModes.Mode.DynamicIsland.Caption", "以屏幕边缘浮层承载媒体状态");
        table.Add("DisplayModes.Mode.FloatingBall", "悬浮球");
        table.Add("DisplayModes.Mode.FloatingBall.Caption", "以紧凑悬浮入口展开控制");
        table.Add("DisplayModes.Mode.PreviewNotice", "当前运行模式固定为任务栏。选择其它模式只切换本页显示的内容，不会切换正在运行的窗口。");
        table.Add("DisplayModes.Mode.Taskbar", "任务栏");
        table.Add("DisplayModes.Mode.Taskbar.Caption", "置于 Windows 任务栏，含静置层、悬停层与完整层");
        table.Add("DisplayModes.Monitor.DisconnectedSuffix", "（当前未连接）");
        table.Add("DisplayModes.Placement.Group.Description", "媒体栏所在的显示器与任务栏位置");
        table.Add("DisplayModes.Placement.Orientation.Auto", "自动（跟随任务栏）");
        table.Add("DisplayModes.Placement.Orientation.Horizontal", "强制横向");
        table.Add("DisplayModes.Placement.Orientation.Vertical", "强制纵向");
        table.Add("DisplayModes.Placement.ResetAction", "重置");
        table.Add("DisplayModes.Placement.Row.AvoidIcons.Description", "自动避开任务栏图标区域，避免遮挡");
        table.Add("DisplayModes.Placement.Row.AvoidIcons.Title", "避开任务栏图标");
        table.Add("DisplayModes.Placement.Row.Lock.Description", "锁定后阻止拖动");
        table.Add("DisplayModes.Placement.Row.Lock.Title", "锁定位置");
        table.Add("DisplayModes.Placement.Row.Monitor.Description", "勾选一个或多个显示器；至少保留一个目标");
        table.Add("DisplayModes.Placement.Row.Offset.Description", "沿跨轴微调媒体栏与图标区之间的间距");
        table.Add("DisplayModes.Placement.Row.Offset.Title", "边缘偏移");
        table.Add("DisplayModes.Placement.Row.Orientation.Description", "自动跟随任务栏方向，也可强制横向或纵向");
        table.Add("DisplayModes.Placement.Row.Orientation.Title", "排列方向");
        table.Add("DisplayModes.Placement.Row.Reset.Description", "恢复到自动避让计算出的位置");
        table.Add("DisplayModes.Rest.Component.Artwork", "封面");
        table.Add("DisplayModes.Rest.Component.Artwork.Description", "当前曲目的封面；没有媒体时是音符，点击它或在其上滚动可挑选播放器");
        table.Add("DisplayModes.Rest.Component.MediaText", "媒体文字");
        table.Add("DisplayModes.Rest.Component.MediaText.Description", "标题与歌手；有歌词时替换为歌词两行");
        table.Add("DisplayModes.Rest.Component.OutputDevice", "输出设备按钮");
        table.Add("DisplayModes.Rest.Component.OutputDevice.Description", "点击打开输出设备菜单，在其上滚动切换设备");
        table.Add("DisplayModes.Rest.Component.Performance", "性能监控");
        table.Add("DisplayModes.Rest.Component.Performance.Description", "按采样间隔轮换显示内存、处理器等指标");
        table.Add("DisplayModes.Rest.Component.QuickLaunchNote", "快速启动小音符");
        table.Add("DisplayModes.Rest.Component.QuickLaunchNote.Description", "没有媒体时显示的音符，点击它或在其上滚动可挑选播放器");
        table.Add("DisplayModes.Rest.Component.Spectrum", "频谱");
        table.Add("DisplayModes.Rest.Component.Spectrum.Description", "当前输出设备的实时频谱；有声音就动，与前台播放器无关");
        table.Add("DisplayModes.Rest.Component.Volume", "音量按钮");
        table.Add("DisplayModes.Rest.Component.Volume.Description", "点击打开音量菜单，在其上滚动调节当前来源的音量");
        table.Add("DisplayModes.Rest.ContentLayout.AdaptiveStack", "自适应堆叠");
        table.Add("DisplayModes.Rest.ContentLayout.CompactInline", "紧凑行内");
        table.Add("DisplayModes.Rest.Density.Balanced", "均衡");
        table.Add("DisplayModes.Rest.Density.Information", "信息优先");
        table.Add("DisplayModes.Rest.Density.Minimal", "精简");
        table.Add("DisplayModes.Rest.Group.Description", "始终显示的基础层，承载封面、标题与歌词");
        table.Add("DisplayModes.Rest.Group.Status", "始终开启");
        table.Add("DisplayModes.Rest.Idle.Expander.Description", "没有媒体来源时媒体栏上还留哪些组件；一个都不勾选时整条媒体栏隐藏");
        table.Add("DisplayModes.Rest.Idle.Expander.Title", "没有媒体时显示");
        table.Add("DisplayModes.Rest.Idle.Notice", "封面与媒体文字不在这里：没有媒体时它们没有任何内容可显示，因此一定不显示；只留小音符时仍可从它上面滚动挑选播放器。");
        table.Add("DisplayModes.Rest.Notice", "频谱与性能组件的开关和参数在「媒体与通知 → 静置层组件」；媒体文字大小在「外观 → 媒体栏文字」。频谱采集的是当前输出设备的全部声音。");
        table.Add("DisplayModes.Rest.Order.Expander.Description", "顺序即媒体栏里从左到右的排列；封面与媒体文字固定在最前面，其余四个可以上下移动");
        table.Add("DisplayModes.Rest.Order.Expander.Title", "静置层组件顺序");
        table.Add("DisplayModes.Rest.Order.Notice", "封面与媒体文字固定在媒体栏最前面，不参与排序（前两行没有上下移按钮）。");
        table.Add("DisplayModes.Rest.Order.Reset.Description", "频谱、性能监控、输出设备按钮、音量按钮");
        table.Add("DisplayModes.Rest.Order.Reset.Title", "恢复默认顺序");
        table.Add("DisplayModes.Rest.Row.Alignment.Description", "设置媒体文字在媒体栏内的对齐方式");
        table.Add("DisplayModes.Rest.Row.Alignment.Title", "标题与歌手对齐");
        table.Add("DisplayModes.Rest.Row.Density.Description", "调整静置层中各按钮、进度条间的间隔");
        table.Add("DisplayModes.Rest.Row.Density.Title", "静置层间隔");
        table.Add("DisplayModes.Rest.Row.DeviceButton.Description", "点击打开输出设备菜单，在其上滚动切换设备；常驻会占掉媒体文字的位置");
        table.Add("DisplayModes.Rest.Row.DeviceButton.Title", "静置层显示输出设备按钮");
        table.Add("DisplayModes.Rest.Row.Entry.Description", "鼠标移入媒体栏或点击文字区顶部细杠时打开完整层");
        table.Add("DisplayModes.Rest.Row.Entry.Title", "显示进入完整层的入口");
        table.Add("DisplayModes.Rest.Row.Layout.Description", "标题与歌手并排一行，或上下堆叠");
        table.Add("DisplayModes.Rest.Row.Layout.Title", "内容排列");
        table.Add("DisplayModes.Rest.Row.Progress.Description", "静置层底部的只读播放进度条；媒体未报告时长时不显示");
        table.Add("DisplayModes.Rest.Row.Progress.Title", "显示播放进度");
        table.Add("DisplayModes.Rest.Row.VolumeButton.Description", "点击打开音量菜单，在其上滚动调节当前来源的音量；常驻会占掉媒体文字的位置");
        table.Add("DisplayModes.Rest.Row.VolumeButton.Title", "静置层显示音量按钮");
        table.Add("DisplayModes.Status.Current", "当前：{0}");
        table.Add("DisplayModes.Unimplemented.DesktopCard", "桌面卡片模式尚未实现，暂时没有可调整的设置。每个模式将拥有各自的设置页。");
        table.Add("DisplayModes.Unimplemented.FloatingBall", "悬浮球模式尚未实现，暂时没有可调整的设置。每个模式将拥有各自的设置页。");
        table.Add("DisplayModes.Width.Group.Description", "媒体栏的宽度与内部间距");
        table.Add("DisplayModes.Width.RangeText", "可用范围：{0:0}–{1:0} DIP");
        table.Add("DisplayModes.Width.Row.Fixed.Badge", "需先关闭跟随");
        table.Add("DisplayModes.Width.Row.Fixed.Description", "在所需最小宽度与任务栏可用宽度之间取值");
        table.Add("DisplayModes.Width.Row.Fixed.Title", "固定宽度");
        table.Add("DisplayModes.Width.Row.Follow.Description", "媒体栏宽度随标题长度自动变化");
        table.Add("DisplayModes.Width.Row.Follow.Title", "跟随内容长度");
        table.Add("DisplayModes.Width.Row.Spacing.Description", "封面区、文字区与附加组件之间的水平间距");
        table.Add("DisplayModes.Width.Row.Spacing.Title", "组件间距");

        // ---- Interaction ----
        table.Add("Interaction.Header.Subtitle", "为媒体栏与托盘上的每种操作指定结果");
        table.Add("Interaction.InApp.Group.Description", "点在静置层上的结果");
        table.Add("Interaction.Row.ArtworkClick.Description", "与下一项可分别设置");
        table.Add("Interaction.Row.ArtworkClick.Title", "点击封面");
        table.Add("Interaction.Row.ChordWheel.Description", "按住上述按键再滚动滚轮");
        table.Add("Interaction.Row.Modifier.Description", "媒体栏与托盘共用同一个按键");
        table.Add("Interaction.Row.Modifier.Title", "组合滚轮按键");
        table.Add("Interaction.Row.PrimaryWheel.Description", "不按组合键时的滚轮行为");
        table.Add("Interaction.Row.TextClick.Title", "点击标题或歌词");
        table.Add("Interaction.Row.TrayChordWheel.Description", "先显示设备候选，停止滚动约 1.2 秒后应用");
        table.Add("Interaction.Row.TrayClick.Description", "右键始终打开菜单；此处设置左键单击行为");
        table.Add("Interaction.Row.TrayClick.Title", "点击托盘图标");
        table.Add("Interaction.Row.TrayPrimaryWheel.Description", "仅在指针位于托盘图标上时生效");
        table.Add("Interaction.SharedModifier.Callout", "使用鼠标左键或右键作为按键时，滚轮后产生的点击或菜单会被抑制，避免误触。");
        table.Add("Interaction.SharedModifier.Group.Description", "按住该按键再滚动滚轮，触发「组合滚轮」");
        table.Add("Interaction.Disabled", "禁用");
        table.Add("Interaction.TrayAction.OpenAudioControl", "打开音频控制菜单");
        table.Add("Interaction.TrayAction.OpenContextMenu", "打开右键菜单");
        table.Add("Interaction.TrayAction.OpenCurrentAppVolumeMenu", "打开当前应用音量菜单");
        table.Add("Interaction.TrayAction.OpenOutputDeviceMenu", "打开输出设备菜单");
        table.Add("Interaction.TrayAction.OpenSettings", "打开设置页");
        table.Add("Interaction.Wheel.Chord.Title", "组合滚轮");
        table.Add("Interaction.Wheel.Primary.Title", "普通滚轮");

        // ---- Layout ----
        table.Add("Layout.Arrangement.Auto", "自动");
        table.Add("Layout.Arrangement.Horizontal", "横向");
        table.Add("Layout.Arrangement.Vertical", "纵向");
        table.Add("Layout.Group.Position", "位置");
        table.Add("Layout.Group.Size", "尺寸");
        table.Add("Layout.Group.Window", "窗口");
        table.Add("Layout.IslandBackground.SystemTheme", "系统主题背景");
        table.Add("Layout.IslandBackground.Transparent", "透明背景");
        table.Add("Layout.Page.Subtitle", "调整窗口模式、排列方式和尺寸");
        table.Add("Layout.Page.Title", "布局");
        table.Add("Layout.Preset.DynamicIslandHorizontal", "灵动岛主题（横向）：可拖动并支持桌面边缘收起");
        table.Add("Layout.Preset.DynamicIslandVertical", "灵动岛主题（竖向）：可拖动并支持桌面边缘收起");
        table.Add("Layout.Preset.TaskbarHorizontal", "任务栏主题（横向）：适配任务栏在屏幕顶部或底部");
        table.Add("Layout.Preset.TaskbarVertical", "任务栏主题（竖向）：适配任务栏在屏幕左侧或右侧");
        table.Add("Layout.Reset.Button", "恢复默认");
        table.Add("Layout.Row.Arrangement.Description", "设置媒体内容的排列方向");
        table.Add("Layout.Row.Arrangement.Title", "排列方式");
        table.Add("Layout.Row.AvoidIcons.Description", "自动限制长度和位置，避免遮挡任务栏图标");
        table.Add("Layout.Row.AvoidIcons.Title", "避开任务栏图标");
        table.Add("Layout.Row.EdgeOffset.Description", "水平任务栏上下移动，垂直任务栏左右移动");
        table.Add("Layout.Row.EdgeOffset.Title", "边缘偏移");
        table.Add("Layout.Row.IslandBackground.Description", "使用系统主题配色或透明背景");
        table.Add("Layout.Row.IslandBackground.Title", "背景方案");
        table.Add("Layout.Row.LengthScale.Description", "调整封面、歌词、标题等组件之间的间距");
        table.Add("Layout.Row.LengthScale.Title", "组件间距缩放");
        table.Add("Layout.Row.LockPosition.Description", "固定媒体栏当前位置");
        table.Add("Layout.Row.LockPosition.Title", "锁定位置");
        table.Add("Layout.Row.ResetPage.Description", "恢复窗口、方向、缩放、任务栏和灵动岛设置");
        table.Add("Layout.Row.ResetPosition.Description", "恢复默认位置");
        table.Add("Layout.Row.ThicknessScale.Description", "按比例缩放所有组件大小，保持组件间距不变");
        table.Add("Layout.Row.ThicknessScale.Title", "粗细缩放");
        table.Add("Layout.Row.WindowMode.Description", "选择媒体栏显示在哪里");
        table.Add("Layout.Row.WindowMode.Title", "窗口模式");
        table.Add("Layout.WindowMode.Taskbar", "停靠任务栏");

        // ---- Lyrics ----
        table.Add("Lyrics.Adoption.FirstArrival", "先到先得");
        table.Add("Lyrics.Adoption.PreferDefaultSource", "偏心默认来源");
        table.Add("Lyrics.Adoption.PreferDefaultSourceWithDeadline", "偏心默认来源（限时）");
        table.Add("Lyrics.DefaultBindings.Add", "添加播放器");
        table.Add("Lyrics.DefaultBindings.Remark.Placeholder", "备注名");
        table.Add("Lyrics.DefaultBindings.Add.Placeholder", "输入 AppID");
        table.Add("Lyrics.DefaultBindings.Expander.Description", "识别正在播放的播放器，并指定它的默认取词接口；未绑定的播放器没有默认接口");
        table.Add("Lyrics.DefaultBindings.Expander.Title", "默认取词接口绑定");
        table.Add("Lyrics.DefaultBindings.None", "不绑定（无默认接口）");
        table.Add("Lyrics.DefaultBindings.Player.Kugou", "酷狗音乐");
        table.Add("Lyrics.DefaultBindings.Player.Netease", "网易云音乐");
        table.Add("Lyrics.DefaultBindings.Player.QQMusic", "QQ 音乐");
        table.Add("Lyrics.DefaultBindings.Player.SodaMusic", "汽水音乐");
        table.Add("Lyrics.DefaultBindings.Remove", "移除此行");
        table.Add("Lyrics.DefaultBindings.Scan", "扫描正在播放");
        table.Add("Lyrics.QueryStrategy.Concurrent", "同时查询");
        table.Add("Lyrics.QueryStrategy.Sequential", "按序查询");
        table.Add("Lyrics.Callout.Display", "有歌词时，媒体栏显示歌词；没有歌词时显示标题与歌手。");
        table.Add("Lyrics.Header.Subtitle", "在任务栏静置层显示当前歌词");
        table.Add("Lyrics.Row.QueryStrategy.Description", "按序逐个尝试来源，或同时发出（默认接口与优先级批次同时查询）；按序时只保留优先级顺序");
        table.Add("Lyrics.Row.QueryStrategy.Title", "查询策略");
        table.Add("Lyrics.Row.AdoptionMode.Description", "并发取词时如何采纳结果；「偏心默认来源」优先采用播放器对应的取词接口");
        table.Add("Lyrics.Row.AdoptionMode.Title", "结果采纳策略");
        table.Add("Lyrics.Row.BatchSize.Description", "每批同时取词的来源个数；当前批次全部未命中才会请求下一批");
        table.Add("Lyrics.Row.BatchSize.Title", "优先级单次并发个数");
        table.Add("Lyrics.Row.Deadline.Description", "优先级来源先返回结果后，再给默认接口这么长的时间；仅「偏心默认来源（限时）」时生效");
        table.Add("Lyrics.Row.Deadline.Title", "默认接口倒计时");
        table.Add("Lyrics.Row.Alignment.Description", "歌词在静置层的对齐方式；标题与歌手的对齐在显示模式页");
        table.Add("Lyrics.Row.Alignment.Title", "歌词对齐");
        table.Add("Lyrics.Row.InfoLines.Description", "隐藏作者、作曲、制作等署名行");
        table.Add("Lyrics.Row.InfoLines.Title", "过滤署名行");
        table.Add("Lyrics.Row.MatchStrictness.Description", "按曲名搜索歌词时要求的匹配程度；越严格越不容易匹配到同名的现场版或翻唱");
        table.Add("Lyrics.Row.MatchStrictness.Title", "搜索匹配严格度");
        table.Add("Lyrics.Row.SecondLine.Description", "第二行显示当前句翻译、当前句音译或下一句歌词；顺序即优先级，缺失的来源自动跳过");
        table.Add("Lyrics.Row.SecondLine.Note", "顺序即优先级：排在上面的来源优先使用，没有内容时依次往下取");
        table.Add("Lyrics.Row.SecondLine.OrderRow.Description", "上移即提高优先级");
        table.Add("Lyrics.Row.SecondLine.Title", "第二行内容");
        table.Add("Lyrics.Row.ShowLyrics.Description", "按播放进度同步显示当前句；关闭后显示标题与歌手");
        table.Add("Lyrics.Row.ShowLyrics.Title", "显示实时歌词");
        table.Add("Lyrics.Row.SyllableHighlight.Description", "当前行带逐字时间轴时随播放逐字亮起；暂停、高对比度或系统关闭动画时不做擦亮");
        table.Add("Lyrics.Row.SyllableHighlight.Title", "逐字擦亮");
        table.Add("Lyrics.Row.TwoLine.Badge", "需先启用歌词");
        table.Add("Lyrics.Row.TwoLine.Description", "在当前句下方再显示一行");
        table.Add("Lyrics.Row.TwoLine.Title", "双行歌词");
        table.Add("Lyrics.Row.UnsungOpacity.Badge", "需先开启逐字擦亮");
        table.Add("Lyrics.Row.UnsungOpacity.Description", "尚未唱到的文字的不透明度；越低对比越明显（默认 45%）");
        table.Add("Lyrics.Row.UnsungOpacity.Title", "未唱部分不透明度");
        table.Add("Lyrics.Row.LineGap.Badge", "需先开启双行歌词");
        table.Add("Lyrics.Row.LineGap.Description", "按字号的百分比在现有两行布局之上额外增加的间距，随字号等比缩放；空间不足时自动收紧，不会裁切文字或缩小字号（默认 0）");
        table.Add("Lyrics.Row.LineGap.Title", "行距");
        table.Add("Lyrics.Row.CharacterSpacing.Description", "按字号的百分比拉开字距，随字号等比缩放；中文与英文都生效，但不会拆断单词（默认 0）");
        table.Add("Lyrics.Row.CharacterSpacing.Title", "字间距");
        table.Add("Lyrics.Row.FixedWidth.Badge", "需先启用歌词");
        table.Add("Lyrics.Row.FixedWidth.Description", "开启后歌词框保持固定长度，不再随每句歌词伸缩；关闭时随内容自动伸缩（默认关闭）");
        table.Add("Lyrics.Row.FixedWidth.Title", "固定歌词框长度");
        table.Add("Lyrics.Row.FixedWidth.Length.Description", "固定模式下的歌词框长度（DIP）；任务栏空间不足时自动夹取（默认 240）");
        table.Add("Lyrics.Row.FixedWidth.Length.Title", "歌词框长度");
        table.Add("Lyrics.SecondLine.NextLine", "下一句歌词");
        table.Add("Lyrics.SecondLine.Reset.Description", "把顺序恢复为 下一句 → 翻译 → 音译");
        table.Add("Lyrics.SecondLine.Reset.Title", "恢复默认顺序");
        table.Add("Lyrics.SecondLine.Romanization", "当前句音译");
        table.Add("Lyrics.SecondLine.Translation", "当前句翻译");
        table.Add("Lyrics.Source.Kugou", "酷狗音乐");
        table.Add("Lyrics.Source.LRCLIB", "LRCLIB");
        table.Add("Lyrics.Source.Netease", "网易云音乐");
        table.Add("Lyrics.Source.NeteaseSearch", "网易云音乐（搜索）");
        table.Add("Lyrics.Source.QQMusic", "QQ 音乐");
        table.Add("Lyrics.Source.SodaMusic", "汽水音乐");
        table.Add("Lyrics.Source.Unknown", "未知来源");
        table.Add("Lyrics.Sources.AllDisabled.Callout", "已关闭全部歌词来源：不会再发出任何歌词请求，媒体栏只显示标题与歌手。");
        table.Add("Lyrics.Sources.Callout", "按下面的顺序向已启用的来源请求歌词，命中即停止；每个来源只发一次请求。");
        table.Add("Lyrics.Sources.Expander.Description", "启用哪些来源，以及它们的优先顺序");
        table.Add("Lyrics.Sources.Expander.Title", "备用来源优先级顺序");
        table.Add("Lyrics.Sources.Expander.Title.Sequential", "优先级顺序");
        table.Add("Lyrics.Sources.MoveDown", "下移");
        table.Add("Lyrics.Sources.MoveUp", "上移");
        table.Add("Lyrics.Sources.Reset.Action", "恢复默认");
        table.Add("Lyrics.Sources.Reset.Description", "重新启用全部来源，并按默认优先级排序");
        table.Add("Lyrics.Sources.Reset.Title", "恢复默认顺序");
        table.Add("Lyrics.Sources.Row.Description", "关闭后不再向该来源请求歌词");
        table.Add("Lyrics.Strictness.Balanced", "均衡");
        table.Add("Lyrics.Strictness.Exact", "精确");
        table.Add("Lyrics.Strictness.Strict", "严格");

        // ---- Media ----
        table.Add("Media.Badge.EnableFirst", "需先启用");
        table.Add("Media.Dialog.Browse.Filter", "应用和快捷方式 (*.exe;*.lnk)|*.exe;*.lnk");
        table.Add("Media.Dialog.Browse.Title", "选择媒体应用或快捷方式");
        table.Add("Media.Header.Subtitle", "媒体来源、快速启动、静置层组件与曲目通知");
        table.Add("Media.Metric.ProcessMemory.Title", "本程序内存");
        table.Add("Media.Metric.SystemMemory.Description", "至少保留一项，最后一项无法取消");
        table.Add("Media.Metric.SystemMemory.Title", "系统内存");
        table.Add("Media.Notification.Details.Description", "选择位置、停留时间与目标显示器");
        table.Add("Media.Notification.Details.Title", "通知细节");
        table.Add("Media.Notification.Duration.Title", "停留时间");
        table.Add("Media.Notification.Duration.Value", "{0} 秒");
        table.Add("Media.Notification.Enabled.Description", "曲目切换并开始播放时显示当前曲目");
        table.Add("Media.Notification.Enabled.Title", "启用通知");
        table.Add("Media.Notification.FixedMonitor.Title", "固定到哪一块显示器");
        table.Add("Media.Notification.Fullscreen.Description", "默认在全屏窗口前抑制通知");
        table.Add("Media.Notification.Fullscreen.Title", "全屏时仍然显示");
        table.Add("Media.Notification.Position.BottomCenter", "中下");
        table.Add("Media.Notification.Position.BottomLeft", "左下");
        table.Add("Media.Notification.Position.BottomRight", "右下");
        table.Add("Media.Notification.Position.Title", "显示位置");
        table.Add("Media.Notification.Position.TopCenter", "中上");
        table.Add("Media.Notification.Position.TopLeft", "左上");
        table.Add("Media.Notification.Position.TopRight", "右上");
        table.Add("Media.Notification.TargetMode.Description", "固定显示器，或跟随前台窗口所在显示器");
        table.Add("Media.Notification.TargetMode.Fixed", "固定显示器");
        table.Add("Media.Notification.TargetMode.ForegroundWindow", "跟随前台窗口所在显示器");
        table.Add("Media.Performance.Metrics.Description", "选中多个时轮流显示");
        table.Add("Media.Performance.Metrics.Title", "显示哪些指标");
        table.Add("Media.Performance.OpenTaskManager.Description", "关闭后点击性能组件不执行任何操作");
        table.Add("Media.Performance.OpenTaskManager.Title", "点击性能组件时打开任务管理器");
        table.Add("Media.Performance.RefreshInterval.Description", "采样间隔，越小越灵敏（0.5–5 秒）");
        table.Add("Media.Performance.RefreshInterval.Title", "刷新间隔");
        table.Add("Media.Performance.RefreshInterval.Value", "{0:0.#} 秒");
        table.Add("Media.Performance.Visible.Description", "在静置层右侧轮换显示选中的指标");
        table.Add("Media.Performance.Visible.Title", "显示性能组件");
        table.Add("Media.QuickLaunch.Browse", "浏览程序或快捷方式");
        table.Add("Media.QuickLaunch.Entries.Description", "调整顺序只影响本列表的启动优先级");
        table.Add("Media.QuickLaunch.Entries.Title", "已添加的启动项");
        table.Add("Media.QuickLaunch.EntryCount", "{0} 项");
        table.Add("Media.QuickLaunch.FromNote.Description", "点击音符打开快速启动列表；滚轮预览，停止约 1.2 秒后启动最后一项");
        table.Add("Media.QuickLaunch.FromNote.Title", "无媒体时从音符启动");
        table.Add("Media.QuickLaunch.MoveDown", "下移一位");
        table.Add("Media.QuickLaunch.MoveUp", "上移一位");
        table.Add("Media.QuickLaunch.Remove", "从快速启动中移除");
        table.Add("Media.RestComponents.Description", "叠加在静置层右侧的两个小组件");
        table.Add("Media.SourceFilter.Description", "仅接收列表内的应用；关闭后列表仍然保留");
        table.Add("Media.SourceFilter.Title", "来源允许列表");
        table.Add("Media.SourceList.AddToQuickLaunch", "加入快速启动");
        table.Add("Media.SourceList.AddToQuickLaunch.ToolTip", "只有能自动找到启动方式的播放器才能加入；找不到时请用「浏览程序或快捷方式」。");
        table.Add("Media.SourceList.Allow", "允许");
        table.Add("Media.SourceList.Description", "先运行一次播放器，它才会出现在这里");
        table.Add("Media.SourceList.Title", "已检测来源");
        table.Add("Media.Spectrum.BandCount.Description", "频谱柱的数量（9–24）；柱宽固定，柱数越多频谱越宽");
        table.Add("Media.Spectrum.BandCount.Title", "柱数");
        table.Add("Media.Spectrum.BandCount.Value", "{0} 根");
        table.Add("Media.Spectrum.ContentHeight.Description", "频谱的高度（14–34 DIP，垂直于任务栏方向）；越高柱子越高，频谱整体不因此变宽");
        table.Add("Media.Spectrum.ContentHeight.Title", "频谱高度");
        table.Add("Media.Spectrum.ContentHeight.Value", "{0:0} DIP");
        table.Add("Media.Spectrum.Parameters.Description", "柱数、高度、刷新率与灵敏度");
        table.Add("Media.Spectrum.Parameters.Title", "频谱参数");
        table.Add("Media.Spectrum.RefreshRate.Description", "频谱刷新频率（5–30 Hz）");
        table.Add("Media.Spectrum.RefreshRate.Title", "刷新率");
        table.Add("Media.Spectrum.Sensitivity.Description", "频谱柱达到最大高度时对应的音频音量（10%–400%）");
        table.Add("Media.Spectrum.Sensitivity.Title", "灵敏度");
        table.Add("Media.Spectrum.Style.Bars", "柱状图");
        table.Add("Media.Spectrum.Style.Description", "频谱的绘制方式，不改变柱数与占用宽度");
        table.Add("Media.Spectrum.Style.MirroredBars", "上下对称柱状图");
        table.Add("Media.Spectrum.Style.PixelBars", "像素柱状图");
        table.Add("Media.Spectrum.Style.Title", "样式");
        table.Add("Media.Spectrum.Style.Waveform", "波形图");
        table.Add("Media.Spectrum.Visible.Description", "在静置层右侧显示实时音频频谱");
        table.Add("Media.Spectrum.Visible.Title", "显示频谱");
        table.Add("Media.Status.AddedToQuickLaunch", "已添加到快速启动。");
        table.Add("Media.Status.AlreadyFirst", "已经在列表最前面。");
        table.Add("Media.Status.AlreadyInQuickLaunch", "该应用已在快速启动列表中。");
        table.Add("Media.Status.AlreadyLast", "已经在列表最后面。");
        table.Add("Media.Status.OnlyExistingFiles", "只能添加现有的 EXE 或 LNK 文件。");
        table.Add("Media.Status.SourceLaunchUnresolved", "无法解析该来源的安全启动方式，请浏览 EXE 或 LNK。");

        // ---- Panel ----
        table.Add("Panel.AudioFlyout.AppVolume", "应用音量");
        table.Add("Panel.AudioFlyout.Refresh", "刷新音频状态");
        table.Add("Panel.AudioFlyout.SpatialAudio", "空间音效");
        table.Add("Panel.CompactMenu.WindowTitle", "任务栏快捷菜单");
        table.Add("Panel.FullPanel.NoMedia", "暂无媒体");
        table.Add("Panel.FullPanel.LyricsSource", "歌词来源：{0}");
        table.Add("Panel.FullPanel.RepeatMode", "循环模式");
        table.Add("Panel.FullPanel.WindowTitle", "媒体完整面板");
        table.Add("Panel.Notification.NowPlaying", "正在播放");
        table.Add("Panel.Notification.WindowTitle", "曲目切换通知");
        table.Add("Panel.Performance.Memory", "内存");
        table.Add("Panel.Performance.ProcessMemory", "本程序内存");
        table.Add("Panel.QuickLaunch.Empty", "尚未添加应用");
        table.Add("Panel.QuickLaunch.Preview", "快速启动：{0}");
        table.Add("Panel.QuickLaunch.Title", "快速启动");
        table.Add("Panel.Repeat.All", "列表循环");
        table.Add("Panel.Repeat.Off", "循环关闭");
        table.Add("Panel.Repeat.One", "单曲循环");
        table.Add("Panel.Repeat.Unavailable", "循环不可用");
        table.Add("Panel.Volume.CurrentAppVolume", "当前应用音量");
        table.Add("Panel.Volume.CurrentMedia", "当前媒体");
        table.Add("Panel.Volume.Tooltip", "当前应用音量 / 音量合成器");
        table.Add("Panel.Volume.Unavailable", "不可用");

        // ---- Search ----
        table.Add("Search.About.Developers.Description", "开发人员名单，取自 GitHub 的贡献者列表");
        table.Add("Search.About.Licenses.Description", "本程序使用的开源软件包与衍生代码及其许可");
        table.Add("Search.About.ProjectInfo.Description", "仓库、反馈入口与使用帮助");
        table.Add("Search.About.Sponsors.Description", "赞助者名单，取自仓库里的名单文件");
        table.Add("Search.About.Support.Description", "微信与支付宝收款码、爱发电赞助链接");
        table.Add("Search.Application.Application.Description", "版本信息、检查更新、自动更新、开机自动启动与界面语言");
        table.Add("Search.Application.Diagnostics.Description", "打开日志文件夹（logs\\app.log，出现错误时发这个文件），或把工作集交还给系统");
        table.Add("Search.Application.SettingsFile.Description", "打开设置文件夹与重置全部设置");
        table.Add("Application.Header.Subtitle", "版本与更新、界面语言、开机自启、设置文件与诊断日志");
        table.Add("Search.Appearance.Fonts.Description", "英文字体、中文字体与字体粗细");
        table.Add("Search.Appearance.MediaBarText.Description", "媒体栏上文字的颜色与大小");
        table.Add("Search.Appearance.ThemeAndBackdrop.Description", "浅色还是深色，以及窗口背景材质");
        table.Add("Search.DisplayModes.ChooseDisplayMode.Description", "选择任务栏、灵动岛、桌面卡片或悬浮球");
        table.Add("Search.DisplayModes.FullLayer.Description", "点击媒体栏展开的面板包含哪些分区");
        table.Add("Search.DisplayModes.HoverLayer.Description", "鼠标移入媒体栏时出现的快捷控制");
        table.Add("Search.DisplayModes.IslandAppearance.Description", "灵动岛的背景样式、不透明度与圆角，当前只读");
        table.Add("Search.DisplayModes.MediaBarWidth.Description", "宽度跟随内容、固定宽度与组件间距");
        table.Add("Search.DisplayModes.RestLayer.Description", "始终显示的基础层：信息密度、内容排列、对齐、进度显示与完整层入口");
        table.Add("Search.DisplayModes.ScreenAndPlacement.Description", "媒体栏所在的显示器与任务栏位置");
        table.Add("Search.Interaction.InAppRestLayer.Description", "点在静置层上的结果：点封面、点文字、滚轮");
        table.Add("Search.Interaction.SharedModifier.Description", "媒体栏与托盘共用的组合滚轮按键");
        table.Add("Search.Interaction.TrayIcon.Description", "托盘图标的点击与滚轮行为");
        table.Add("Search.Lyrics.Alignment.Description", "歌词靠左、居中还是靠右");
        table.Add("Search.Lyrics.Display.Description", "显示歌词、显示两行、第二行显示什么、逐字擦亮与署名行过滤");
        table.Add("Search.Lyrics.Sources.Description", "选择歌词来源、它们的优先顺序与搜索匹配严格度");
        table.Add("Search.MediaAndNotifications.MediaSource.Description", "来源允许列表与已检测来源");
        table.Add("Search.MediaAndNotifications.QuickLaunch.Description", "无媒体时从音符启动播放器");
        table.Add("Search.MediaAndNotifications.RestLayerComponents.Description", "叠加在静置层右侧的频谱与性能组件");
        table.Add("Search.MediaAndNotifications.TrackChangeNotification.Description", "曲目切换并开始播放时显示当前曲目");

        // ---- Service ----
        table.Add("Service.MediaSource.Kugou", "酷狗音乐");
        table.Add("Service.MediaSource.NetEaseCloudMusic", "网易云音乐");
        table.Add("Service.MediaSource.QQMusic", "QQ音乐");
        table.Add("Service.MediaSource.Unknown", "未知来源");
        table.Add("Service.Startup.ExecutablePathUnavailable", "无法确定程序路径，无法写入启动项");
        table.Add("Service.Startup.RegistryKeyUnavailable", "无法打开启动项注册表键");

        // ---- Settings ----
        table.Add("Settings.Legacy.About", "关于 AFMediaBar");
        table.Add("Settings.Legacy.Personalization", "个性化");
        table.Add("Settings.Legacy.Theme", "主题");
        table.Add("Settings.Legacy.ThemeDark", "深色");
        table.Add("Settings.Legacy.ThemeLight", "浅色");
        table.Add("Settings.Search.Placeholder", "搜索设置");
        table.Add("Settings.Search.Suggestion.Title", "{0} › {1}");

        // ---- Shell ----
        table.Add("Shell.QuickLaunch.Status.Failed", "无法启动此应用，请检查应用是否仍可用。");
        table.Add("Shell.QuickLaunch.Status.InvalidTarget", "启动目标已失效，请在媒体与通知中重新添加。");

        // ---- Startup ----
        table.Add("Startup.SingleInstance.AlreadyRunning", "AF Media Bar 已在运行，请查看右下角的托盘图标（或点击小箭头展开隐藏图标）。");

        // ---- Update ----
        table.Add("Update.Channel.Accelerated", "加速站点 {0}");
        table.Add("Update.Channel.Direct", "GitHub 直连");
        table.Add("Update.Install.Blocked.OtherInstances", "程序还有其它实例在运行");
        table.Add("Update.Install.Blocked.Portable", "当前是便携版，无法自动安装");
        table.Add("Update.Navigation.Available", "发现新版本 v{0}");
        table.Add("Update.Navigation.Downloading", "正在下载更新 {0}%");
        table.Add("Update.Navigation.Ready", "更新已就绪（v{0}）");
        table.Add("Update.Navigation.Verifying", "正在校验更新");
        table.Add("Update.Notification.Body", "发现 v{0}（当前 v{1}）。点击打开设置，查看亮点并下载安装。");
        table.Add("Update.Notification.Title", "AF Media Bar 有新版本");
        table.Add("Update.Reason.DownloadFailed", "下载失败（网络或磁盘错误）");
        table.Add("Update.Reason.DownloadHashMismatch", "安装包校验失败（SHA-256 不匹配，收到 {0} 字节）");
        table.Add("Update.Reason.DownloadHttp", "下载失败（HTTP {0}）");
        table.Add("Update.Reason.DownloadTimeout", "下载超时");
        table.Add("Update.Reason.ManifestEmpty", "清单内容为空");
        table.Add("Update.Reason.ManifestEndpointInvalid", "清单地址无效");
        table.Add("Update.Reason.ManifestHttp", "无法访问版本清单（HTTP {0}）");
        table.Add("Update.Reason.ManifestInvalidJson", "清单不是合法 JSON");
        table.Add("Update.Reason.ManifestNetwork", "无法访问版本清单（网络错误）");
        table.Add("Update.Reason.ManifestRootNotObject", "清单根节点不是对象");
        table.Add("Update.Reason.ManifestSchemaInvalid", "清单的 schemaVersion 不是有效版本号");
        table.Add("Update.Reason.ManifestSchemaTooNew", "清单 schemaVersion {0} 高于当前程序支持的 {1}");
        table.Add("Update.Reason.ManifestUnreachable", "无法访问版本清单");
        table.Add("Update.Reason.ManifestVersionMissing", "清单缺少 version");
        table.Add("Update.Reason.ManifestVersionUnparsable", "清单的 version（{0}）无法解析");
        table.Add("Update.Reason.NoUsableSource", "所有下载地址都不可用");
        table.Add("Update.Reason.PendingRecordMissing", "已下载的安装包记录缺失");
        table.Add("Update.Reason.Unknown", "未知原因");
        table.Add("Update.Reason.VerifyHashMismatch", "已下载的安装包 SHA-256 与清单不符，已删除");
        table.Add("Update.Reason.VerifyUnreadable", "已下载的安装包无法读取，已删除");
        table.Add("Update.Relative.Days", "{0} 天前");
        table.Add("Update.Relative.Hours", "{0} 小时前");
        table.Add("Update.Relative.JustNow", "刚刚");
        table.Add("Update.Relative.Minutes", "{0} 分钟前");
        table.Add("Update.Status.Available", "发现新版本 v{0}（当前 v{1}）");
        table.Add("Update.Status.Checking", "正在检查更新…");
        table.Add("Update.Status.Downloading", "正在下载并校验安装包 {0}%");
        table.Add("Update.Status.Failed", "更新失败：{0}");
        table.Add("Update.Status.Idle", "尚未检查更新");
        table.Add("Update.Status.ManualOnly", "发现新版本 v{0}，但清单未提供可自动安装的安装包");
        table.Add("Update.Status.Ready", "更新已就绪（v{0}）· 下次启动程序时自动安装，或立即重启并安装");
        table.Add("Update.Status.ReadyBlocked", "已下载 v{0}，但{1}；可从下载页手动更新");
        table.Add("Update.Status.Skipped", "已跳过 v{0}（当前 v{1}）· 手动检查仍会显示该版本");
        table.Add("Update.Status.UpToDate", "已是最新版本（v{0}）");
        table.Add("Update.Status.Verifying", "正在校验安装包 {0}%");
        table.Add("Update.Suffix.Channel", " · {0}");
        table.Add("Update.Suffix.LastCheck", " · 上次检查 {0}");
        table.Add("Update.Suffix.Mandatory", " · 该版本必须更新");
        table.Add("Update.Tray.Available", "发现新版本 v{0}（点击查看）");
        table.Add("Update.Tray.Check", "检查更新");
        table.Add("Update.Tray.Checking", "正在检查更新…");
        table.Add("Update.Tray.Downloading", "正在下载更新 {0}%");
        table.Add("Update.Tray.Failed", "更新失败，点击重试");
        table.Add("Update.Tray.Ready", "更新已就绪（v{0}），点击重启安装");
        table.Add("Update.Tray.Verifying", "正在校验安装包 {0}%");

        // ---- Wheel ----
        table.Add("Wheel.Action.CurrentMediaVolume", "当前媒体音量");
        table.Add("Wheel.Action.MediaSource", "播放源");
        table.Add("Wheel.Hint.Chord", "{0} + 滚轮：{1}");
        table.Add("Wheel.Hint.Plain", "普通滚轮：{0}");
        table.Add("Wheel.Hint.WithValue", "{0}（当前：{1}）");
        table.Add("Wheel.Line.WithValue", "{0}：{1}");
    }
}



