namespace AFMediaBar.Classes.Services.Localization.Strings;

/// <summary>
/// 文案（越南语）。/ Vietnamese text.
///
/// 一种语言一份文件：翻译与校对只碰这一个文件，新增语言就是再增一个同构文件，并在 <c>Translations</c> 的登记列表里加一行。
/// 键必须与另外几份语言文件完全一致：缺一条时该语言会回退，所以漏翻译只能靠逐行对照各份文件发现；
/// 各份文件的键顺序也相同，因此同一行号在各份文件里指的是同一条文案。
/// Vietnamese text.
///
/// One file per language: translating and proofreading touch only this file, and adding a language means adding one more
/// file of the same shape plus a line in the registration list inside <c>Translations</c>. The keys have to match the other
/// files exactly: a missing entry falls back, so a gap is found by comparing files, and
/// because all files share one key order the same line number means the same string in every one of them.
/// </summary>
internal static class StringsVi
{
    /// <summary>登记本语言文案。/ Registers the text of this language.</summary>
    /// <param name="table">该语言的文案表。/ The text table of this language.</param>
    internal static void Register(LanguageTable table)
    {
        // ---- About ----
        table.Add("About.Header.Subtitle", "Nhà phát triển, nhà tài trợ và giấy phép nguồn mở");
        table.Add("About.Language.Description", "Ngôn ngữ hiển thị của giao diện; chọn \"Theo hệ thống\" sẽ dựa vào ngôn ngữ hiển thị của Windows, áp dụng ngay sau khi đổi");
        table.Add("About.Language.English", "English");
        table.Add("About.Language.FollowSystem", "Theo hệ thống");
        table.Add("About.Language.SimplifiedChinese", "简体中文");
        table.Add("About.Language.Title", "Ngôn ngữ giao diện");
        table.Add("About.Language.TraditionalChinese", "繁體中文");
        table.Add("About.Language.Vietnamese", "Tiếng Việt");
        table.Add("About.ResetScope", "tất cả cài đặt");
        table.Add("About.Row.AutoCheck.Description", "Đọc danh sách phiên bản công khai khoảng 20 giây sau khi khởi động; sau khi thành công sẽ không kiểm tra lại trong 24 giờ, nếu thất bại sẽ thử lại sau 1 giờ. Khi có bản mới sẽ hiện một thông báo hệ thống, nhấp vào thông báo sẽ mở trang này");
        table.Add("About.Row.AutoCheck.Title", "Tự động kiểm tra bản cập nhật");
        table.Add("About.Row.ClearDefaults.Description", "Xóa các tùy chọn mặc định đã lưu, mọi mục đặt lại sẽ quay về giá trị mặc định tích hợp sẵn của ứng dụng");
        table.Add("About.Row.ClearDefaults.Title", "Xóa cài đặt mặc định của tôi");
        table.Add("About.Row.Download.Download", "Tải về và cài đặt");
        table.Add("About.Row.DownloadPage.Description", "Khi không truy cập được GitHub, một máy chủ tăng tốc sẽ mở cùng trang tải về");
        table.Add("About.Row.DownloadPage.Mirror", "Máy chủ tăng tốc");
        table.Add("About.Row.DownloadPage.Title", "Mở trang tải về");
        table.Add("About.Row.Install.Description", "Sau khi tải về và xác minh xong, lần khởi động tiếp theo sẽ cài đặt trước khi chạy phiên bản mới; bạn cũng có thể cài đặt ngay bây giờ");
        table.Add("About.Row.Install.Now", "Khởi động lại và cài đặt ngay");
        table.Add("About.Row.Install.Title", "Cài đặt bản cập nhật");
        table.Add("About.Row.OpenFolder.Description", "Mở thư mục chứa settings.json, nơi có thể sao lưu hoặc thay thế trực tiếp");
        table.Add("About.Row.OpenFolder.Title", "Mở thư mục cài đặt");
        table.Add("About.Row.LogFolder.Description", "Nhật ký là một tệp duy nhất, logs\\app.log, lưu giữ 1000 dòng mới nhất; hãy gửi tệp này khi ứng dụng gặp sự cố");
        table.Add("About.Row.LogFolder.Title", "Tệp nhật ký");
        table.Add("About.Row.TrimMemory.Button", "Nén ngay");
        table.Add("About.Row.TrimMemory.Description", "Trả lại tập làm việc (bộ nhớ vật lý đang dùng) cho hệ thống: con số trong Task Manager sẽ giảm ngay lập tức, lần sử dụng tiếp theo sẽ đọc lại phần đó và có thể khựng nhẹ; kích thước đã cam kết không đổi");
        table.Add("About.Row.TrimMemory.Title", "Nén dung lượng bộ nhớ");
        table.Add("Common.Group.Developers", "Nhà phát triển");
        table.Add("Common.Group.Diagnostics", "Chẩn đoán và nhật ký");
        table.Add("About.Row.Portable.Badge", "Di động");
        table.Add("About.Row.Portable.Description", "Đây không phải bản cài đặt nên không thể tự động thay thế tệp; hãy lấy bản cài đặt từ trang tải về hoặc tự thay thế tệp thủ công");
        table.Add("About.Row.Portable.Title", "Không hỗ trợ cập nhật tự động");
        table.Add("About.Row.Progress.Title", "Tiến độ tải về");
        table.Add("About.Row.Project.Description", "Trải nghiệm phương tiện trên thanh tác vụ Windows · phiên bản 1.0.0");
        table.Add("About.Row.Project.Issues", "Báo cáo sự cố");
        table.Add("About.Row.Project.Star", "Tặng sao trên GitHub");
        table.Add("About.Row.ResetAll.Button", "Đặt lại tất cả");
        table.Add("About.Row.ResetAll.Description", "Khôi phục chế độ hiển thị, tương tác, lời bài hát, giao diện và thông báo phương tiện về mặc định");
        table.Add("About.Row.ResetAll.Title", "Đặt lại mọi cài đặt");
        table.Add("About.Row.SaveDefaults.NotSaved", "Chưa lưu: mọi mục \"khôi phục mặc định của trang này\" sẽ quay về cài đặt mặc định gốc");
        table.Add("About.Row.SaveDefaults.Saved", "Đã lưu: mọi mục \"khôi phục mặc định của trang này\" sẽ quay về bản chụp này");
        table.Add("About.Row.SaveDefaults.Title", "Lưu cài đặt hiện tại làm mặc định");
        table.Add("About.Row.Skip.Clear", "Hủy bỏ bỏ qua");
        table.Add("About.Row.Skip.Description", "Bỏ qua chỉ ảnh hưởng tới thông báo tự động; kiểm tra thủ công vẫn sẽ báo phiên bản đó");
        table.Add("About.Licenses.Open", "Mở dự án");
        table.Add("About.Support.Afdian", "Afdian");
        table.Add("About.Support.Alipay", "Alipay");
        table.Add("About.Support.Open", "Mở liên kết");
        table.Add("About.Support.Pending", "Mã thanh toán và liên kết ủng hộ do tác giả cung cấp sau; đường dẫn ở trên là nơi lưu trữ tệp");
        table.Add("About.Support.SponsorNote", "Khoản tài trợ trên 10 Nhân dân tệ có thể được ghi danh vào danh sách tài trợ; vui lòng để lại ID của bạn trong ghi chú thanh toán");
        table.Add("About.Support.WeChat", "WeChat");
        table.Add("Credits.Contributions", "{0} đóng góp");
        table.Add("Credits.Reason.ContributorsEmpty", "Danh sách người đóng góp trống");
        table.Add("Credits.Reason.ContributorsShape", "Danh sách người đóng góp có định dạng không mong muốn");
        table.Add("Credits.Reason.Empty", "Danh sách trống");
        table.Add("Credits.Reason.InvalidJson", "Danh sách không phải là JSON hợp lệ");
        table.Add("Credits.Reason.SchemaTooNew", "Danh sách tài trợ có phiên bản schema {0}, mới hơn phiên bản hỗ trợ {1}");
        table.Add("Credits.Reason.SponsorsShape", "Danh sách tài trợ có cấu trúc không mong muốn");
        table.Add("Credits.Sponsors.Count", "Tổng cộng {0} nhà tài trợ");
        table.Add("Credits.Sponsors.None", "Chưa có nhà tài trợ nào. Nếu danh sách không xuất hiện, nhấn Thử lại, hoặc thêm mục vào docs/sponsors.json trong kho lưu trữ");
        table.Add("Credits.SponsorSeparator", ", ");
        table.Add("Credits.Status.Failed", "Hiện không thể tải danh sách: {0}");
        table.Add("Credits.Status.Partial", "Hiện không thể tải một phần danh sách: {0}");
        table.Add("Credits.Status.PartialCached", "Lần trước chỉ lấy được một phần danh sách");
        table.Add("Credits.Status.Loading", "Đang tải danh sách nhà phát triển và nhà tài trợ…");
        table.Add("Credits.Retry", "Thử lại");
        table.Add("About.Row.Startup.Description", "Khởi chạy AF Media Bar sau khi bạn đăng nhập vào Windows (chỉ ghi vào mục khởi động của người dùng hiện tại)");
        table.Add("About.Row.Startup.Title", "Khởi động cùng hệ thống");
        table.Add("About.Row.Version.Check", "Kiểm tra bản cập nhật");
        table.Add("About.Row.Version.Description", "Phiên bản hiện đang cài đặt và phiên bản mới nhất trong danh mục công khai");
        table.Add("About.Row.Version.Title", "Phiên bản");
        table.Add("About.Status.ClearDefaultsFailed", "Không thể xóa cài đặt mặc định: {0}");
        table.Add("About.Status.SaveDefaultsFailed", "Không thể lưu cài đặt mặc định: {0}");
        table.Add("About.Status.StartupFailed", "Không thể thay đổi mục khởi động: {0}");

        // ---- Appearance ----
        table.Add("Appearance.Accent.Custom", "Tùy chỉnh");
        table.Add("Appearance.Accent.FollowSystem", "Theo hệ thống");
        table.Add("Appearance.Accent.HexLabel", "Giá trị");
        table.Add("Appearance.Accent.Hint", "Màu chủ đạo được áp dụng ở mọi nơi có màu nhấn: trạng thái chọn và nút gạt trong cài đặt, thanh trượt, cả hai thanh tiến trình, vùng sáng trên thanh tác vụ và flyout, cũng như phần nhấn của bảng điều khiển đầy đủ. Chọn Tùy chỉnh chỉ tác động lên ứng dụng này; cài đặt cá nhân hóa của Windows không bị thay đổi. Độ tương phản cao vẫn sử dụng màu nhấn của hệ thống.");
        table.Add("Appearance.Accent.PaletteLabel", "Chọn màu chủ đạo");
        table.Add("Appearance.Backdrop.Acrylic", "Acrylic");
        table.Add("Appearance.Backdrop.Mica", "Mica");
        table.Add("Appearance.Backdrop.MicaAlt", "Mica Alt");
        table.Add("Appearance.Backdrop.Solid", "Đơn sắc (Solid)");
        table.Add("Appearance.BackdropTint.Hint", "Chỉ áp dụng ở nơi ứng dụng tự vẽ chất liệu: các cửa sổ trên Windows 10 và thông báo bài hát (thông báo không bao giờ nhận tiêu điểm, trong khi chất liệu hệ thống cần cửa sổ tiền cảnh, vì thế hiệu ứng mờ do ứng dụng tự vẽ). Mica và Acrylic trên Windows 11 do hệ thống vẽ và sẽ bỏ qua giá trị này. Giá trị thấp hơn sẽ trong suốt hơn; giá trị rất cao sẽ tiệm cận bề mặt đặc.");
        table.Add("Appearance.CjkFont.FollowSystem", "Theo hệ thống");
        table.Add("Appearance.LatinFont.FollowSystem", "Theo hệ thống");
        table.Add("Appearance.Header.Subtitle", "Phông chữ, chủ đề, chất liệu nền cửa sổ và chữ trên thanh phương tiện");
        table.Add("Appearance.Motion.Detail.Full", "Giữ nguyên hiệu ứng mở rộng, phản hồi và chuyển đổi phổ sóng");
        table.Add("Appearance.Motion.Detail.Instant", "Tuân theo cài đặt hệ thống để tránh độ trễ chuyển tiếp");
        table.Add("Appearance.Motion.Detail.Reduced", "Tắt hiệu ứng mờ, chữ chạy marquee và phổ sóng liên tục");
        table.Add("Appearance.Motion.Mode.Full", "Hiệu ứng đầy đủ");
        table.Add("Appearance.Motion.Mode.Instant", "Cập nhật tức thì");
        table.Add("Appearance.Motion.Mode.Reduced", "Giảm chuyển động");
        table.Add("Appearance.Preview.DarkWallpaper", "Hình nền tối");
        table.Add("Appearance.Preview.Hint", "Kết quả tự động phụ thuộc vào màu sắc thực tế phía sau thanh tác vụ nên cả hai bản xem trước mang tính tham khảo; các chế độ ép buộc sẽ dùng cùng một màu chữ trên cả hai.");
        table.Add("Appearance.Preview.LightWallpaper", "Hình nền sáng");
        table.Add("Appearance.Row.Accent.Description", "Mặc định theo hệ thống; màu chủ đạo tùy chỉnh chỉ ảnh hưởng ứng dụng này");
        table.Add("Appearance.Row.Accent.Title", "Màu chủ đạo (Accent color)");
        table.Add("Appearance.Row.Backdrop.Description", "Đặt chất liệu nền cho cửa sổ cài đặt, pop-up khay hệ thống và menu ngữ cảnh");
        table.Add("Appearance.Row.Backdrop.Title", "Chất liệu nền cửa sổ");
        table.Add("Appearance.Row.BackdropTint.Description", "Độ đậm chất liệu khi ứng dụng tự vẽ (30%-100%)");
        table.Add("Appearance.Row.BackdropTint.Title", "Độ đậm chất liệu");
        table.Add("Appearance.Row.CjkFont.Description", "Phông chữ dùng cho ký tự chữ Hán / CJK");
        table.Add("Appearance.Row.CjkFont.Title", "Phông chữ CJK");
        table.Add("Appearance.Row.FontWeight.Description", "Độ đậm phông chữ dùng chung cho cửa sổ cài đặt, thanh tác vụ và thông báo");
        table.Add("Appearance.Row.FontWeight.Title", "Độ đậm phông chữ");
        table.Add("Appearance.Row.LatinFont.Description", "Phông chữ dùng cho chữ cái Latin và chữ số");
        table.Add("Appearance.Row.LatinFont.Title", "Phông chữ Latin");
        table.Add("Appearance.Row.MediaFontSize.Description", "Thu phóng cỡ chữ tiêu đề, nghệ sĩ và lời bài hát ở lớp nghỉ theo tỷ lệ phần trăm (80%–125%)");
        table.Add("Appearance.Row.MediaFontSize.Title", "Cỡ chữ phương tiện");
        table.Add("Appearance.Row.Motion.Title", "Hiệu ứng chuyển động tương tác");
        table.Add("Appearance.Row.TextColor.Description", "Chế độ tự động chọn màu sáng hoặc tối dựa trên màu sắc thực tế phía sau chữ");
        table.Add("Appearance.Row.TextColor.Title", "Màu chữ");
        table.Add("Appearance.Row.Theme.Description", "Tự động theo cài đặt giao diện sáng/tối của Windows");
        table.Add("Appearance.Row.Theme.Title", "Chủ đề ứng dụng");
        table.Add("Appearance.Specimen.Label", "Xem trước phông chữ");
        table.Add("Appearance.TextColor.Automatic", "Tự động (theo nền)");
        table.Add("Appearance.TextColor.DarkText", "Luôn dùng chữ tối");
        table.Add("Appearance.TextColor.LightText", "Luôn dùng chữ sáng");
        table.Add("Appearance.Theme.Automatic", "Tự động (theo hệ thống)");
        table.Add("Appearance.Theme.Dark", "Tối (Dark)");
        table.Add("Appearance.Theme.Light", "Sáng (Light)");

        // ---- Audio ----
        table.Add("Audio.Application.SystemSounds", "Âm thanh hệ thống");
        table.Add("Audio.Error.CreateDeviceEnumerator", "Không thể tạo bộ liệt kê thiết bị âm thanh Windows.");
        table.Add("Audio.Error.CreatePolicyConfig", "Không thể tạo dịch vụ chính sách âm thanh Windows.");
        table.Add("Audio.OutputDevice.Unavailable", "Thiết bị phát: không khả dụng");
        table.Add("Audio.OutputDevice.Unchanged", "Thiết bị phát: không đổi");
        table.Add("Audio.OutputDevice.Value", "Thiết bị phát: {0}");
        table.Add("Audio.Spatial.Enabled", "Đã bật");
        table.Add("Audio.Spatial.NoDevice", "Không có thiết bị phát");
        table.Add("Audio.Spatial.Off", "Tắt");
        table.Add("Audio.Spatial.Unavailable", "Trạng thái không khả dụng");
        table.Add("Audio.Spatial.Unsupported", "Thiết bị này không hỗ trợ");
        table.Add("Audio.Status.AdjustApplicationVolumeFailed", "Điều chỉnh âm lượng của {0} thất bại: {1}");
        table.Add("Audio.Status.NoSessions", "Không có phiên âm thanh ứng dụng nào");
        table.Add("Audio.Status.OpenSoundSettingsFailed", "Mở cài đặt âm thanh Windows thất bại: {0}");
        table.Add("Audio.Status.ReadFailed", "Đọc trạng thái âm thanh thất bại: {0}");
        table.Add("Audio.Status.SwitchOutputDeviceFailed", "Chuyển thiết bị phát thất bại: {0}");
        table.Add("Audio.Tooltip.AdjustVolumeFailed", "Điều chỉnh âm lượng thất bại");
        table.Add("Audio.Tooltip.SwitchOutputDeviceFailed", "Chuyển thiết bị phát thất bại");
        table.Add("Audio.Tooltip.WheelDisabled", "Con lăn khay hệ thống đã tắt");
        table.Add("Audio.Volume.CurrentValue", "{0} {1}%");
        table.Add("Audio.Volume.Unavailable", "Âm lượng phương tiện hiện tại: không khả dụng");
        table.Add("Audio.Volume.Unchanged", "Âm lượng phương tiện hiện tại: không đổi");
        table.Add("Audio.Volume.Value", "{0}: {1}%");

        // ---- Common ----
        table.Add("Common.ActivateSourceApplication", "Mở ứng dụng đang phát");
        table.Add("Common.AdjustCurrentMediaVolume", "Điều chỉnh âm lượng phương tiện hiện tại");
        table.Add("Common.AlignCenter", "Căn giữa");
        table.Add("Common.AlignLeft", "Căn trái");
        table.Add("Common.AlignRight", "Căn phải");
        table.Add("Common.AudioControl", "Điều khiển âm thanh");
        table.Add("Common.Cancel", "Hủy");
        table.Add("Common.Clear", "Xóa");
        table.Add("Common.DynamicIsland", "Đảo động (Dynamic island)");
        table.Add("Common.Exit", "Thoát");
        table.Add("Common.FullLayer", "Bảng điều khiển đầy đủ");
        table.Add("Common.Group.Application", "Ứng dụng");
        table.Add("Common.Group.ChooseDisplayMode", "Chọn chế độ hiển thị");
        table.Add("Common.Group.Fonts", "Phông chữ");
        table.Add("Common.Group.InAppRestLayer", "Trong ứng dụng (lớp nghỉ)");
        table.Add("Common.Group.IslandAppearance", "Giao diện đảo động");
        table.Add("Common.Group.Licenses", "Giấy phép nguồn mở");
        table.Add("Common.Group.LyricsAlignment", "Căn lề");
        table.Add("Common.Group.LyricsDisplay", "Hiển thị");
        table.Add("Common.Group.LyricsSources", "Nguồn lời bài hát");
        table.Add("Common.Group.MediaBarText", "Chữ trên thanh phương tiện");
        table.Add("Common.Group.MediaBarWidth", "Độ rộng thanh phương tiện");
        table.Add("Common.Group.ProjectInfo", "Thông tin dự án");
        table.Add("Common.Group.QuickLaunch", "Khởi động nhanh");
        table.Add("Common.Group.RestLayerComponents", "Thành phần lớp nghỉ");
        table.Add("Common.Group.ScreenAndPlacement", "Màn hình và vị trí");
        table.Add("Common.Group.SettingsFile", "Tệp cài đặt");
        table.Add("Common.Group.SharedModifier", "Phím bổ trợ dùng chung");
        table.Add("Common.Group.Sponsors", "Nhà tài trợ");
        table.Add("Common.Group.Support", "Ủng hộ tác giả");
        table.Add("Common.Group.ThemeAndBackdrop", "Chủ đề và chất liệu nền");
        table.Add("Common.Group.TrackChangeNotification", "Thông báo đổi bài");
        table.Add("Common.HoverLayer", "Lớp rê chuột (Hover layer)");
        table.Add("Common.MediaSource", "Nguồn phương tiện");
        table.Add("Common.Modifier.LeftMouseButton", "Nút chuột trái");
        table.Add("Common.Modifier.RightMouseButton", "Nút chuột phải");
        table.Add("Common.Modifier.Shift", "Phím Shift");
        table.Add("Common.Monitor.PrimarySuffix", " (Chính)");
        table.Add("Common.NextTrack", "Bài tiếp");
        table.Add("Common.NotBound", "Chưa gán");
        table.Add("Common.NotImplemented", "Chưa phát triển");
        table.Add("Common.OpenFolder", "Mở thư mục");
        table.Add("Common.OpenFullPanel", "Mở bảng điều khiển đầy đủ");
        table.Add("Common.OutputDevice", "Thiết bị phát");
        table.Add("Common.Page.About", "Giới thiệu");
        table.Add("Common.Page.Application", "Ứng dụng");
        table.Add("Common.Page.Appearance", "Giao diện");
        table.Add("Common.Page.DisplayModes", "Chế độ hiển thị");
        table.Add("Common.Page.Interaction", "Tương tác");
        table.Add("Common.Page.Lyrics", "Lời bài hát");
        table.Add("Common.Page.MediaAndNotifications", "Phương tiện và thông báo");
        table.Add("Common.PlayPause", "Phát / tạm dừng");
        table.Add("Common.PreviousNextTrack", "Bài trước / bài tiếp");
        table.Add("Common.PreviousTrack", "Bài trước");
        table.Add("Common.ReconnectSmtc", "Kết nối lại SMTC");
        table.Add("Common.ReloadTaskbarHost", "Tải lại thanh phương tiện trên Taskbar");
        table.Add("Common.ResetDialog.Confirm", "Khôi phục");
        table.Add("Common.ResetDialog.Content", "Mọi tùy chọn bên trong \"{0}\" sẽ được đặt lại; các trang khác và quá trình phát hiện tại không bị ảnh hưởng.");
        table.Add("Common.ResetDialog.Title", "Khôi phục mặc định");
        table.Add("Common.ResetPageDefaults", "Khôi phục mặc định trang này");
        table.Add("Common.ResetPosition", "Đặt lại vị trí");
        table.Add("Common.RestLayer", "Lớp nghỉ (Rest layer)");
        table.Add("Common.Save", "Lưu");
        table.Add("Common.Settings", "Cài đặt");
        table.Add("Common.SkipVersion", "Bỏ qua phiên bản này");
        table.Add("Common.SwitchMediaSource", "Chuyển nguồn phương tiện");
        table.Add("Common.SwitchOutputDevice", "Chuyển thiết bị phát");
        table.Add("Common.SwitchPlayer", "Chuyển trình phát");
        table.Add("Common.TargetMonitor", "Màn hình mục tiêu");
        table.Add("Common.TrayIcon", "Biểu tượng khay hệ thống");

        // ---- Diagram ----
        table.Add("Diagram.DynamicIslandSurface.Caption", "Chế độ đảo động chưa được phát triển, do đó ba tùy chọn dưới đây là chỉ đọc; giao diện của nó và thanh tác vụ không ảnh hưởng lẫn nhau.");
        table.Add("Diagram.InputGestures.Caption", "Đây là hai khu vực có thể nhấp chuột duy nhất trên thanh phương tiện và mỗi khu vực được đặt độc lập; các nút trong bảng mở rộng không bị ảnh hưởng.");
        table.Add("Diagram.InputGestures.Label.ArtworkClick", "Nhấp vào ảnh bìa");
        table.Add("Diagram.InputGestures.Label.TextClick", "Nhấp vào tiêu đề hoặc lời");
        table.Add("Diagram.LayerFull.Caption", "Bảng mở rộng từ thanh phương tiện có bốn phần; mỗi phần có thể tắt riêng, nhưng ít nhất một phần phải luôn bật.");
        table.Add("Diagram.LayerFull.Label.MediaInfo", "Thông tin bài hát");
        table.Add("Diagram.LayerFull.Label.Performance", "Hiệu năng");
        table.Add("Diagram.LayerFull.Label.Playback", "Điều khiển phát");
        table.Add("Diagram.LayerHover.Caption", "Rê chuột sẽ hiển thị các nút phát, chuyển nguồn, thiết bị phát, âm lượng và tiến trình, mỗi nút có công tắc riêng ở trang tiếp theo.");
        table.Add("Diagram.LayerRest.Caption", "Ảnh bìa và tiêu đề luôn được hiển thị; các thành phần phổ sóng và hiệu năng nằm ở bên phải và được bật/tắt trong \"Phương tiện và thông báo → Thành phần lớp nghỉ\".");
        table.Add("Diagram.LyricsAlignment.Caption", "Tùy chọn này chỉ quyết định lề hiển thị của lời bài hát; căn lề tiêu đề và nghệ sĩ là cài đặt riêng trong trang \"Chế độ hiển thị\".");
        table.Add("Diagram.LyricsTwoLine.Caption", "Dòng thứ nhất là câu hiện tại; dòng thứ hai là câu tiếp theo hoặc bản dịch và sẽ ẩn đi khi lớp nghỉ không còn đủ chỗ.");
        table.Add("Diagram.LyricsTwoLine.Label.FirstLine", "Dòng thứ nhất");
        table.Add("Diagram.LyricsTwoLine.Label.SecondLine", "Dòng thứ hai");
        table.Add("Diagram.NotificationPlacement.Caption", "Có sáu vị trí khả dụng và ô nổi bật là vị trí hiện tại; chuyển màn hình chỉ thay đổi nơi thông báo xuất hiện.");
        table.Add("Diagram.NotificationPlacement.Label.AvoidTaskbar", "Các vị trí dưới đáy tự động tránh thanh tác vụ");
        table.Add("Diagram.NotificationPlacement.Label.InsideMonitor", "Thông báo xuất hiện bên trong màn hình đã chọn");
        table.Add("Diagram.Spectrum.Caption", "Hình minh họa hiển thị 9 cột phổ sóng với cột ngoài cùng bên phải tắt; tốc độ làm mới quyết định phản ứng nhanh chậm và độ nhạy quyết định chiều cao cột sóng ở mức âm lượng nhất định.");
        table.Add("Diagram.TaskbarLength.Caption", "Độ rộng tự động theo nội dung; khi tắt tính năng này sẽ áp dụng độ rộng cố định, và phạm vi được giới hạn bởi thanh tác vụ hiện tại.");
        table.Add("Diagram.TaskbarLength.Label.MinimumWidth", "Độ rộng tối thiểu cần thiết");
        table.Add("Diagram.TaskbarLength.Label.TaskbarLimit", "Giới hạn an toàn thanh tác vụ");
        table.Add("Diagram.TaskbarPlacement.Caption", "Thanh phương tiện tự động tránh các biểu tượng thanh tác vụ; độ lệch mép điều chỉnh khoảng cách giữa nó và khu vực biểu tượng.");
        table.Add("Diagram.TaskbarPlacement.Label.EdgeOffset", "Độ lệch mép −20 ~ +20 px");
        table.Add("Diagram.TaskbarPlacement.Label.TaskbarIcons", "Biểu tượng thanh tác vụ");
        table.Add("Diagram.TrayOverflow.Caption", "Ô nổi bật là ứng dụng này; mặc định nằm trong khu vực biểu tượng ẩn và cần kéo ra ngoài trong cài đặt thanh tác vụ Windows để nhấp chuột và lăn con trỏ hoạt động trực tiếp.");
        table.Add("Diagram.TrayOverflow.Label.OverflowArrow", "Thu gọn trong mũi tên ẩn");
        table.Add("Diagram.TrayOverflow.Label.TrayArea", "Khu vực khay hệ thống");
        table.Add("Diagram.WheelGestures.Caption", "Lăn lên và xuống không có ý nghĩa cố định mà do hành động gán quyết định. Chuyển thiết bị sẽ hiển thị danh sách ứng viên trước và áp dụng sau khoảng 1,2 giây ngừng cuộn.");
        table.Add("Diagram.WheelGestures.Label.MediaBar", "Trên thanh phương tiện");
        table.Add("Diagram.WheelGestures.Label.MediaBarResults", "Có thể gán cả 4 tác vụ: bài trước/tiếp, thiết bị hoặc trình phát, âm lượng");
        table.Add("Diagram.WheelGestures.Label.TrayResults", "Chỉ chuyển thiết bị và âm lượng");

        // ---- DisplayModes ----
        table.Add("DisplayModes.Full.Expander.Description", "Chọn các phần hiển thị trong bảng điều khiển; ít nhất một phần phải luôn bật");
        table.Add("DisplayModes.Full.Expander.Title", "Nội dung bảng điều khiển đầy đủ");
        table.Add("DisplayModes.Full.Group.Description", "Bảng điều khiển đầy đủ mở rộng từ thanh phương tiện");
        table.Add("DisplayModes.Full.Preset.Compact", "Gọn gàng");
        table.Add("DisplayModes.Full.Preset.Custom", "Tùy chỉnh");
        table.Add("DisplayModes.Full.Preset.Full", "Đầy đủ");
        table.Add("DisplayModes.Full.Row.Enable.Description", "Mở rộng bảng điều khiển đầy đủ khi nhấp vào thanh phương tiện");
        table.Add("DisplayModes.Full.Row.Enable.Title", "Bật bảng điều khiển đầy đủ");
        table.Add("DisplayModes.Full.Row.MediaControls.Title", "Nút điều khiển phát");
        table.Add("DisplayModes.Full.Row.MediaInfo.Title", "Thông tin bài hát");
        table.Add("DisplayModes.Full.Row.Performance.Title", "Thông tin hiệu năng");
        table.Add("DisplayModes.Full.Row.Preset.Description", "Áp dụng sẵn tập hợp hiển thị các phần chỉ trong một bước");
        table.Add("DisplayModes.Full.Row.Preset.Title", "Áp dụng cấu hình mẫu");
        table.Add("DisplayModes.Header.Subtitle", "Vị trí đặt thanh phương tiện, độ rộng và ba trạng thái hiển thị");
        table.Add("DisplayModes.Hover.Expander.Description", "Chọn các nút điều khiển xuất hiện khi rê chuột");
        table.Add("DisplayModes.Hover.Expander.Title", "Nút điều khiển lớp rê chuột");
        table.Add("DisplayModes.Hover.Group.Description", "Các nút điều khiển nhanh xuất hiện khi con trỏ di vào thanh phương tiện");
        table.Add("DisplayModes.Hover.Row.Enable.Description", "Hiển thị các nút điều khiển nhanh khi con trỏ đi vào thanh phương tiện");
        table.Add("DisplayModes.Hover.Row.Enable.Title", "Bật lớp rê chuột (Hover layer)");
        table.Add("DisplayModes.Hover.Row.Progress.Title", "Thanh tiến trình");
        table.Add("DisplayModes.Island.Group.Description", "Giao diện riêng của đảo động, độc lập với thanh tác vụ");
        table.Add("DisplayModes.Island.Notice", "Chế độ đảo động hiện chưa được phát triển, do đó các tùy chọn dưới đây hiện là chỉ đọc và thay đổi sẽ không ảnh hưởng tới thanh phương tiện đang chạy.");
        table.Add("DisplayModes.Island.Row.Corner.Description", "0–24 DIP");
        table.Add("DisplayModes.Island.Row.Corner.Title", "Bán kính bo góc");
        table.Add("DisplayModes.Island.Row.Opacity.Description", "Giá trị càng cao độ mờ đục càng lớn");
        table.Add("DisplayModes.Island.Row.Opacity.Title", "Độ mờ đục nền");
        table.Add("DisplayModes.Island.Row.Surface.Description", "Kiểu nền riêng của đảo động");
        table.Add("DisplayModes.Island.Row.Surface.Title", "Kiểu nền");
        table.Add("DisplayModes.Island.Surface.Automatic", "Tự động");
        table.Add("DisplayModes.Island.Surface.Solid", "Màu đơn sắc");
        table.Add("DisplayModes.Island.Surface.ThemeTint", "Màu sắc theo chủ đề");
        table.Add("DisplayModes.Mode.Current", "Chế độ hiện tại");
        table.Add("DisplayModes.Mode.DesktopCard", "Thẻ màn hình nền");
        table.Add("DisplayModes.Mode.DesktopCard.Caption", "Đặt các thẻ phương tiện có thể tự do sắp xếp trên màn hình nền");
        table.Add("DisplayModes.Mode.DynamicIsland.Caption", "Hiển thị trạng thái phát dưới dạng lớp phủ ở cạnh màn hình");
        table.Add("DisplayModes.Mode.FloatingBall", "Bóng nổi");
        table.Add("DisplayModes.Mode.FloatingBall.Caption", "Mở rộng bảng điều khiển từ một điểm nổi nhỏ gọn");
        table.Add("DisplayModes.Mode.PreviewNotice", "Chế độ đang chạy luôn là thanh tác vụ. Chọn chế độ khác chỉ thay đổi nội dung trang này; không chuyển đổi cửa sổ đang hoạt động.");
        table.Add("DisplayModes.Mode.Taskbar", "Thanh tác vụ (Taskbar)");
        table.Add("DisplayModes.Mode.Taskbar.Caption", "Chạy trên thanh tác vụ Windows, cung cấp lớp nghỉ, lớp rê chuột và bảng điều khiển đầy đủ");
        table.Add("DisplayModes.Monitor.DisconnectedSuffix", " (chưa kết nối)");
        table.Add("DisplayModes.Placement.Group.Description", "Màn hình hiển thị thanh phương tiện và vị trí của nó trên thanh tác vụ");
        table.Add("DisplayModes.Placement.Orientation.Auto", "Tự động (theo thanh tác vụ)");
        table.Add("DisplayModes.Placement.Orientation.Horizontal", "Bắt buộc nằm ngang");
        table.Add("DisplayModes.Placement.Orientation.Vertical", "Bắt buộc nằm dọc");
        table.Add("DisplayModes.Placement.ResetAction", "Đặt lại");
        table.Add("DisplayModes.Placement.Row.AvoidIcons.Description", "Tự động tránh khu vực biểu tượng thanh tác vụ để không bị che khuất");
        table.Add("DisplayModes.Placement.Row.AvoidIcons.Title", "Tránh biểu tượng thanh tác vụ");
        table.Add("DisplayModes.Placement.Row.Lock.Description", "Khóa cố định không cho phép kéo vị trí");
        table.Add("DisplayModes.Placement.Row.Lock.Title", "Khóa vị trí");
        table.Add("DisplayModes.Placement.Row.Monitor.Description", "Chọn một hoặc nhiều màn hình; ít nhất một màn hình mục tiêu phải được chọn");
        table.Add("DisplayModes.Placement.Row.Offset.Description", "Tinh chỉnh khoảng cách giữa thanh phương tiện và vùng biểu tượng theo trục vuông góc");
        table.Add("DisplayModes.Placement.Row.Offset.Title", "Độ lệch mép");
        table.Add("DisplayModes.Placement.Row.Orientation.Description", "Tự động theo hướng thanh tác vụ hoặc ép buộc nằm ngang/dọc");
        table.Add("DisplayModes.Placement.Row.Orientation.Title", "Chiều hướng");
        table.Add("DisplayModes.Placement.Row.Reset.Description", "Quay lại vị trí do thuật toán tự động tránh tính toán");
        table.Add("DisplayModes.Rest.Component.Artwork", "Ảnh bìa");
        table.Add("DisplayModes.Rest.Component.Artwork.Description", "Ảnh bìa của bài hát đang phát; khi không có phương tiện sẽ là nốt nhạc, nhấp hoặc lăn chuột để chọn trình phát");
        table.Add("DisplayModes.Rest.Component.MediaText", "Văn bản bài hát");
        table.Add("DisplayModes.Rest.Component.MediaText.Description", "Tiêu đề và nghệ sĩ; được thay thế bằng hai dòng lời bài hát khi có lời");
        table.Add("DisplayModes.Rest.Component.OutputDevice", "Nút thiết bị phát");
        table.Add("DisplayModes.Rest.Component.OutputDevice.Description", "Nhấp chuột mở menu thiết bị phát và lăn chuột để chuyển nhanh thiết bị");
        table.Add("DisplayModes.Rest.Component.Performance", "Theo dõi hiệu năng");
        table.Add("DisplayModes.Rest.Component.Performance.Description", "Luân phiên hiển thị bộ nhớ, bộ vi xử lý và các chỉ số khác theo chu kỳ lấy mẫu");
        table.Add("DisplayModes.Rest.Component.QuickLaunchNote", "Nốt nhạc khởi động nhanh");
        table.Add("DisplayModes.Rest.Component.QuickLaunchNote.Description", "Nốt nhạc hiển thị khi không có nhạc; nhấp hoặc lăn chuột trên đó để chọn trình phát");
        table.Add("DisplayModes.Rest.Component.Spectrum", "Phổ sóng (Spectrum)");
        table.Add("DisplayModes.Rest.Component.Spectrum.Description", "Phổ sóng thời gian thực của thiết bị phát hiện tại; phản hồi theo mọi âm thanh phát ra");
        table.Add("DisplayModes.Rest.Component.Volume", "Nút âm lượng");
        table.Add("DisplayModes.Rest.Component.Volume.Description", "Nhấp chuột mở menu âm lượng và lăn chuột để điều chỉnh âm lượng nguồn phát hiện tại");
        table.Add("DisplayModes.Rest.ContentLayout.AdaptiveStack", "Xếp chồng thích ứng");
        table.Add("DisplayModes.Rest.ContentLayout.CompactInline", "Thẳng hàng thu gọn");
        table.Add("DisplayModes.Rest.Density.Balanced", "Cân bằng");
        table.Add("DisplayModes.Rest.Density.Information", "Ưu tiên thông tin");
        table.Add("DisplayModes.Rest.Density.Minimal", "Tối giản");
        table.Add("DisplayModes.Rest.Group.Description", "Lớp nền luôn hiển thị mang ảnh bìa, tiêu đề và lời bài hát");
        table.Add("DisplayModes.Rest.Group.Status", "Luôn bật");
        table.Add("DisplayModes.Rest.Idle.Expander.Description", "Các thành phần vẫn hiển thị trên thanh phương tiện khi không có nguồn phát; nếu bỏ chọn tất cả thanh sẽ ẩn hoàn toàn");
        table.Add("DisplayModes.Rest.Idle.Expander.Title", "Hiển thị khi không có phương tiện");
        table.Add("DisplayModes.Rest.Idle.Notice", "Ảnh bìa và văn bản bài hát không được liệt kê ở đây: khi không có nhạc chúng không có gì để hiện và luôn ẩn. Chỉ để lại nốt nhạc vẫn cho phép chọn trình phát bằng cách lăn con trỏ.");
        table.Add("DisplayModes.Rest.Notice", "Các thành phần phổ sóng và hiệu năng được bật/tắt và điều chỉnh trong mục \"Phương tiện và thông báo → Thành phần lớp nghỉ\"; cỡ chữ bài hát nằm trong \"Giao diện → Chữ trên thanh phương tiện\". Phổ sóng thu lại tất cả âm thanh từ thiết bị phát hiện tại.");
        table.Add("DisplayModes.Rest.Order.Expander.Description", "Thứ tự sắp xếp từ trái sang phải trong thanh; ảnh bìa và văn bản bài hát được ghim ở đầu, bốn thành phần còn lại có thể dịch chuyển lên xuống");
        table.Add("DisplayModes.Rest.Order.Expander.Title", "Thứ tự thành phần lớp nghỉ");
        table.Add("DisplayModes.Rest.Order.Notice", "Ảnh bìa và văn bản bài hát được cố định ở đầu thanh và không tham gia sắp xếp (hai hàng này không có nút di chuyển).");
        table.Add("DisplayModes.Rest.Order.Reset.Description", "Phổ sóng, theo dõi hiệu năng, nút thiết bị phát, nút âm lượng");
        table.Add("DisplayModes.Rest.Order.Reset.Title", "Khôi phục thứ tự mặc định");
        table.Add("DisplayModes.Rest.Row.Alignment.Description", "Cách căn lề văn bản bài hát bên trong thanh phương tiện");
        table.Add("DisplayModes.Rest.Row.Alignment.Title", "Căn lề tiêu đề và nghệ sĩ");
        table.Add("DisplayModes.Rest.Row.Density.Description", "Điều chỉnh khoảng cách giữa các nút bấm và thanh tiến trình trong lớp nghỉ");
        table.Add("DisplayModes.Rest.Row.Density.Title", "Khoảng cách lớp nghỉ");
        table.Add("DisplayModes.Rest.Row.DeviceButton.Description", "Nhấp chuột mở menu thiết bị phát và lăn chuột để chuyển thiết bị; giữ nút này sẽ chiếm bớt không gian chữ bài hát");
        table.Add("DisplayModes.Rest.Row.DeviceButton.Title", "Hiện nút thiết bị phát trong lớp nghỉ");
        table.Add("DisplayModes.Rest.Row.Entry.Description", "Mở bảng điều khiển đầy đủ khi con trỏ đi vào thanh phương tiện hoặc nhấp vào dải mỏng phía trên vùng chữ");
        table.Add("DisplayModes.Rest.Row.Entry.Title", "Hiện lối vào bảng điều khiển đầy đủ");
        table.Add("DisplayModes.Rest.Row.Layout.Description", "Đặt tiêu đề và nghệ sĩ trên cùng một dòng cạnh nhau hoặc xếp chồng lên nhau");
        table.Add("DisplayModes.Rest.Row.Layout.Title", "Bố cục nội dung");
        table.Add("DisplayModes.Rest.Row.Progress.Description", "Thanh tiến trình chỉ đọc dọc theo đáy của lớp nghỉ; tự động ẩn khi nguồn phát không báo thời lượng");
        table.Add("DisplayModes.Rest.Row.Progress.Title", "Hiện tiến trình phát");
        table.Add("DisplayModes.Rest.Row.VolumeButton.Description", "Nhấp chuột mở menu âm lượng và lăn chuột để chỉnh âm lượng nguồn hiện tại; giữ nút này sẽ chiếm bớt không gian chữ bài hát");
        table.Add("DisplayModes.Rest.Row.VolumeButton.Title", "Hiện nút âm lượng trong lớp nghỉ");
        table.Add("DisplayModes.Status.Current", "Hiện tại: {0}");
        table.Add("DisplayModes.Unimplemented.DesktopCard", "Chế độ thẻ màn hình nền hiện chưa được phát triển nên chưa có cài đặt. Mỗi chế độ sẽ có trang cài đặt riêng sau này.");
        table.Add("DisplayModes.Unimplemented.FloatingBall", "Chế độ bóng nổi hiện chưa được phát triển nên chưa có cài đặt. Mỗi chế độ sẽ có trang cài đặt riêng sau này.");
        table.Add("DisplayModes.Width.Group.Description", "Độ rộng của thanh phương tiện và khoảng cách bên trong");
        table.Add("DisplayModes.Width.RangeText", "Phạm vi khả dụng: {0:0}–{1:0} DIP");
        table.Add("DisplayModes.Width.Row.Fixed.Badge", "Cần tắt tự động theo nội dung trước");
        table.Add("DisplayModes.Width.Row.Fixed.Description", "Nhận giá trị nằm giữa độ rộng tối thiểu cần thiết và độ rộng khả dụng trên thanh tác vụ");
        table.Add("DisplayModes.Width.Row.Fixed.Title", "Độ rộng cố định");
        table.Add("DisplayModes.Width.Row.Follow.Description", "Độ rộng thanh phương tiện tự động co giãn theo độ dài tiêu đề");
        table.Add("DisplayModes.Width.Row.Follow.Title", "Tự động theo độ dài nội dung");
        table.Add("DisplayModes.Width.Row.Spacing.Description", "Khoảng cách ngang giữa khu vực ảnh bìa, vùng chữ và các thành phần bổ sung");
        table.Add("DisplayModes.Width.Row.Spacing.Title", "Khoảng cách thành phần");

        // ---- Interaction ----
        table.Add("Interaction.Header.Subtitle", "Hành động kích hoạt của từng cử chỉ trên thanh phương tiện và biểu tượng khay hệ thống");
        table.Add("Interaction.InApp.Group.Description", "Hành động khi nhấp chuột vào lớp nghỉ");
        table.Add("Interaction.Row.ArtworkClick.Description", "Cài đặt độc lập với hàng bên dưới");
        table.Add("Interaction.Row.ArtworkClick.Title", "Nhấp vào ảnh bìa");
        table.Add("Interaction.Row.ChordWheel.Description", "Giữ phím bổ trợ ở trên đồng thời lăn con trỏ chuột");
        table.Add("Interaction.Row.Modifier.Description", "Thanh phương tiện và biểu tượng khay dùng chung một phím bổ trợ");
        table.Add("Interaction.Row.Modifier.Title", "Phím bổ trợ kết hợp con lăn");
        table.Add("Interaction.Row.PrimaryWheel.Description", "Hành vi con lăn khi không giữ phím bổ trợ");
        table.Add("Interaction.Row.TextClick.Title", "Nhấp vào tiêu đề hoặc lời");
        table.Add("Interaction.Row.TrayChordWheel.Description", "Hiện danh sách thiết bị ứng viên trước và áp dụng lựa chọn sau khoảng 1,2 giây ngừng cuộn");
        table.Add("Interaction.Row.TrayClick.Description", "Nút chuột phải luôn mở menu; tùy chọn này đặt hành vi khi nhấp chuột trái");
        table.Add("Interaction.Row.TrayClick.Title", "Nhấp vào biểu tượng khay hệ thống");
        table.Add("Interaction.Row.TrayPrimaryWheel.Description", "Chỉ áp dụng khi con trỏ chuột nằm trên biểu tượng khay");
        table.Add("Interaction.SharedModifier.Callout", "Khi nút chuột trái hoặc phải được dùng làm phím bổ trợ, cú nhấp hoặc menu sinh ra sau khi lăn chuột sẽ bị chặn để tránh thao tác nhầm.");
        table.Add("Interaction.SharedModifier.Group.Description", "Giữ phím bổ trợ này khi lăn con lăn để kích hoạt cử chỉ con lăn kết hợp");
        table.Add("Interaction.Disabled", "vô hiệu hóa");
        table.Add("Interaction.TrayAction.OpenAudioControl", "Mở menu điều khiển âm thanh");
        table.Add("Interaction.TrayAction.OpenContextMenu", "Mở menu ngữ cảnh");
        table.Add("Interaction.TrayAction.OpenCurrentAppVolumeMenu", "Mở menu âm lượng ứng dụng hiện tại");
        table.Add("Interaction.TrayAction.OpenOutputDeviceMenu", "Mở menu thiết bị phát");
        table.Add("Interaction.TrayAction.OpenSettings", "Mở trang cài đặt");
        table.Add("Interaction.Wheel.Chord.Title", "Con lăn kết hợp phím");
        table.Add("Interaction.Wheel.Primary.Title", "Con lăn đơn thuần");

        // ---- Layout ----
        table.Add("Layout.Arrangement.Auto", "Tự động");
        table.Add("Layout.Arrangement.Horizontal", "Ngang");
        table.Add("Layout.Arrangement.Vertical", "Dọc");
        table.Add("Layout.Group.Position", "Vị trí");
        table.Add("Layout.Group.Size", "Kích thước");
        table.Add("Layout.Group.Window", "Cửa sổ");
        table.Add("Layout.IslandBackground.SystemTheme", "Nền chủ đề hệ thống");
        table.Add("Layout.IslandBackground.Transparent", "Nền trong suốt");
        table.Add("Layout.Page.Subtitle", "Điều chỉnh chế độ cửa sổ, hướng sắp xếp và kích thước");
        table.Add("Layout.Page.Title", "Bố cục");
        table.Add("Layout.Preset.DynamicIslandHorizontal", "Chủ đề đảo động (ngang): có thể kéo thả và thu gọn vào cạnh màn hình");
        table.Add("Layout.Preset.DynamicIslandVertical", "Chủ đề đảo động (dọc): có thể kéo thả và thu gọn vào cạnh màn hình");
        table.Add("Layout.Preset.TaskbarHorizontal", "Chủ đề thanh tác vụ (ngang): phù hợp với thanh tác vụ ở trên cùng hoặc dưới cùng");
        table.Add("Layout.Preset.TaskbarVertical", "Chủ đề thanh tác vụ (dọc): phù hợp với thanh tác vụ ở cạnh trái hoặc phải");
        table.Add("Layout.Reset.Button", "Khôi phục mặc định");
        table.Add("Layout.Row.Arrangement.Description", "Đặt hướng sắp xếp nội dung phương tiện");
        table.Add("Layout.Row.Arrangement.Title", "Hướng sắp xếp");
        table.Add("Layout.Row.AvoidIcons.Description", "Tự động giới hạn chiều dài và vị trí để không che biểu tượng tác vụ");
        table.Add("Layout.Row.AvoidIcons.Title", "Tránh biểu tượng thanh tác vụ");
        table.Add("Layout.Row.EdgeOffset.Description", "Di chuyển lên/xuống trên thanh tác vụ ngang và trái/phải trên thanh tác vụ dọc");
        table.Add("Layout.Row.EdgeOffset.Title", "Độ lệch mép");
        table.Add("Layout.Row.IslandBackground.Description", "Dùng màu chủ đề hệ thống hoặc nền trong suốt");
        table.Add("Layout.Row.IslandBackground.Title", "Kiểu nền");
        table.Add("Layout.Row.LengthScale.Description", "Điều chỉnh khoảng cách giữa các thành phần như ảnh bìa, lời bài hát và tiêu đề");
        table.Add("Layout.Row.LengthScale.Title", "Tỷ lệ khoảng cách thành phần");
        table.Add("Layout.Row.LockPosition.Description", "Giữ thanh phương tiện ở vị trí hiện tại");
        table.Add("Layout.Row.LockPosition.Title", "Khóa vị trí");
        table.Add("Layout.Row.ResetPage.Description", "Khôi phục cài đặt cửa sổ, sắp xếp, tỷ lệ, thanh tác vụ và đảo động");
        table.Add("Layout.Row.ResetPosition.Description", "Khôi phục vị trí mặc định");
        table.Add("Layout.Row.ThicknessScale.Description", "Thu phóng tỷ lệ mọi thành phần trong khi khoảng cách giữa chúng giữ nguyên");
        table.Add("Layout.Row.ThicknessScale.Title", "Tỷ lệ độ dày thành phần");
        table.Add("Layout.Row.WindowMode.Description", "Chọn nơi xuất hiện thanh phương tiện");
        table.Add("Layout.Row.WindowMode.Title", "Chế độ cửa sổ");
        table.Add("Layout.WindowMode.Taskbar", "Gắn vào thanh tác vụ");

        // ---- Lyrics ----
        table.Add("Lyrics.Adoption.FirstArrival", "Kết quả đầu tiên đến");
        table.Add("Lyrics.Adoption.PreferDefaultSource", "Ưu tiên nguồn mặc định");
        table.Add("Lyrics.Adoption.PreferDefaultSourceWithDeadline", "Ưu tiên nguồn mặc định (có giới hạn thời gian)");
        table.Add("Lyrics.DefaultBindings.Add", "Thêm trình phát");
        table.Add("Lyrics.DefaultBindings.Remark.Placeholder", "Ghi chú");
        table.Add("Lyrics.DefaultBindings.Add.Placeholder", "Nhập AppID (AUMID hoặc một đoạn ký tự)");
        table.Add("Lyrics.DefaultBindings.Expander.Description", "Nhận diện các trình phát đang chạy và chọn nguồn lời bài hát mặc định cho từng trình phát; trình phát chưa gán sẽ không có nguồn mặc định");
        table.Add("Lyrics.DefaultBindings.Expander.Title", "Gán nguồn lời mặc định");
        table.Add("Lyrics.DefaultBindings.None", "Chưa gán (không có nguồn mặc định)");
        table.Add("Lyrics.DefaultBindings.Player.Kugou", "Kugou Music");
        table.Add("Lyrics.DefaultBindings.Player.Netease", "NetEase Music");
        table.Add("Lyrics.DefaultBindings.Player.QQMusic", "QQ Music");
        table.Add("Lyrics.DefaultBindings.Player.SodaMusic", "Soda Music");
        table.Add("Lyrics.DefaultBindings.Remove", "Xóa dòng này");
        table.Add("Lyrics.DefaultBindings.Scan", "Quét các trình phát đang mở");
        table.Add("Lyrics.QueryStrategy.Concurrent", "Đồng thời");
        table.Add("Lyrics.QueryStrategy.Sequential", "Tuần tự");
        table.Add("Lyrics.Callout.Display", "Khi có lời bài hát thanh phương tiện sẽ hiển thị lời; khi không có sẽ hiển thị tiêu đề và nghệ sĩ.");
        table.Add("Lyrics.Header.Subtitle", "Lời bài hát hiện tại trong lớp nghỉ của thanh tác vụ");
        table.Add("Lyrics.Row.QueryStrategy.Description", "Thử từng nguồn một hoặc gửi yêu cầu đồng thời (nguồn mặc định và các nhóm ưu tiên truy vấn cùng nhau); chế độ tuần tự chỉ tuân theo thứ tự ưu tiên");
        table.Add("Lyrics.Row.QueryStrategy.Title", "Chiến lược truy vấn");
        table.Add("Lyrics.Row.AdoptionMode.Description", "Cách chọn kết quả khi truy vấn đồng thời; \"Ưu tiên nguồn mặc định\" ưu tiên giao diện khớp với trình phát đang phát");
        table.Add("Lyrics.Row.AdoptionMode.Title", "Chế độ áp dụng kết quả");
        table.Add("Lyrics.Row.BatchSize.Description", "Số nguồn truy vấn đồng thời trong mỗi đợt; đợt tiếp theo chỉ được gọi sau khi đợt hiện tại đều không tìm thấy");
        table.Add("Lyrics.Row.BatchSize.Title", "Số lượng truy vấn đồng thời");
        table.Add("Lyrics.Row.Deadline.Description", "Khi một nguồn ưu tiên đã phản hồi trước, nguồn mặc định sẽ có khoảng thời gian này để phản hồi; chỉ áp dụng cho \"Ưu tiên nguồn mặc định (có giới hạn thời gian)\"");
        table.Add("Lyrics.Row.Deadline.Title", "Hạn chót nguồn mặc định");
        table.Add("Lyrics.Row.Alignment.Description", "Cách căn lề lời bài hát trong lớp nghỉ; căn lề tiêu đề và nghệ sĩ là cài đặt riêng trong trang chế độ hiển thị");
        table.Add("Lyrics.Row.Alignment.Title", "Căn lề lời bài hát");
        table.Add("Lyrics.Row.InfoLines.Description", "Ẩn các dòng thông tin ghi công như nhạc sĩ, người soạn lời, nhà sản xuất");
        table.Add("Lyrics.Row.InfoLines.Title", "Lọc các dòng ghi công");
        table.Add("Lyrics.Row.MatchStrictness.Description", "Mức độ trùng khớp của tìm kiếm lời theo tiêu đề; càng nghiêm ngặt thì càng ít chấp nhận các bản live hoặc cover trùng tên");
        table.Add("Lyrics.Row.MatchStrictness.Title", "Độ nghiêm ngặt khớp tìm kiếm");
        table.Add("Lyrics.Row.SecondLine.Description", "Dòng thứ hai hiển thị bản dịch, phiên âm hoặc câu tiếp theo; thứ tự đại diện cho độ ưu tiên và nguồn thiếu sẽ được bỏ qua");
        table.Add("Lyrics.Row.SecondLine.Note", "Thứ tự là mức độ ưu tiên: nguồn liệt kê trước sẽ được dùng trước, nguồn trống sẽ chuyển tiếp xuống nguồn sau");
        table.Add("Lyrics.Row.SecondLine.OrderRow.Description", "Di chuyển hàng lên trên sẽ nâng cao độ ưu tiên");
        table.Add("Lyrics.Row.SecondLine.Title", "Nội dung dòng thứ hai");
        table.Add("Lyrics.Row.ShowLyrics.Description", "Đồng bộ câu hát hiện tại theo tiến độ phát nhạc; khi tắt sẽ hiển thị tiêu đề và nghệ sĩ");
        table.Add("Lyrics.Row.ShowLyrics.Title", "Hiện lời bài hát thời gian thực");
        table.Add("Lyrics.Row.SyllableHighlight.Description", "Làm sáng câu hát theo từng âm tiết khi có dữ liệu dòng thời gian âm tiết; không hiệu ứng khi tạm dừng, độ tương phản cao hoặc tắt animation hệ thống");
        table.Add("Lyrics.Row.SyllableHighlight.Title", "Chạy chữ theo âm tiết");
        table.Add("Lyrics.Row.TwoLine.Badge", "Cần bật lời bài hát trước");
        table.Add("Lyrics.Row.TwoLine.Description", "Thêm một dòng phụ bên dưới câu hát hiện tại");
        table.Add("Lyrics.Row.TwoLine.Title", "Lời bài hát hai dòng");
        table.Add("Lyrics.Row.UnsungOpacity.Badge", "Cần bật chạy chữ âm tiết trước");
        table.Add("Lyrics.Row.UnsungOpacity.Description", "Độ mờ đục của chữ chưa hát tới; giá trị càng thấp độ tương phản càng rõ (mặc định 45%)");
        table.Add("Lyrics.Row.UnsungOpacity.Title", "Độ mờ phần chưa hát");
        table.Add("Lyrics.Row.LineGap.Badge", "Cần bật lời hai dòng trước");
        table.Add("Lyrics.Row.LineGap.Description", "Khoảng cách bổ sung giữa hai dòng theo tỷ lệ phần trăm cỡ chữ; tự động co lại khi thiếu không gian, chữ không bao giờ bị cắt hay co méo (mặc định 0)");
        table.Add("Lyrics.Row.LineGap.Title", "Khoảng cách dòng");
        table.Add("Lyrics.Row.CharacterSpacing.Description", "Khoảng cách giữa các ký tự theo tỷ lệ phần trăm cỡ chữ; áp dụng cho cả CJK và Latin mà không làm ngắt từ (mặc định 0)");
        table.Add("Lyrics.Row.CharacterSpacing.Title", "Khoảng cách ký tự");
        table.Add("Lyrics.Row.FixedWidth.Badge", "Cần bật lời bài hát trước");
        table.Add("Lyrics.Row.FixedWidth.Description", "Giữ khung lời bài hát ở độ dài cố định thay vì đổi kích thước theo từng câu; khi tắt sẽ tự co giãn theo nội dung (mặc định tắt)");
        table.Add("Lyrics.Row.FixedWidth.Title", "Cố định độ dài khung lời");
        table.Add("Lyrics.Row.FixedWidth.Length.Description", "Chiều dài của khung lời ở chế độ cố định (DIP); tự động ép nhỏ lại khi thanh tác vụ thiếu chỗ (mặc định 240)");
        table.Add("Lyrics.Row.FixedWidth.Length.Title", "Độ dài khung lời");
        table.Add("Lyrics.SecondLine.NextLine", "Câu hát tiếp theo");
        table.Add("Lyrics.SecondLine.Reset.Description", "Khôi phục thứ tự về câu tiếp theo, bản dịch, phiên âm");
        table.Add("Lyrics.SecondLine.Reset.Title", "Khôi phục thứ tự mặc định");
        table.Add("Lyrics.SecondLine.Romanization", "Phiên âm của câu hiện tại");
        table.Add("Lyrics.SecondLine.Translation", "Bản dịch của câu hiện tại");
        table.Add("Lyrics.Source.Kugou", "Kugou Music");
        table.Add("Lyrics.Source.LRCLIB", "LRCLIB");
        table.Add("Lyrics.Source.Netease", "NetEase Cloud Music");
        table.Add("Lyrics.Source.NeteaseSearch", "NetEase Cloud Music (tìm kiếm)");
        table.Add("Lyrics.Source.QQMusic", "QQ Music");
        table.Add("Lyrics.Source.SodaMusic", "Soda Music");
        table.Add("Lyrics.Source.Unknown", "Nguồn không xác định");
        table.Add("Lyrics.Sources.AllDisabled.Callout", "Tất cả nguồn lời bài hát đã bị tắt: không có yêu cầu nào được gửi và thanh phương tiện chỉ hiện tiêu đề cùng nghệ sĩ.");
        table.Add("Lyrics.Sources.Callout", "Lời bài hát được yêu cầu từ các nguồn đã bật theo thứ tự bên dưới và dừng lại ngay ở kết quả đầu tiên; mỗi nguồn chỉ gửi truy vấn một lần.");
        table.Add("Lyrics.Sources.Expander.Description", "Những nguồn nào đang bật và theo thứ tự ưu tiên nào");
        table.Add("Lyrics.Sources.Expander.Title", "Thứ tự ưu tiên nguồn dự phòng");
        table.Add("Lyrics.Sources.Expander.Title.Sequential", "Thứ tự ưu tiên");
        table.Add("Lyrics.Sources.MoveDown", "Di chuyển xuống");
        table.Add("Lyrics.Sources.MoveUp", "Di chuyển lên");
        table.Add("Lyrics.Sources.Reset.Action", "Khôi phục mặc định");
        table.Add("Lyrics.Sources.Reset.Description", "Bật lại tất cả nguồn và sắp xếp theo thứ tự ưu tiên mặc định");
        table.Add("Lyrics.Sources.Reset.Title", "Khôi phục thứ tự mặc định");
        table.Add("Lyrics.Sources.Row.Description", "Khi tắt, nguồn này sẽ không còn được gửi yêu cầu tìm lời");
        table.Add("Lyrics.Strictness.Balanced", "Cân bằng");
        table.Add("Lyrics.Strictness.Exact", "Chính xác tuyệt đối");
        table.Add("Lyrics.Strictness.Strict", "Nghiêm ngặt");

        // ---- Media ----
        table.Add("Media.Badge.EnableFirst", "Cần bật trước");
        table.Add("Media.Dialog.Browse.Filter", "Ứng dụng và phím tắt (*.exe;*.lnk)|*.exe;*.lnk");
        table.Add("Media.Dialog.Browse.Title", "Chọn ứng dụng phát nhạc hoặc phím tắt");
        table.Add("Media.Header.Subtitle", "Nguồn phương tiện, khởi động nhanh, thành phần lớp nghỉ và thông báo bài hát");
        table.Add("Media.Metric.ProcessMemory.Title", "Bộ nhớ ứng dụng này sử dụng");
        table.Add("Media.Metric.SystemMemory.Description", "Cần ít nhất một chỉ số hiển thị nên không thể tắt chỉ số cuối cùng");
        table.Add("Media.Metric.SystemMemory.Title", "Bộ nhớ hệ thống");
        table.Add("Media.Notification.Details.Description", "Vị trí, thời gian hiển thị và màn hình mục tiêu");
        table.Add("Media.Notification.Details.Title", "Chi tiết thông báo");
        table.Add("Media.Notification.Duration.Title", "Thời lượng hiển thị");
        table.Add("Media.Notification.Duration.Value", "{0} giây");
        table.Add("Media.Notification.Enabled.Description", "Hiển thị bài hát hiện tại khi đổi bài hoặc bắt đầu phát nhạc");
        table.Add("Media.Notification.Enabled.Title", "Bật thông báo bài hát");
        table.Add("Media.Notification.FixedMonitor.Title", "Màn hình cố định");
        table.Add("Media.Notification.Fullscreen.Description", "Mặc định thông báo sẽ tự ẩn khi có cửa sổ toàn màn hình");
        table.Add("Media.Notification.Fullscreen.Title", "Hiển thị khi toàn màn hình");
        table.Add("Media.Notification.Position.BottomCenter", "Dưới đáy - ở giữa");
        table.Add("Media.Notification.Position.BottomLeft", "Dưới đáy - bên trái");
        table.Add("Media.Notification.Position.BottomRight", "Dưới đáy - bên phải");
        table.Add("Media.Notification.Position.Title", "Vị trí");
        table.Add("Media.Notification.Position.TopCenter", "Trên cùng - ở giữa");
        table.Add("Media.Notification.Position.TopLeft", "Trên cùng - bên trái");
        table.Add("Media.Notification.Position.TopRight", "Trên cùng - bên phải");
        table.Add("Media.Notification.TargetMode.Description", "Một màn hình cố định hoặc màn hình của cửa sổ đang hoạt động");
        table.Add("Media.Notification.TargetMode.Fixed", "Màn hình cố định");
        table.Add("Media.Notification.TargetMode.ForegroundWindow", "Màn hình của cửa sổ tiền cảnh");
        table.Add("Media.Performance.Metrics.Description", "Các chỉ số đã chọn sẽ được hiển thị luân phiên");
        table.Add("Media.Performance.Metrics.Title", "Chỉ số cần hiển thị");
        table.Add("Media.Performance.OpenTaskManager.Description", "Khi tắt tính năng này, nhấp vào thành phần hiệu năng sẽ không làm gì");
        table.Add("Media.Performance.OpenTaskManager.Title", "Mở Task Manager khi nhấp vào thành phần hiệu năng");
        table.Add("Media.Performance.RefreshInterval.Description", "Khoảng thời gian lấy mẫu; giá trị càng nhỏ cập nhật càng nhanh (0.5–5 giây)");
        table.Add("Media.Performance.RefreshInterval.Title", "Khoảng thời gian làm mới");
        table.Add("Media.Performance.RefreshInterval.Value", "{0:0.#} giây");
        table.Add("Media.Performance.Visible.Description", "Luân phiên hiển thị các chỉ số đã chọn ở phía bên phải lớp nghỉ");
        table.Add("Media.Performance.Visible.Title", "Hiện thành phần theo dõi hiệu năng");
        table.Add("Media.QuickLaunch.Browse", "Duyệt tìm ứng dụng hoặc phím tắt");
        table.Add("Media.QuickLaunch.Entries.Description", "Sắp xếp lại chỉ ảnh hưởng tới thứ tự ưu tiên khởi động của danh sách này");
        table.Add("Media.QuickLaunch.Entries.Title", "Các mục đã thêm");
        table.Add("Media.QuickLaunch.EntryCount", "{0} mục");
        table.Add("Media.QuickLaunch.FromNote.Description", "Nhấp vào biểu tượng nốt nhạc để mở danh sách khởi động nhanh; lăn chuột để xem trước và mục cuối cùng sẽ khởi chạy sau khoảng 1,2 giây ngừng cuộn");
        table.Add("Media.QuickLaunch.FromNote.Title", "Khởi chạy từ biểu tượng nốt nhạc khi không phát nhạc");
        table.Add("Media.QuickLaunch.MoveDown", "Di chuyển xuống một vị trí");
        table.Add("Media.QuickLaunch.MoveUp", "Di chuyển lên một vị trí");
        table.Add("Media.QuickLaunch.Remove", "Xóa khỏi khởi động nhanh");
        table.Add("Media.RestComponents.Description", "Hai thành phần được phủ ở phía bên phải của lớp nghỉ");
        table.Add("Media.SourceFilter.Description", "Chỉ chấp nhận các ứng dụng có trong danh sách; danh sách vẫn được lưu khi tính năng này tắt");
        table.Add("Media.SourceFilter.Title", "Danh sách nguồn được phép");
        table.Add("Media.SourceList.AddToQuickLaunch", "Thêm vào khởi động nhanh");
        table.Add("Media.SourceList.AddToQuickLaunch.ToolTip", "Chỉ có thể thêm các trình phát có thể tự động xác định phương thức khởi chạy; khi không tìm thấy, hãy dùng \"Duyệt tìm ứng dụng hoặc phím tắt\".");
        table.Add("Media.SourceList.Allow", "Cho phép");
        table.Add("Media.SourceList.Description", "Trình phát chỉ xuất hiện ở đây sau khi đã chạy ít nhất một lần");
        table.Add("Media.SourceList.Title", "Nguồn phát đã phát hiện");
        table.Add("Media.Spectrum.BandCount.Description", "Số cột sóng âm (9–24); chiều rộng mỗi cột là cố định nên càng nhiều cột thì phổ sóng càng rộng");
        table.Add("Media.Spectrum.BandCount.Title", "Số lượng cột sóng");
        table.Add("Media.Spectrum.BandCount.Value", "{0} cột");
        table.Add("Media.Spectrum.ContentHeight.Description", "Chiều cao của phổ sóng (14–34 DIP, hướng vuông góc với thanh tác vụ); cột cao hơn không làm tăng chiều rộng phổ");
        table.Add("Media.Spectrum.ContentHeight.Title", "Chiều cao phổ sóng");
        table.Add("Media.Spectrum.ContentHeight.Value", "{0:0} DIP");
        table.Add("Media.Spectrum.Parameters.Description", "Số cột, chiều cao, tốc độ làm mới và độ nhạy");
        table.Add("Media.Spectrum.Parameters.Title", "Thông số phổ sóng");
        table.Add("Media.Spectrum.RefreshRate.Description", "Tần suất làm mới phổ sóng (5–30 Hz)");
        table.Add("Media.Spectrum.RefreshRate.Title", "Tốc độ làm mới");
        table.Add("Media.Spectrum.Sensitivity.Description", "Mức âm thanh mà tại đó cột sóng đạt chiều cao tối đa (10%–400%)");
        table.Add("Media.Spectrum.Sensitivity.Title", "Độ nhạy");
        table.Add("Media.Spectrum.Style.Bars", "Cột sóng cổ điển");
        table.Add("Media.Spectrum.Style.Description", "Cách vẽ phổ sóng; không làm thay đổi số lượng cột cũng như chiều rộng chiếm dụng");
        table.Add("Media.Spectrum.Style.MirroredBars", "Cột sóng đối xứng");
        table.Add("Media.Spectrum.Style.PixelBars", "Cột sóng pixel");
        table.Add("Media.Spectrum.Style.Title", "Kiểu dáng");
        table.Add("Media.Spectrum.Style.Waveform", "Dạng sóng (Waveform)");
        table.Add("Media.Spectrum.Visible.Description", "Phổ sóng âm thanh trực tiếp ở phía bên phải lớp nghỉ");
        table.Add("Media.Spectrum.Visible.Title", "Hiện phổ sóng âm");
        table.Add("Media.Status.AddedToQuickLaunch", "Đã thêm vào khởi động nhanh.");
        table.Add("Media.Status.AlreadyFirst", "Mục này đã ở đầu danh sách.");
        table.Add("Media.Status.AlreadyInQuickLaunch", "Ứng dụng này đã có trong danh sách khởi động nhanh.");
        table.Add("Media.Status.AlreadyLast", "Mục này đã ở cuối danh sách.");
        table.Add("Media.Status.OnlyExistingFiles", "Chỉ có thể thêm tệp EXE hoặc LNK tồn tại.");
        table.Add("Media.Status.SourceLaunchUnresolved", "Không thể xác định cách khởi chạy nguồn này; hãy duyệt tìm tệp EXE hoặc LNK.");

        // ---- Panel ----
        table.Add("Panel.AudioFlyout.AppVolume", "Âm lượng ứng dụng");
        table.Add("Panel.AudioFlyout.Refresh", "Làm mới trạng thái âm thanh");
        table.Add("Panel.AudioFlyout.SpatialAudio", "Âm thanh không gian");
        table.Add("Panel.CompactMenu.WindowTitle", "Menu nhanh thanh tác vụ");
        table.Add("Panel.FullPanel.NoMedia", "Không có phương tiện");
        table.Add("Panel.FullPanel.LyricsSource", "Nguồn lời bài hát: {0}");
        table.Add("Panel.FullPanel.RepeatMode", "Chế độ lặp lại");
        table.Add("Panel.FullPanel.WindowTitle", "Bảng điều khiển phương tiện đầy đủ");
        table.Add("Panel.Notification.NowPlaying", "Đang phát");
        table.Add("Panel.Notification.WindowTitle", "Thông báo đổi bài hát");
        table.Add("Panel.Performance.Memory", "Bộ nhớ");
        table.Add("Panel.Performance.ProcessMemory", "Bộ nhớ tiến trình");
        table.Add("Panel.QuickLaunch.Empty", "Chưa có ứng dụng nào được thêm");
        table.Add("Panel.QuickLaunch.Preview", "Khởi động nhanh: {0}");
        table.Add("Panel.QuickLaunch.Title", "Khởi động nhanh");
        table.Add("Panel.Repeat.All", "Lặp lại tất cả");
        table.Add("Panel.Repeat.Off", "Tắt lặp lại");
        table.Add("Panel.Repeat.One", "Lặp lại một bài");
        table.Add("Panel.Repeat.Unavailable", "Không khả dụng");
        table.Add("Panel.Volume.CurrentAppVolume", "Âm lượng ứng dụng hiện tại");
        table.Add("Panel.Volume.CurrentMedia", "Phương tiện hiện tại");
        table.Add("Panel.Volume.Tooltip", "Âm lượng ứng dụng hiện tại / Bộ trộn âm lượng");
        table.Add("Panel.Volume.Unavailable", "Không khả dụng");

        // ---- Search ----
        table.Add("Search.About.Developers.Description", "Danh sách nhà phát triển, lấy từ danh sách người đóng góp GitHub");
        table.Add("Search.About.Licenses.Description", "Các gói nguồn mở và mã dẫn xuất được chương trình sử dụng, kèm theo giấy phép");
        table.Add("Search.About.ProjectInfo.Description", "Kho lưu trữ, kênh phản hồi và trợ giúp");
        table.Add("Search.About.Sponsors.Description", "Danh sách nhà tài trợ, đọc từ tệp trong kho lưu trữ");
        table.Add("Search.About.Support.Description", "Mã thanh toán WeChat, Alipay và liên kết tài trợ Afdian");
        table.Add("Search.Application.Application.Description", "Thông tin phiên bản, kiểm tra cập nhật, tự động cập nhật, khởi động cùng hệ thống và ngôn ngữ giao diện");
        table.Add("Search.Application.Diagnostics.Description", "Mở thư mục nhật ký (logs\\app.log, tệp gửi khi gặp lỗi) hoặc trả lại tập làm việc cho hệ thống");
        table.Add("Search.Application.SettingsFile.Description", "Mở thư mục cài đặt và đặt lại toàn bộ cài đặt");
        table.Add("Application.Header.Subtitle", "Phiên bản và cập nhật, ngôn ngữ giao diện, khởi động cùng Windows, tệp cài đặt và chẩn đoán");
        table.Add("Search.Appearance.Fonts.Description", "Phông chữ Latin, phông chữ CJK và độ đậm phông chữ");
        table.Add("Search.Appearance.MediaBarText.Description", "Màu sắc và kích thước chữ trên thanh phương tiện");
        table.Add("Search.Appearance.ThemeAndBackdrop.Description", "Giao diện sáng hoặc tối và chất liệu nền cửa sổ");
        table.Add("Search.DisplayModes.ChooseDisplayMode.Description", "Chế độ hiển thị thanh phương tiện: thanh tác vụ, đảo động, thẻ màn hình nền hoặc bóng nổi");
        table.Add("Search.DisplayModes.FullLayer.Description", "Các phần của bảng điều khiển mở ra khi nhấp vào thanh phương tiện");
        table.Add("Search.DisplayModes.HoverLayer.Description", "Các nút điều khiển nhanh xuất hiện khi con trỏ di vào thanh phương tiện");
        table.Add("Search.DisplayModes.IslandAppearance.Description", "Kiểu nền, độ mờ đục và bo góc của đảo động; hiện là chỉ đọc");
        table.Add("Search.DisplayModes.MediaBarWidth.Description", "Độ rộng cố định hoặc tự động theo nội dung và khoảng cách thành phần");
        table.Add("Search.DisplayModes.RestLayer.Description", "Lớp nền luôn hiển thị: mật độ thông tin, sắp xếp nội dung, căn lề, hiển thị tiến trình và lối vào bảng điều khiển");
        table.Add("Search.DisplayModes.ScreenAndPlacement.Description", "Màn hình đặt thanh phương tiện và vị trí trên thanh tác vụ");
        table.Add("Search.Interaction.InAppRestLayer.Description", "Hành động khi nhấp vào lớp nghỉ: nhấp ảnh bìa, nhấp chữ và con lăn");
        table.Add("Search.Interaction.SharedModifier.Description", "Phím bổ trợ con lăn kết hợp dùng chung giữa thanh tác vụ và khay hệ thống");
        table.Add("Search.Interaction.TrayIcon.Description", "Hành vi nhấp chuột và lăn con trỏ trên biểu tượng khay hệ thống");
        table.Add("Search.Lyrics.Alignment.Description", "Căn lề trái, giữa hoặc phải cho lời bài hát");
        table.Add("Search.Lyrics.Display.Description", "Hiển thị lời bài hát, dòng thứ hai, nội dung dòng thứ hai, chạy chữ âm tiết và lọc dòng ghi công");
        table.Add("Search.Lyrics.Sources.Description", "Chọn các nguồn lời bài hát, thứ tự ưu tiên và độ nghiêm ngặt tìm kiếm");
        table.Add("Search.MediaAndNotifications.MediaSource.Description", "Danh sách nguồn cho phép và các nguồn phát đã phát hiện");
        table.Add("Search.MediaAndNotifications.QuickLaunch.Description", "Khởi chạy trình phát từ biểu tượng nốt nhạc khi không phát nhạc");
        table.Add("Search.MediaAndNotifications.RestLayerComponents.Description", "Các thành phần phổ sóng và hiệu năng phủ ở bên phải lớp nghỉ");
        table.Add("Search.MediaAndNotifications.TrackChangeNotification.Description", "Hiển thị bài hát hiện tại khi bài hát mới bắt đầu phát");

        // ---- Service ----
        table.Add("Service.MediaSource.Kugou", "Kugou Music");
        table.Add("Service.MediaSource.NetEaseCloudMusic", "NetEase Cloud Music");
        table.Add("Service.MediaSource.QQMusic", "QQ Music");
        table.Add("Service.MediaSource.Unknown", "Nguồn không xác định");
        table.Add("Service.Startup.ExecutablePathUnavailable", "Không thể xác định đường dẫn chương trình nên không thể ghi mục khởi động");
        table.Add("Service.Startup.RegistryKeyUnavailable", "Không thể mở khóa đăng ký khởi động trong Registry");

        // ---- Settings ----
        table.Add("Settings.Legacy.About", "Giới thiệu AFMediaBar");
        table.Add("Settings.Legacy.Personalization", "Cá nhân hóa");
        table.Add("Settings.Legacy.Theme", "Chủ đề");
        table.Add("Settings.Legacy.ThemeDark", "Tối");
        table.Add("Settings.Legacy.ThemeLight", "Sáng");
        table.Add("Settings.Search.Placeholder", "Tìm kiếm cài đặt");
        table.Add("Settings.Search.Suggestion.Title", "{0} › {1}");

        // ---- Shell ----
        table.Add("Shell.QuickLaunch.Status.Failed", "Không thể khởi chạy ứng dụng; hãy kiểm tra xem ứng dụng còn khả dụng hay không.");
        table.Add("Shell.QuickLaunch.Status.InvalidTarget", "Mục tiêu khởi chạy không còn hợp lệ; hãy thêm lại trong trang Phương tiện và thông báo.");

        // ---- Startup ----
        table.Add("Startup.SingleInstance.AlreadyRunning", "AF Media Bar hiện đang chạy. Hãy tìm biểu tượng của ứng dụng ở khu vực thông báo góc dưới bên phải, hoặc chọn mũi tên để hiện các biểu tượng ẩn.");

        // ---- Update ----
        table.Add("Update.Channel.Accelerated", "Máy chủ tăng tốc {0}");
        table.Add("Update.Channel.Direct", "GitHub trực tiếp");
        table.Add("Update.Install.Blocked.OtherInstances", "Có các tiến trình khác của ứng dụng đang chạy");
        table.Add("Update.Install.Blocked.Portable", "Không hỗ trợ tự động cài đặt trên bản di động (Portable)");
        table.Add("Update.Navigation.Available", "Đã có phiên bản v{0}");
        table.Add("Update.Navigation.Downloading", "Đang tải bản cập nhật {0}%");
        table.Add("Update.Navigation.Ready", "Bản cập nhật đã sẵn sàng (v{0})");
        table.Add("Update.Navigation.Verifying", "Đang xác minh bản cập nhật");
        table.Add("Update.Notification.Body", "Đã có phiên bản v{0} (hiện tại v{1}). Nhấp để mở cài đặt, xem điểm mới và tải về.");
        table.Add("Update.Notification.Title", "Có bản cập nhật mới cho AF Media Bar");
        table.Add("Update.Reason.DownloadFailed", "Tải về thất bại (lỗi mạng hoặc ổ đĩa)");
        table.Add("Update.Reason.DownloadHashMismatch", "Xác minh bộ cài đặt thất bại (sai lệch mã SHA-256, đã nhận {0} byte)");
        table.Add("Update.Reason.DownloadHttp", "Tải về thất bại (HTTP {0})");
        table.Add("Update.Reason.DownloadTimeout", "Quá thời gian tải về");
        table.Add("Update.Reason.ManifestEmpty", "Danh sách phiên bản trống");
        table.Add("Update.Reason.ManifestEndpointInvalid", "Địa chỉ danh sách phiên bản không hợp lệ");
        table.Add("Update.Reason.ManifestHttp", "Không thể truy cập danh sách phiên bản (HTTP {0})");
        table.Add("Update.Reason.ManifestInvalidJson", "Danh sách phiên bản không phải JSON hợp lệ");
        table.Add("Update.Reason.ManifestNetwork", "Không thể truy cập danh sách phiên bản (lỗi mạng)");
        table.Add("Update.Reason.ManifestRootNotObject", "Gốc của danh sách phiên bản không phải đối tượng");
        table.Add("Update.Reason.ManifestSchemaInvalid", "schemaVersion của danh sách không phải số phiên bản hợp lệ");
        table.Add("Update.Reason.ManifestSchemaTooNew", "schemaVersion {0} của danh sách mới hơn phiên bản hỗ trợ {1}");
        table.Add("Update.Reason.ManifestUnreachable", "Không thể truy cập danh sách phiên bản");
        table.Add("Update.Reason.ManifestVersionMissing", "Danh sách không có trường phiên bản");
        table.Add("Update.Reason.ManifestVersionUnparsable", "Không thể phân tích cú pháp phiên bản ({0}) trong danh sách");
        table.Add("Update.Reason.NoUsableSource", "Không có địa chỉ tải về nào khả dụng");
        table.Add("Update.Reason.PendingRecordMissing", "Thiếu bản ghi của bộ cài đã tải về");
        table.Add("Update.Reason.Unknown", "nguyên nhân không xác định");
        table.Add("Update.Reason.VerifyHashMismatch", "Bộ cài đã tải không khớp mã SHA-256 trong danh sách và đã bị xóa");
        table.Add("Update.Reason.VerifyUnreadable", "Không thể đọc tệp cài đặt đã tải và tệp đã bị xóa");
        table.Add("Update.Relative.Days", "{0} ngày trước");
        table.Add("Update.Relative.Hours", "{0} giờ trước");
        table.Add("Update.Relative.JustNow", "vừa xong");
        table.Add("Update.Relative.Minutes", "{0} phút trước");
        table.Add("Update.Status.Available", "Đã có phiên bản v{0} (hiện tại v{1})");
        table.Add("Update.Status.Checking", "Đang kiểm tra bản cập nhật…");
        table.Add("Update.Status.Downloading", "Đang tải về và xác minh bộ cài {0}%");
        table.Add("Update.Status.Failed", "Cập nhật thất bại: {0}");
        table.Add("Update.Status.Idle", "Chưa kiểm tra bản cập nhật");
        table.Add("Update.Status.ManualOnly", "Đã có phiên bản v{0}, nhưng danh sách không cung cấp bộ cài có thể cài tự động");
        table.Add("Update.Status.Ready", "Bản cập nhật đã sẵn sàng (v{0}) · tự động cài đặt trong lần khởi động tiếp theo, hoặc khởi động lại và cài ngay bây giờ");
        table.Add("Update.Status.ReadyBlocked", "Đã tải về v{0}, nhưng {1}; vui lòng cập nhật thủ công từ trang tải về");
        table.Add("Update.Status.Skipped", "Đã bỏ qua v{0} (hiện tại v{1}) · kiểm tra thủ công vẫn sẽ báo phiên bản này");
        table.Add("Update.Status.UpToDate", "Đang sử dụng phiên bản mới nhất (v{0})");
        table.Add("Update.Status.Verifying", "Đang xác minh bộ cài {0}%");
        table.Add("Update.Suffix.Channel", " · {0}");
        table.Add("Update.Suffix.LastCheck", " · Kiểm tra lần cuối {0}");
        table.Add("Update.Suffix.Mandatory", " · Phiên bản này là bắt buộc");
        table.Add("Update.Tray.Available", "Đã có phiên bản v{0} (nhấp để xem)");
        table.Add("Update.Tray.Check", "Kiểm tra bản cập nhật");
        table.Add("Update.Tray.Checking", "Đang kiểm tra bản cập nhật…");
        table.Add("Update.Tray.Downloading", "Đang tải bản cập nhật {0}%");
        table.Add("Update.Tray.Failed", "Cập nhật thất bại, nhấp để thử lại");
        table.Add("Update.Tray.Ready", "Bản cập nhật đã sẵn sàng (v{0}), nhấp để khởi động lại và cài đặt");
        table.Add("Update.Tray.Verifying", "Đang xác minh bộ cài {0}%");

        // ---- Wheel ----
        table.Add("Wheel.Action.CurrentMediaVolume", "Âm lượng phương tiện hiện tại");
        table.Add("Wheel.Action.MediaSource", "Nguồn phương tiện");
        table.Add("Wheel.Hint.Chord", "{0} + con lăn: {1}");
        table.Add("Wheel.Hint.Plain", "Con lăn đơn thuần: {0}");
        table.Add("Wheel.Hint.WithValue", "{0} (hiện tại: {1})");
        table.Add("Wheel.Line.WithValue", "{0}: {1}");
    }
}
