namespace AFMediaBar.Classes.Services.Localization.Strings;

/// <summary>
/// 英文文案。
///
/// 一种语言一份文件：翻译与校对只碰这一个文件，新增语言就是再增一个同构文件，并在 <c>Translations</c> 的登记列表里加一行。
/// 键必须与另外两份语言文件完全一致：缺一条时该语言会回退到简体中文，所以漏翻译只能靠逐行对照三份文件发现；
/// 三份文件的键顺序也相同，因此同一行号在三份文件里指的是同一条文案。
/// English text.
///
/// One file per language: translating and proofreading touch only this file, and adding a language means adding one more
/// file of the same shape plus a line in the registration list inside <c>Translations</c>. The keys have to match the other
/// two files exactly: a missing entry falls back to simplified Chinese, so a gap is found by comparing the three files, and
/// because all three files share one key order the same line number means the same string in every one of them.
/// </summary>
internal static class StringsEn
{
    /// <summary>登记本语言文案。/ Registers the text of this language.</summary>
    /// <param name="table">该语言的文案表。/ The text table of this language.</param>
    internal static void Register(LanguageTable table)
    {
        // ---- About ----
        table.Add("About.Header.Subtitle", "Developers, sponsors, and open-source licenses");
        table.Add("About.Language.Description", "The language of the interface text; \"follow the system\" takes it from the Windows display language, and a change applies immediately");
        table.Add("About.Language.English", "English");
        table.Add("About.Language.FollowSystem", "Follow the system");
        table.Add("About.Language.SimplifiedChinese", "简体中文");
        table.Add("About.Language.Title", "Interface language");
        table.Add("About.Language.TraditionalChinese", "繁體中文");
        table.Add("About.Language.Vietnamese", "Vietnamese");
        table.Add("About.ResetScope", "all settings");
        table.Add("About.Row.AutoCheck.Description", "Reads the public version manifest about 20 seconds after start; after a success it does not check again for 24 hours, and after a failure it retries an hour later. A new version raises one system notification, and clicking the notification opens this page");
        table.Add("About.Row.AutoCheck.Title", "Check for updates automatically");
        table.Add("About.Row.ClearDefaults.Description", "Deletes the saved defaults so every reset entry falls back to the built-in defaults");
        table.Add("About.Row.ClearDefaults.Title", "Clear my default settings");
        table.Add("About.Row.Download.Download", "Download and install");
        table.Add("About.Row.DownloadPage.Description", "When GitHub is unreachable, an accelerator site opens the same download page");
        table.Add("About.Row.DownloadPage.Mirror", "Accelerated mirror");
        table.Add("About.Row.DownloadPage.Title", "Open the download page");
        table.Add("About.Row.Install.Description", "Once the download and verification finish, the next start installs before launching the new version; it can also be installed right now");
        table.Add("About.Row.Install.Now", "Restart and install now");
        table.Add("About.Row.Install.Title", "Install the update");
        table.Add("About.Row.OpenFolder.Description", "Opens the folder holding settings.json, where it can be backed up or replaced directly");
        table.Add("About.Row.OpenFolder.Title", "Open the settings folder");
        table.Add("About.Row.LogFolder.Description", "The log is one file, logs\\app.log, holding the newest 1000 lines; send that file when something breaks");
        table.Add("About.Row.LogFolder.Title", "Log file");
        table.Add("About.Row.TrimMemory.Button", "Compress now");
        table.Add("About.Row.TrimMemory.Description", "Returns the working set — the physical memory in use — to the system: the figure in Task Manager drops at once, the next use has to read that part back in and may stutter briefly; the commit size does not change");
        table.Add("About.Row.TrimMemory.Title", "Compress memory usage");
        table.Add("Common.Group.Developers", "Developers");
        table.Add("Common.Group.Diagnostics", "Diagnostics and logs");
        table.Add("About.Row.Portable.Badge", "Portable");
        table.Add("About.Row.Portable.Description", "This is not an installed build, so files cannot be replaced automatically; get the installer from the download page or replace the program files by hand");
        table.Add("About.Row.Portable.Title", "Automatic updates are unavailable");
        table.Add("About.Row.Progress.Title", "Download progress");
        table.Add("About.Row.Project.Description", "Media experience for the Windows taskbar · version 1.0.0");
        table.Add("About.Row.Project.Issues", "Report an issue");
        table.Add("About.Row.Project.Star", "Star it on GitHub");
        table.Add("About.Row.ResetAll.Button", "Reset everything");
        table.Add("About.Row.ResetAll.Description", "Restores the display mode, interaction, lyrics, appearance, and media-notification settings to their defaults");
        table.Add("About.Row.ResetAll.Title", "Reset every setting");
        table.Add("About.Row.SaveDefaults.NotSaved", "Not saved: every \"restore this page's defaults\" entry falls back to the built-in defaults");
        table.Add("About.Row.SaveDefaults.Saved", "Saved: every \"restore this page's defaults\" entry returns to this snapshot");
        table.Add("About.Row.SaveDefaults.Title", "Save the current settings as defaults");
        table.Add("About.Row.Skip.Clear", "Stop skipping");
        table.Add("About.Row.Skip.Description", "Skipping affects only the automatic notice; a manual check still reports that version");
        table.Add("About.Licenses.Open", "Open project");
        table.Add("About.Support.Afdian", "Afdian");
        table.Add("About.Support.Alipay", "Alipay");
        table.Add("About.Support.Open", "Open link");
        table.Add("About.Support.Pending", "The payment codes and the support link are supplied by the author later; the path above is where the file belongs");
        table.Add("About.Support.SponsorNote", "Sponsorships above 10 CNY can join the sponsor list; please leave your ID in the payment note");
        table.Add("About.Support.WeChat", "WeChat");
        table.Add("Credits.Contributions", "{0} commits");
        table.Add("Credits.Reason.ContributorsEmpty", "The contributors list is empty");
        table.Add("Credits.Reason.ContributorsShape", "The contributors list has an unexpected shape");
        table.Add("Credits.Reason.Empty", "The list was empty");
        table.Add("Credits.Reason.InvalidJson", "The list is not valid JSON");
        table.Add("Credits.Reason.SchemaTooNew", "The sponsor list is schema version {0}, newer than the supported version {1}");
        table.Add("Credits.Reason.SponsorsShape", "The sponsor list has an unexpected shape");
        table.Add("Credits.Sponsors.Count", "{0} sponsors in total");
        table.Add("Credits.Sponsors.None", "No sponsors yet. If this list does not appear, press Retry, or add entries to docs/sponsors.json in the repository");
        table.Add("Credits.SponsorSeparator", ", ");
        table.Add("Credits.Status.Failed", "The lists cannot be loaded right now: {0}");
        table.Add("Credits.Status.Partial", "Part of the lists cannot be loaded right now: {0}");
        table.Add("Credits.Status.PartialCached", "Only part of the lists was fetched last time");
        table.Add("Credits.Status.Loading", "Loading the developer and sponsor lists…");
        table.Add("Credits.Retry", "Retry");
        table.Add("About.Row.Startup.Description", "Runs AF Media Bar after you sign in to Windows (writes only the current user's startup entry)");
        table.Add("About.Row.Startup.Title", "Start when signing in");
        table.Add("About.Row.Version.Check", "Check for updates");
        table.Add("About.Row.Version.Description", "The version installed now and the newest version in the public manifest");
        table.Add("About.Row.Version.Title", "Version");
        table.Add("About.Status.ClearDefaultsFailed", "Could not delete the defaults: {0}");
        table.Add("About.Status.SaveDefaultsFailed", "Could not save the defaults: {0}");
        table.Add("About.Status.StartupFailed", "Could not change the startup entry: {0}");

        // ---- Appearance ----
        table.Add("Appearance.Accent.Custom", "Custom");
        table.Add("Appearance.Accent.FollowSystem", "Follow the system");
        table.Add("Appearance.Accent.HexLabel", "Value");
        table.Add("Appearance.Accent.Hint", "The accent is used everywhere an accent colour appears: selection states and toggles in the settings, sliders, both progress bars, the media bar and flyout highlights, and the accent section of the full layer. Choosing Custom only affects this application; the Windows personalisation setting is not modified. High contrast still uses the system highlight colour.");
        table.Add("Appearance.Accent.PaletteLabel", "Pick an accent");
        table.Add("Appearance.Backdrop.Acrylic", "Acrylic");
        table.Add("Appearance.Backdrop.Mica", "Mica");
        table.Add("Appearance.Backdrop.MicaAlt", "Mica Alt");
        table.Add("Appearance.Backdrop.Solid", "Solid");
        table.Add("Appearance.BackdropTint.Hint", "Only applies where the application paints the material itself: windows on Windows 10, and the track notification, which never takes focus (the system materials need a foreground window, and a notification never activates, so its blur is painted by the application). Mica and Acrylic on Windows 11 are painted by the system and ignore this value. Lower is more transparent; very high values approach a solid surface.");
        table.Add("Appearance.CjkFont.FollowSystem", "Follow the system");
        table.Add("Appearance.LatinFont.FollowSystem", "Follow the system");
        table.Add("Appearance.Header.Subtitle", "Fonts, theme, window backdrop, and media-bar text");
        table.Add("Appearance.Motion.Detail.Full", "Keeps expansion, feedback, and spectrum transitions");
        table.Add("Appearance.Motion.Detail.Instant", "Follows the system setting to avoid transition latency");
        table.Add("Appearance.Motion.Detail.Reduced", "Blur, the marquee, and the continuous spectrum are turned off");
        table.Add("Appearance.Motion.Mode.Full", "Full motion");
        table.Add("Appearance.Motion.Mode.Instant", "Instant updates");
        table.Add("Appearance.Motion.Mode.Reduced", "Reduced motion");
        table.Add("Appearance.Preview.DarkWallpaper", "Dark wallpaper");
        table.Add("Appearance.Preview.Hint", "The automatic result depends on the actual color behind the taskbar, so both previews are indicative; the forced modes use one text color on both.");
        table.Add("Appearance.Preview.LightWallpaper", "Light wallpaper");
        table.Add("Appearance.Row.Accent.Description", "Follows the system by default; a custom accent only changes this application");
        table.Add("Appearance.Row.Accent.Title", "Accent colour");
        table.Add("Appearance.Row.Backdrop.Description", "Sets one backing for the settings window, tray pop-ups, and context menus");
        table.Add("Appearance.Row.Backdrop.Title", "Window backdrop material");
        table.Add("Appearance.Row.BackdropTint.Description", "Tint concentration of the material the application paints itself (30%-100%)");
        table.Add("Appearance.Row.BackdropTint.Title", "Material concentration");
        table.Add("Appearance.Row.CjkFont.Description", "The font used for Han characters");
        table.Add("Appearance.Row.CjkFont.Title", "CJK font");
        table.Add("Appearance.Row.FontWeight.Description", "The text weight shared by the settings window, the media bar, and notifications");
        table.Add("Appearance.Row.FontWeight.Title", "Font weight");
        table.Add("Appearance.Row.LatinFont.Description", "The font used for letters and digits");
        table.Add("Appearance.Row.LatinFont.Title", "Latin font");
        table.Add("Appearance.Row.MediaFontSize.Description", "Scales the rest layer's title, artist, and lyrics type size by a percentage (80%–125%)");
        table.Add("Appearance.Row.MediaFontSize.Title", "Media text size");
        table.Add("Appearance.Row.Motion.Title", "Interaction motion");
        table.Add("Appearance.Row.TextColor.Description", "The automatic mode picks light or dark from the color actually behind the text");
        table.Add("Appearance.Row.TextColor.Title", "Text color");
        table.Add("Appearance.Row.Theme.Description", "Follows the Windows light and dark setting automatically");
        table.Add("Appearance.Row.Theme.Title", "Application theme");
        table.Add("Appearance.Specimen.Label", "Font preview");
        table.Add("Appearance.TextColor.Automatic", "Automatic (from the backdrop)");
        table.Add("Appearance.TextColor.DarkText", "Always dark text");
        table.Add("Appearance.TextColor.LightText", "Always light text");
        table.Add("Appearance.Theme.Automatic", "Automatic (follow the system)");
        table.Add("Appearance.Theme.Dark", "Dark");
        table.Add("Appearance.Theme.Light", "Light");

        // ---- Audio ----
        table.Add("Audio.Application.SystemSounds", "System sounds");
        table.Add("Audio.Error.CreateDeviceEnumerator", "The Windows audio device enumerator could not be created.");
        table.Add("Audio.Error.CreatePolicyConfig", "The Windows audio policy service could not be created.");
        table.Add("Audio.OutputDevice.Unavailable", "Output device: unavailable");
        table.Add("Audio.OutputDevice.Unchanged", "Output device: unchanged");
        table.Add("Audio.OutputDevice.Value", "Output device: {0}");
        table.Add("Audio.Spatial.Enabled", "Enabled");
        table.Add("Audio.Spatial.NoDevice", "No output device");
        table.Add("Audio.Spatial.Off", "Off");
        table.Add("Audio.Spatial.Unavailable", "Status unavailable");
        table.Add("Audio.Spatial.Unsupported", "Not supported by this device");
        table.Add("Audio.Status.AdjustApplicationVolumeFailed", "Adjusting the volume of {0} failed: {1}");
        table.Add("Audio.Status.NoSessions", "No application audio sessions");
        table.Add("Audio.Status.OpenSoundSettingsFailed", "Opening the Windows sound settings failed: {0}");
        table.Add("Audio.Status.ReadFailed", "Reading the audio state failed: {0}");
        table.Add("Audio.Status.SwitchOutputDeviceFailed", "Switching the output device failed: {0}");
        table.Add("Audio.Tooltip.AdjustVolumeFailed", "Adjusting the volume failed");
        table.Add("Audio.Tooltip.SwitchOutputDeviceFailed", "Switching the output device failed");
        table.Add("Audio.Tooltip.WheelDisabled", "Tray wheel disabled");
        table.Add("Audio.Volume.CurrentValue", "{0} {1}%");
        table.Add("Audio.Volume.Unavailable", "Current media volume: unavailable");
        table.Add("Audio.Volume.Unchanged", "Current media volume: unchanged");
        table.Add("Audio.Volume.Value", "{0}: {1}%");

        // ---- Common ----
        table.Add("Common.ActivateSourceApplication", "Open the playing application");
        table.Add("Common.AdjustCurrentMediaVolume", "Adjust current media volume");
        table.Add("Common.AlignCenter", "Center");
        table.Add("Common.AlignLeft", "Align left");
        table.Add("Common.AlignRight", "Align right");
        table.Add("Common.AudioControl", "Audio control");
        table.Add("Common.Cancel", "Cancel");
        table.Add("Common.Clear", "Clear");
        table.Add("Common.DynamicIsland", "Dynamic island");
        table.Add("Common.Exit", "Exit");
        table.Add("Common.FullLayer", "Full panel");
        table.Add("Common.Group.Application", "Application");
        table.Add("Common.Group.ChooseDisplayMode", "Choose a display mode");
        table.Add("Common.Group.Fonts", "Fonts");
        table.Add("Common.Group.InAppRestLayer", "In the application (rest layer)");
        table.Add("Common.Group.IslandAppearance", "Dynamic island appearance");
        table.Add("Common.Group.Licenses", "Open-source licenses");
        table.Add("Common.Group.LyricsAlignment", "Alignment");
        table.Add("Common.Group.LyricsDisplay", "Display");
        table.Add("Common.Group.LyricsSources", "Lyric sources");
        table.Add("Common.Group.MediaBarText", "Media bar text");
        table.Add("Common.Group.MediaBarWidth", "Media bar width");
        table.Add("Common.Group.ProjectInfo", "Project information");
        table.Add("Common.Group.QuickLaunch", "Quick launch");
        table.Add("Common.Group.RestLayerComponents", "Rest-layer components");
        table.Add("Common.Group.ScreenAndPlacement", "Screen and placement");
        table.Add("Common.Group.SettingsFile", "Settings file");
        table.Add("Common.Group.SharedModifier", "Shared modifier");
        table.Add("Common.Group.Sponsors", "Sponsors");
        table.Add("Common.Group.Support", "Support me");
        table.Add("Common.Group.ThemeAndBackdrop", "Theme and backdrop");
        table.Add("Common.Group.TrackChangeNotification", "Track-change notification");
        table.Add("Common.HoverLayer", "Hover layer");
        table.Add("Common.MediaSource", "Media source");
        table.Add("Common.Modifier.LeftMouseButton", "Left mouse button");
        table.Add("Common.Modifier.RightMouseButton", "Right mouse button");
        table.Add("Common.Modifier.Shift", "Shift key");
        table.Add("Common.Monitor.PrimarySuffix", " (Primary)");
        table.Add("Common.NextTrack", "Next track");
        table.Add("Common.NotBound", "Not bound");
        table.Add("Common.NotImplemented", "Not implemented");
        table.Add("Common.OpenFolder", "Open folder");
        table.Add("Common.OpenFullPanel", "Open the full panel");
        table.Add("Common.OutputDevice", "Output device");
        table.Add("Common.Page.About", "About");
        table.Add("Common.Page.Application", "Application");
        table.Add("Common.Page.Appearance", "Appearance");
        table.Add("Common.Page.DisplayModes", "Display mode");
        table.Add("Common.Page.Interaction", "Interaction");
        table.Add("Common.Page.Lyrics", "Lyrics");
        table.Add("Common.Page.MediaAndNotifications", "Media and notifications");
        table.Add("Common.PlayPause", "Play / pause");
        table.Add("Common.PreviousNextTrack", "Previous / next track");
        table.Add("Common.PreviousTrack", "Previous track");
        table.Add("Common.ReconnectSmtc", "Reconnect SMTC");
        table.Add("Common.ReloadTaskbarHost", "Reload the taskbar media bar");
        table.Add("Common.ResetDialog.Confirm", "Restore");
        table.Add("Common.ResetDialog.Content", "Every option inside \"{0}\" is reset; other pages and the current playback are not affected.");
        table.Add("Common.ResetDialog.Title", "Restore defaults");
        table.Add("Common.ResetPageDefaults", "Restore this page's defaults");
        table.Add("Common.ResetPosition", "Reset position");
        table.Add("Common.RestLayer", "Rest layer");
        table.Add("Common.Save", "Save");
        table.Add("Common.Settings", "Settings");
        table.Add("Common.SkipVersion", "Skip this version");
        table.Add("Common.SwitchMediaSource", "Switch media source");
        table.Add("Common.SwitchOutputDevice", "Switch output device");
        table.Add("Common.SwitchPlayer", "Switch player");
        table.Add("Common.TargetMonitor", "Target monitor");
        table.Add("Common.TrayIcon", "Tray icon");

        // ---- Diagram ----
        table.Add("Diagram.DynamicIslandSurface.Caption", "Dynamic island mode is not implemented, so the three options below are read-only; its appearance and the taskbar do not affect each other.");
        table.Add("Diagram.InputGestures.Caption", "These are the only two clickable areas on the media bar and each is set separately; buttons in the expanded panel are unaffected.");
        table.Add("Diagram.InputGestures.Label.ArtworkClick", "Artwork click");
        table.Add("Diagram.InputGestures.Label.TextClick", "Title or lyrics click");
        table.Add("Diagram.LayerFull.Caption", "The panel opened from the media bar has four sections; each can be turned off, but at least one stays on.");
        table.Add("Diagram.LayerFull.Label.MediaInfo", "Media info");
        table.Add("Diagram.LayerFull.Label.Performance", "Performance");
        table.Add("Diagram.LayerFull.Label.Playback", "Playback");
        table.Add("Diagram.LayerHover.Caption", "Hovering reveals playback, switching, output device, volume, and progress controls, each with its own switch on the next page.");
        table.Add("Diagram.LayerRest.Caption", "Cover and title are always shown; the spectrum and performance components sit on the right and are switched in \"Media and notifications → Rest-layer components\".");
        table.Add("Diagram.LyricsAlignment.Caption", "It only decides which side the lyrics take; title and artist alignment is a separate setting on the \"Display mode\" page.");
        table.Add("Diagram.LyricsTwoLine.Caption", "The first line is the current line; the second is the next line or a translation and is hidden when the rest layer runs out of room.");
        table.Add("Diagram.LyricsTwoLine.Label.FirstLine", "First line");
        table.Add("Diagram.LyricsTwoLine.Label.SecondLine", "Second line");
        table.Add("Diagram.NotificationPlacement.Caption", "Six positions are available and the highlighted square is the current one; switching monitor only changes where it appears.");
        table.Add("Diagram.NotificationPlacement.Label.AvoidTaskbar", "Bottom positions avoid the taskbar");
        table.Add("Diagram.NotificationPlacement.Label.InsideMonitor", "Notifications appear inside the selected monitor");
        table.Add("Diagram.Spectrum.Caption", "The example shows 9 spectrum bars with the rightmost one off; the refresh rate sets how fast it reacts and the sensitivity sets the bar height at a given volume.");
        table.Add("Diagram.TaskbarLength.Caption", "The width follows the content; with following off a fixed width applies instead, and its range is set by the current taskbar.");
        table.Add("Diagram.TaskbarLength.Label.MinimumWidth", "Minimum required width");
        table.Add("Diagram.TaskbarLength.Label.TaskbarLimit", "Taskbar safe limit");
        table.Add("Diagram.TaskbarPlacement.Caption", "The media bar avoids the taskbar icons automatically; the edge offset adjusts the gap between it and the icon area.");
        table.Add("Diagram.TaskbarPlacement.Label.EdgeOffset", "Edge offset −20 ~ +20 px");
        table.Add("Diagram.TaskbarPlacement.Label.TaskbarIcons", "Taskbar icons");
        table.Add("Diagram.TrayOverflow.Caption", "The highlighted square is this application; it sits in the hidden-icon area by default and has to be dragged out in Windows taskbar settings before tray clicks and the wheel work.");
        table.Add("Diagram.TrayOverflow.Label.OverflowArrow", "Collapsed into the arrow");
        table.Add("Diagram.TrayOverflow.Label.TrayArea", "Tray area");
        table.Add("Diagram.WheelGestures.Caption", "Up and down have no fixed meaning; the bound action decides. A device switch shows the candidates first and applies about 1.2 seconds after scrolling stops.");
        table.Add("Diagram.WheelGestures.Label.MediaBar", "On the media bar");
        table.Add("Diagram.WheelGestures.Label.MediaBarResults", "All four results can be bound: previous/next, device or player, volume");
        table.Add("Diagram.WheelGestures.Label.TrayResults", "Only device switching and volume");

        // ---- DisplayModes ----
        table.Add("DisplayModes.Full.Expander.Description", "Chooses the sections the panel contains; at least one stays enabled");
        table.Add("DisplayModes.Full.Expander.Title", "Full-panel content");
        table.Add("DisplayModes.Full.Group.Description", "The full control panel expanded from the media bar");
        table.Add("DisplayModes.Full.Preset.Compact", "Compact");
        table.Add("DisplayModes.Full.Preset.Custom", "Custom");
        table.Add("DisplayModes.Full.Preset.Full", "Full");
        table.Add("DisplayModes.Full.Row.Enable.Description", "Expands the full control panel when the media bar is clicked");
        table.Add("DisplayModes.Full.Row.Enable.Title", "Enable the full panel");
        table.Add("DisplayModes.Full.Row.MediaControls.Title", "Playback controls");
        table.Add("DisplayModes.Full.Row.MediaInfo.Title", "Media information");
        table.Add("DisplayModes.Full.Row.Performance.Title", "Performance information");
        table.Add("DisplayModes.Full.Row.Preset.Description", "Applies one set of section visibilities in a single step");
        table.Add("DisplayModes.Full.Row.Preset.Title", "Apply a preset");
        table.Add("DisplayModes.Header.Subtitle", "Where the media bar sits, how wide it is, and its three display states");
        table.Add("DisplayModes.Hover.Expander.Description", "Chooses which controls appear on hover");
        table.Add("DisplayModes.Hover.Expander.Title", "Hover-layer controls");
        table.Add("DisplayModes.Hover.Group.Description", "Quick controls that appear when the pointer enters the media bar");
        table.Add("DisplayModes.Hover.Row.Enable.Description", "Shows the quick-control buttons when the pointer enters the media bar");
        table.Add("DisplayModes.Hover.Row.Enable.Title", "Enable the hover layer");
        table.Add("DisplayModes.Hover.Row.Progress.Title", "Progress bar");
        table.Add("DisplayModes.Island.Group.Description", "The dynamic island's own appearance, independent of the taskbar");
        table.Add("DisplayModes.Island.Notice", "The dynamic island mode is not implemented yet, so the options below are read-only for now and changes do not affect the running taskbar media bar.");
        table.Add("DisplayModes.Island.Row.Corner.Description", "0–24 DIP");
        table.Add("DisplayModes.Island.Row.Corner.Title", "Corner radius");
        table.Add("DisplayModes.Island.Row.Opacity.Description", "A higher value is more opaque");
        table.Add("DisplayModes.Island.Row.Opacity.Title", "Background opacity");
        table.Add("DisplayModes.Island.Row.Surface.Description", "The dynamic island's own background style");
        table.Add("DisplayModes.Island.Row.Surface.Title", "Background style");
        table.Add("DisplayModes.Island.Surface.Automatic", "Automatic");
        table.Add("DisplayModes.Island.Surface.Solid", "Solid color");
        table.Add("DisplayModes.Island.Surface.ThemeTint", "Theme tint");
        table.Add("DisplayModes.Mode.Current", "Current mode");
        table.Add("DisplayModes.Mode.DesktopCard", "Desktop card");
        table.Add("DisplayModes.Mode.DesktopCard.Caption", "Places freely arrangeable media cards on the desktop");
        table.Add("DisplayModes.Mode.DynamicIsland.Caption", "Carries the media state in an overlay at the edge of the screen");
        table.Add("DisplayModes.Mode.FloatingBall", "Floating ball");
        table.Add("DisplayModes.Mode.FloatingBall.Caption", "Expands the controls from a compact floating entry point");
        table.Add("DisplayModes.Mode.PreviewNotice", "The running mode stays the taskbar. Choosing another mode only changes what this page shows; it does not switch the running window.");
        table.Add("DisplayModes.Mode.Taskbar", "Taskbar");
        table.Add("DisplayModes.Mode.Taskbar.Caption", "Runs in the Windows taskbar and provides the rest layer, the hover layer, and the full panel");
        table.Add("DisplayModes.Monitor.DisconnectedSuffix", " (not connected)");
        table.Add("DisplayModes.Placement.Group.Description", "The monitor holding the media bar, and its position on the taskbar");
        table.Add("DisplayModes.Placement.Orientation.Auto", "Automatic (follow the taskbar)");
        table.Add("DisplayModes.Placement.Orientation.Horizontal", "Force horizontal");
        table.Add("DisplayModes.Placement.Orientation.Vertical", "Force vertical");
        table.Add("DisplayModes.Placement.ResetAction", "Reset");
        table.Add("DisplayModes.Placement.Row.AvoidIcons.Description", "Keeps clear of the taskbar icon area so nothing is covered");
        table.Add("DisplayModes.Placement.Row.AvoidIcons.Title", "Avoid taskbar icons");
        table.Add("DisplayModes.Placement.Row.Lock.Description", "Prevents dragging while locked");
        table.Add("DisplayModes.Placement.Row.Lock.Title", "Lock position");
        table.Add("DisplayModes.Placement.Row.Monitor.Description", "Select one or more monitors; at least one target stays selected");
        table.Add("DisplayModes.Placement.Row.Offset.Description", "Fine-tunes the gap between the media bar and the icon area along the cross axis");
        table.Add("DisplayModes.Placement.Row.Offset.Title", "Edge offset");
        table.Add("DisplayModes.Placement.Row.Orientation.Description", "Follows the taskbar orientation automatically, or forces horizontal or vertical");
        table.Add("DisplayModes.Placement.Row.Orientation.Title", "Orientation");
        table.Add("DisplayModes.Placement.Row.Reset.Description", "Returns to the position that automatic avoidance calculates");
        table.Add("DisplayModes.Rest.Component.Artwork", "Artwork");
        table.Add("DisplayModes.Rest.Component.Artwork.Description", "The current track's artwork; without media it is a note, and clicking it or wheeling over it picks a player");
        table.Add("DisplayModes.Rest.Component.MediaText", "Media text");
        table.Add("DisplayModes.Rest.Component.MediaText.Description", "The title and the artist; replaced by the two lyric rows while lyrics are available");
        table.Add("DisplayModes.Rest.Component.OutputDevice", "Output-device button");
        table.Add("DisplayModes.Rest.Component.OutputDevice.Description", "Opens the output-device menu on click and switches devices on the wheel");
        table.Add("DisplayModes.Rest.Component.Performance", "Performance monitor");
        table.Add("DisplayModes.Rest.Component.Performance.Description", "Cycles through memory, processor, and other metrics at the sampling interval");
        table.Add("DisplayModes.Rest.Component.QuickLaunchNote", "Quick-launch note");
        table.Add("DisplayModes.Rest.Component.QuickLaunchNote.Description", "The note shown without media; clicking it or wheeling over it picks a player");
        table.Add("DisplayModes.Rest.Component.Spectrum", "Spectrum");
        table.Add("DisplayModes.Rest.Component.Spectrum.Description", "The live spectrum of the current output device; it moves with any sound, regardless of the foreground player");
        table.Add("DisplayModes.Rest.Component.Volume", "Volume button");
        table.Add("DisplayModes.Rest.Component.Volume.Description", "Opens the volume menu on click and adjusts the current source's volume on the wheel");
        table.Add("DisplayModes.Rest.ContentLayout.AdaptiveStack", "Adaptive stack");
        table.Add("DisplayModes.Rest.ContentLayout.CompactInline", "Compact inline");
        table.Add("DisplayModes.Rest.Density.Balanced", "Balanced");
        table.Add("DisplayModes.Rest.Density.Information", "Information first");
        table.Add("DisplayModes.Rest.Density.Minimal", "Minimal");
        table.Add("DisplayModes.Rest.Group.Description", "The always-visible base layer that carries the artwork, the title, and the lyrics");
        table.Add("DisplayModes.Rest.Group.Status", "Always on");
        table.Add("DisplayModes.Rest.Idle.Expander.Description", "Which components stay on the media bar while no media source exists; with nothing checked the whole bar is hidden");
        table.Add("DisplayModes.Rest.Idle.Expander.Title", "Shown without media");
        table.Add("DisplayModes.Rest.Idle.Notice", "The artwork and the media text are not listed here: with no media they have nothing to display and are therefore never shown. Keeping only the note still lets a player be picked by wheeling over it.");
        table.Add("DisplayModes.Rest.Notice", "The spectrum and performance components are switched and tuned under \"Media and notifications → Rest-layer components\"; the media text size is under \"Appearance → Media bar text\". The spectrum captures everything the current output device plays.");
        table.Add("DisplayModes.Rest.Order.Expander.Description", "The order is the left-to-right arrangement inside the bar; the artwork and the media text are pinned to the front and the other four can move up and down");
        table.Add("DisplayModes.Rest.Order.Expander.Title", "Rest-layer component order");
        table.Add("DisplayModes.Rest.Order.Notice", "The artwork and the media text are pinned to the front of the bar and take no part in ordering (their two rows carry no move buttons).");
        table.Add("DisplayModes.Rest.Order.Reset.Description", "Spectrum, performance monitor, output-device button, volume button");
        table.Add("DisplayModes.Rest.Order.Reset.Title", "Restore the default order");
        table.Add("DisplayModes.Rest.Row.Alignment.Description", "Sets how the media text is aligned inside the media bar");
        table.Add("DisplayModes.Rest.Row.Alignment.Title", "Title and artist alignment");
        table.Add("DisplayModes.Rest.Row.Density.Description", "Adjusts the spacing between the buttons and the progress bar inside the rest layer");
        table.Add("DisplayModes.Rest.Row.Density.Title", "Rest-layer spacing");
        table.Add("DisplayModes.Rest.Row.DeviceButton.Description", "Opens the output-device menu on click and switches devices on the wheel; keeping it there takes room from the media text");
        table.Add("DisplayModes.Rest.Row.DeviceButton.Title", "Show the output-device button in the rest layer");
        table.Add("DisplayModes.Rest.Row.Entry.Description", "Opens the full panel when the pointer enters the media bar or the thin bar above the text area is clicked");
        table.Add("DisplayModes.Rest.Row.Entry.Title", "Show the full-panel entry");
        table.Add("DisplayModes.Rest.Row.Layout.Description", "Puts the title and the artist on one line side by side, or stacks them");
        table.Add("DisplayModes.Rest.Row.Layout.Title", "Content layout");
        table.Add("DisplayModes.Rest.Row.Progress.Description", "A read-only progress bar along the bottom of the rest layer; it stays hidden while the media reports no duration");
        table.Add("DisplayModes.Rest.Row.Progress.Title", "Show playback progress");
        table.Add("DisplayModes.Rest.Row.VolumeButton.Description", "Opens the volume menu on click and adjusts the current source's volume on the wheel; keeping it there takes room from the media text");
        table.Add("DisplayModes.Rest.Row.VolumeButton.Title", "Show the volume button in the rest layer");
        table.Add("DisplayModes.Status.Current", "Current: {0}");
        table.Add("DisplayModes.Unimplemented.DesktopCard", "The desktop card mode is not implemented yet, so there are no settings to change for now. Every mode will get its own settings page.");
        table.Add("DisplayModes.Unimplemented.FloatingBall", "The floating ball mode is not implemented yet, so there are no settings to change for now. Every mode will get its own settings page.");
        table.Add("DisplayModes.Width.Group.Description", "Width of the media bar and the spacing inside it");
        table.Add("DisplayModes.Width.RangeText", "Available range: {0:0}–{1:0} DIP");
        table.Add("DisplayModes.Width.Row.Fixed.Badge", "Turn content following off first");
        table.Add("DisplayModes.Width.Row.Fixed.Description", "Takes a value between the required minimum width and the width available on the taskbar");
        table.Add("DisplayModes.Width.Row.Fixed.Title", "Fixed width");
        table.Add("DisplayModes.Width.Row.Follow.Description", "The media bar width follows the title length automatically");
        table.Add("DisplayModes.Width.Row.Follow.Title", "Follow the content length");
        table.Add("DisplayModes.Width.Row.Spacing.Description", "Horizontal spacing between the artwork area, the text area, and the extra components");
        table.Add("DisplayModes.Width.Row.Spacing.Title", "Component spacing");

        // ---- Interaction ----
        table.Add("Interaction.Header.Subtitle", "The result of each interaction on the media bar and the tray icon");
        table.Add("Interaction.InApp.Group.Description", "The result of a click on the rest layer");
        table.Add("Interaction.Row.ArtworkClick.Description", "Set independently of the next row");
        table.Add("Interaction.Row.ArtworkClick.Title", "Artwork click");
        table.Add("Interaction.Row.ChordWheel.Description", "Hold the modifier above while scrolling the wheel");
        table.Add("Interaction.Row.Modifier.Description", "The media bar and the tray icon share one modifier");
        table.Add("Interaction.Row.Modifier.Title", "Chord wheel modifier");
        table.Add("Interaction.Row.PrimaryWheel.Description", "Wheel behavior while the modifier is not held");
        table.Add("Interaction.Row.TextClick.Title", "Title or lyrics click");
        table.Add("Interaction.Row.TrayChordWheel.Description", "Shows the device candidates first and applies the choice about 1.2 seconds after scrolling stops");
        table.Add("Interaction.Row.TrayClick.Description", "The right button always opens the menu; this sets the left-click behavior");
        table.Add("Interaction.Row.TrayClick.Title", "Tray icon click");
        table.Add("Interaction.Row.TrayPrimaryWheel.Description", "Applies only while the pointer is over the tray icon");
        table.Add("Interaction.SharedModifier.Callout", "When the left or right mouse button is the modifier, the click or menu produced after a wheel gesture is suppressed to avoid an accidental action.");
        table.Add("Interaction.SharedModifier.Group.Description", "Hold this modifier while scrolling the wheel to trigger the chord wheel");
        table.Add("Interaction.Disabled", "disabled");
        table.Add("Interaction.TrayAction.OpenAudioControl", "Open the audio control menu");
        table.Add("Interaction.TrayAction.OpenContextMenu", "Open the context menu");
        table.Add("Interaction.TrayAction.OpenCurrentAppVolumeMenu", "Open the current application volume menu");
        table.Add("Interaction.TrayAction.OpenOutputDeviceMenu", "Open the output device menu");
        table.Add("Interaction.TrayAction.OpenSettings", "Open the settings page");
        table.Add("Interaction.Wheel.Chord.Title", "Chord wheel");
        table.Add("Interaction.Wheel.Primary.Title", "Plain wheel");

        // ---- Layout ----
        table.Add("Layout.Arrangement.Auto", "Automatic");
        table.Add("Layout.Arrangement.Horizontal", "Horizontal");
        table.Add("Layout.Arrangement.Vertical", "Vertical");
        table.Add("Layout.Group.Position", "Position");
        table.Add("Layout.Group.Size", "Size");
        table.Add("Layout.Group.Window", "Window");
        table.Add("Layout.IslandBackground.SystemTheme", "System theme background");
        table.Add("Layout.IslandBackground.Transparent", "Transparent background");
        table.Add("Layout.Page.Subtitle", "Adjust the window mode, arrangement, and size");
        table.Add("Layout.Page.Title", "Layout");
        table.Add("Layout.Preset.DynamicIslandHorizontal", "Dynamic island theme (horizontal): draggable, and collapsible against a desktop edge");
        table.Add("Layout.Preset.DynamicIslandVertical", "Dynamic island theme (vertical): draggable, and collapsible against a desktop edge");
        table.Add("Layout.Preset.TaskbarHorizontal", "Taskbar theme (horizontal): fits a taskbar along the top or bottom of the screen");
        table.Add("Layout.Preset.TaskbarVertical", "Taskbar theme (vertical): fits a taskbar along the left or right edge of the screen");
        table.Add("Layout.Reset.Button", "Restore defaults");
        table.Add("Layout.Row.Arrangement.Description", "Sets the direction in which the media content is arranged");
        table.Add("Layout.Row.Arrangement.Title", "Arrangement");
        table.Add("Layout.Row.AvoidIcons.Description", "Limits the length and position automatically so taskbar icons are not covered");
        table.Add("Layout.Row.AvoidIcons.Title", "Avoid taskbar icons");
        table.Add("Layout.Row.EdgeOffset.Description", "Moves up and down on a horizontal taskbar and left and right on a vertical one");
        table.Add("Layout.Row.EdgeOffset.Title", "Edge offset");
        table.Add("Layout.Row.IslandBackground.Description", "Uses the system theme colors or a transparent background");
        table.Add("Layout.Row.IslandBackground.Title", "Background style");
        table.Add("Layout.Row.LengthScale.Description", "Adjusts the spacing between components such as cover art, lyrics, and the title");
        table.Add("Layout.Row.LengthScale.Title", "Component spacing scale");
        table.Add("Layout.Row.LockPosition.Description", "Keeps the media bar at its current position");
        table.Add("Layout.Row.LockPosition.Title", "Lock position");
        table.Add("Layout.Row.ResetPage.Description", "Restores the window, arrangement, scale, taskbar, and dynamic island settings");
        table.Add("Layout.Row.ResetPosition.Description", "Restores the default position");
        table.Add("Layout.Row.ThicknessScale.Description", "Scales every component proportionally while the spacing between components stays unchanged");
        table.Add("Layout.Row.ThicknessScale.Title", "Component thickness scale");
        table.Add("Layout.Row.WindowMode.Description", "Chooses where the media bar appears");
        table.Add("Layout.Row.WindowMode.Title", "Window mode");
        table.Add("Layout.WindowMode.Taskbar", "Dock to the taskbar");

        // ---- Lyrics ----
        table.Add("Lyrics.Adoption.FirstArrival", "First arrival");
        table.Add("Lyrics.Adoption.PreferDefaultSource", "Prefer default source");
        table.Add("Lyrics.Adoption.PreferDefaultSourceWithDeadline", "Prefer default source (with deadline)");
        table.Add("Lyrics.DefaultBindings.Add", "Add player");
        table.Add("Lyrics.DefaultBindings.Remark.Placeholder", "Remark");
        table.Add("Lyrics.DefaultBindings.Add.Placeholder", "Enter the AppID (an AUMID or a fragment of it)");
        table.Add("Lyrics.DefaultBindings.Expander.Description", "Recognize the players now running and pick each one's default lyric interface; players left unbound have no default interface");
        table.Add("Lyrics.DefaultBindings.Expander.Title", "Default-interface bindings");
        table.Add("Lyrics.DefaultBindings.None", "Not bound (no default interface)");
        table.Add("Lyrics.DefaultBindings.Player.Kugou", "Kugou Music");
        table.Add("Lyrics.DefaultBindings.Player.Netease", "NetEase Music");
        table.Add("Lyrics.DefaultBindings.Player.QQMusic", "QQ Music");
        table.Add("Lyrics.DefaultBindings.Player.SodaMusic", "Soda Music");
        table.Add("Lyrics.DefaultBindings.Remove", "Remove this row");
        table.Add("Lyrics.DefaultBindings.Scan", "Scan playing players");
        table.Add("Lyrics.QueryStrategy.Concurrent", "Simultaneous");
        table.Add("Lyrics.QueryStrategy.Sequential", "Sequential");
        table.Add("Lyrics.Callout.Display", "With lyrics available the media bar shows the lyrics; without them it shows the title and artist.");
        table.Add("Lyrics.Header.Subtitle", "The current lyrics in the taskbar rest layer");
        table.Add("Lyrics.Row.QueryStrategy.Description", "Try the sources one by one, or send them out at once (the default interface and the priority batches query together); sequential mode keeps only the priority order");
        table.Add("Lyrics.Row.QueryStrategy.Title", "Query strategy");
        table.Add("Lyrics.Row.AdoptionMode.Description", "How a concurrent retrieval adopts its result; \"prefer default source\" favours the interface matched to the playing player");
        table.Add("Lyrics.Row.AdoptionMode.Title", "Result adoption mode");
        table.Add("Lyrics.Row.BatchSize.Description", "How many sources fetch concurrently per batch; the next batch is requested only after the current one has all missed");
        table.Add("Lyrics.Row.BatchSize.Title", "Concurrency batch size");
        table.Add("Lyrics.Row.Deadline.Description", "Once a priority source has answered first, the default interface gets this long; applies only to \"prefer default source (with deadline)\"");
        table.Add("Lyrics.Row.Deadline.Title", "Default-interface deadline");
        table.Add("Lyrics.Row.Alignment.Description", "How the lyrics are aligned in the rest layer; title and artist alignment is a separate setting on the display mode page");
        table.Add("Lyrics.Row.Alignment.Title", "Lyric alignment");
        table.Add("Lyrics.Row.InfoLines.Description", "Hides credit lines such as writer, composer, and producer");
        table.Add("Lyrics.Row.InfoLines.Title", "Filter credit lines");
        table.Add("Lyrics.Row.MatchStrictness.Description", "How closely a lyric search by title has to match; the stricter it is, the less likely a same-named live version or cover is accepted");
        table.Add("Lyrics.Row.MatchStrictness.Title", "Search match strictness");
        table.Add("Lyrics.Row.SecondLine.Description", "The second line shows the translation, the romanization, or the next lyric line; the order is the priority and a missing source is skipped");
        table.Add("Lyrics.Row.SecondLine.Note", "The order is the priority: the source listed first is used first, and an empty one falls through to the next");
        table.Add("Lyrics.Row.SecondLine.OrderRow.Description", "Moving a row up raises its priority");
        table.Add("Lyrics.Row.SecondLine.Title", "Second-line content");
        table.Add("Lyrics.Row.ShowLyrics.Description", "Syncs the current line to playback progress; when off, the title and artist are shown");
        table.Add("Lyrics.Row.ShowLyrics.Title", "Show live lyrics");
        table.Add("Lyrics.Row.SyllableHighlight.Description", "Lights the current line up syllable by syllable when it carries a syllable timeline; nothing is revealed while paused, in high contrast, or with system animations off");
        table.Add("Lyrics.Row.SyllableHighlight.Title", "Syllable reveal");
        table.Add("Lyrics.Row.TwoLine.Badge", "Enable lyrics first");
        table.Add("Lyrics.Row.TwoLine.Description", "Adds one more line below the current line");
        table.Add("Lyrics.Row.TwoLine.Title", "Two-line lyrics");
        table.Add("Lyrics.Row.UnsungOpacity.Badge", "Enable the syllable reveal first");
        table.Add("Lyrics.Row.UnsungOpacity.Description", "Opacity of the text that has not been sung yet; lower means a stronger contrast (45% by default)");
        table.Add("Lyrics.Row.UnsungOpacity.Title", "Unsung-part opacity");
        table.Add("Lyrics.Row.LineGap.Badge", "Enable two-line lyrics first");
        table.Add("Lyrics.Row.LineGap.Description", "Extra spacing on top of the two-row layout as a percentage of the font size, scaling with it; tightened automatically when space runs short, so text is never clipped or shrunk (0 by default)");
        table.Add("Lyrics.Row.LineGap.Title", "Line gap");
        table.Add("Lyrics.Row.CharacterSpacing.Description", "Widens the gap between characters as a percentage of the font size and scales with it; applies to CJK and Latin without breaking words apart (0 by default)");
        table.Add("Lyrics.Row.CharacterSpacing.Title", "Character spacing");
        table.Add("Lyrics.Row.FixedWidth.Badge", "Enable lyrics first");
        table.Add("Lyrics.Row.FixedWidth.Description", "Keeps the lyric box at a fixed length instead of resizing with every line; when off it follows the content (off by default)");
        table.Add("Lyrics.Row.FixedWidth.Title", "Fixed lyric-box length");
        table.Add("Lyrics.Row.FixedWidth.Length.Description", "Length of the lyric box in fixed mode (DIP); clamped automatically when the taskbar runs short (240 by default)");
        table.Add("Lyrics.Row.FixedWidth.Length.Title", "Lyric-box length");
        table.Add("Lyrics.SecondLine.NextLine", "Next lyric line");
        table.Add("Lyrics.SecondLine.Reset.Description", "Restores the order to next line, translation, romanization");
        table.Add("Lyrics.SecondLine.Reset.Title", "Restore the default order");
        table.Add("Lyrics.SecondLine.Romanization", "Romanization of the current line");
        table.Add("Lyrics.SecondLine.Translation", "Translation of the current line");
        table.Add("Lyrics.Source.Kugou", "Kugou Music");
        table.Add("Lyrics.Source.LRCLIB", "LRCLIB");
        table.Add("Lyrics.Source.Netease", "NetEase Cloud Music");
        table.Add("Lyrics.Source.NeteaseSearch", "NetEase Cloud Music (search)");
        table.Add("Lyrics.Source.QQMusic", "QQ Music");
        table.Add("Lyrics.Source.SodaMusic", "Soda Music");
        table.Add("Lyrics.Source.Unknown", "Unknown source");
        table.Add("Lyrics.Sources.AllDisabled.Callout", "Every lyric source is off: no lyric request is sent at all, and the media bar shows the title and artist only.");
        table.Add("Lyrics.Sources.Callout", "Lyrics are requested from the enabled sources in the order below, stopping at the first hit; each source is asked once.");
        table.Add("Lyrics.Sources.Expander.Description", "Which sources are enabled and in what priority order");
        table.Add("Lyrics.Sources.Expander.Title", "Fallback source priority order");
        table.Add("Lyrics.Sources.Expander.Title.Sequential", "Priority order");
        table.Add("Lyrics.Sources.MoveDown", "Move down");
        table.Add("Lyrics.Sources.MoveUp", "Move up");
        table.Add("Lyrics.Sources.Reset.Action", "Restore defaults");
        table.Add("Lyrics.Sources.Reset.Description", "Enables every source again and sorts them by the default priority");
        table.Add("Lyrics.Sources.Reset.Title", "Restore default order");
        table.Add("Lyrics.Sources.Row.Description", "When off, this source is no longer asked for lyrics");
        table.Add("Lyrics.Strictness.Balanced", "Balanced");
        table.Add("Lyrics.Strictness.Exact", "Exact");
        table.Add("Lyrics.Strictness.Strict", "Strict");

        // ---- Media ----
        table.Add("Media.Badge.EnableFirst", "Enable first");
        table.Add("Media.Dialog.Browse.Filter", "Applications and shortcuts (*.exe;*.lnk)|*.exe;*.lnk");
        table.Add("Media.Dialog.Browse.Title", "Select a media application or shortcut");
        table.Add("Media.Header.Subtitle", "Media sources, quick launch, rest-layer components, and track notifications");
        table.Add("Media.Metric.ProcessMemory.Title", "Memory used by this application");
        table.Add("Media.Metric.SystemMemory.Description", "At least one metric is required, so the last one cannot be turned off");
        table.Add("Media.Metric.SystemMemory.Title", "System memory");
        table.Add("Media.Notification.Details.Description", "Position, duration, and target monitor");
        table.Add("Media.Notification.Details.Title", "Notification details");
        table.Add("Media.Notification.Duration.Title", "Duration");
        table.Add("Media.Notification.Duration.Value", "{0} s");
        table.Add("Media.Notification.Enabled.Description", "Shows the current track when the track changes and playback starts");
        table.Add("Media.Notification.Enabled.Title", "Enable notifications");
        table.Add("Media.Notification.FixedMonitor.Title", "Pinned monitor");
        table.Add("Media.Notification.Fullscreen.Description", "Notifications are suppressed in front of a full-screen window by default");
        table.Add("Media.Notification.Fullscreen.Title", "Show while full screen");
        table.Add("Media.Notification.Position.BottomCenter", "Bottom center");
        table.Add("Media.Notification.Position.BottomLeft", "Bottom left");
        table.Add("Media.Notification.Position.BottomRight", "Bottom right");
        table.Add("Media.Notification.Position.Title", "Position");
        table.Add("Media.Notification.Position.TopCenter", "Top center");
        table.Add("Media.Notification.Position.TopLeft", "Top left");
        table.Add("Media.Notification.Position.TopRight", "Top right");
        table.Add("Media.Notification.TargetMode.Description", "A fixed monitor, or the monitor of the foreground window");
        table.Add("Media.Notification.TargetMode.Fixed", "Fixed monitor");
        table.Add("Media.Notification.TargetMode.ForegroundWindow", "Monitor of the foreground window");
        table.Add("Media.Performance.Metrics.Description", "Several selected metrics are shown in turn");
        table.Add("Media.Performance.Metrics.Title", "Which metrics to show");
        table.Add("Media.Performance.OpenTaskManager.Description", "While this is off, clicking the performance component does nothing");
        table.Add("Media.Performance.OpenTaskManager.Title", "Open Task Manager when the performance component is clicked");
        table.Add("Media.Performance.RefreshInterval.Description", "Sampling interval; a smaller value reacts sooner (0.5–5 seconds)");
        table.Add("Media.Performance.RefreshInterval.Title", "Refresh interval");
        table.Add("Media.Performance.RefreshInterval.Value", "{0:0.#} s");
        table.Add("Media.Performance.Visible.Description", "Cycles through the selected metrics on the right side of the rest layer");
        table.Add("Media.Performance.Visible.Title", "Show performance component");
        table.Add("Media.QuickLaunch.Browse", "Browse for an application or shortcut");
        table.Add("Media.QuickLaunch.Entries.Description", "Reordering affects only the launch priority of this list");
        table.Add("Media.QuickLaunch.Entries.Title", "Added entries");
        table.Add("Media.QuickLaunch.EntryCount", "{0} items");
        table.Add("Media.QuickLaunch.FromNote.Description", "Clicking the note icon opens the quick launch list; the wheel previews it and the last entry launches about 1.2 seconds after scrolling stops");
        table.Add("Media.QuickLaunch.FromNote.Title", "Launch from the note icon when no media is playing");
        table.Add("Media.QuickLaunch.MoveDown", "Move down one position");
        table.Add("Media.QuickLaunch.MoveUp", "Move up one position");
        table.Add("Media.QuickLaunch.Remove", "Remove from quick launch");
        table.Add("Media.RestComponents.Description", "The two components overlaid on the right side of the rest layer");
        table.Add("Media.SourceFilter.Description", "Only applications in the list are accepted; the list is kept while this is off");
        table.Add("Media.SourceFilter.Title", "Source allow list");
        table.Add("Media.SourceList.AddToQuickLaunch", "Add to quick launch");
        table.Add("Media.SourceList.AddToQuickLaunch.ToolTip", "Only players whose launch method can be located automatically can be added; when none is found, use \"Browse for an application or shortcut\".");
        table.Add("Media.SourceList.Allow", "Allow");
        table.Add("Media.SourceList.Description", "A player appears here only after it has been run once");
        table.Add("Media.SourceList.Title", "Detected sources");
        table.Add("Media.Spectrum.BandCount.Description", "Number of spectrum bars (9–24); the bar width is fixed, so more bars make the spectrum wider");
        table.Add("Media.Spectrum.BandCount.Title", "Bar count");
        table.Add("Media.Spectrum.BandCount.Value", "{0} bars");
        table.Add("Media.Spectrum.ContentHeight.Description", "Height of the spectrum (14–34 DIP, the direction perpendicular to the taskbar); taller bars do not make the spectrum wider");
        table.Add("Media.Spectrum.ContentHeight.Title", "Spectrum height");
        table.Add("Media.Spectrum.ContentHeight.Value", "{0:0} DIP");
        table.Add("Media.Spectrum.Parameters.Description", "Bar count, height, refresh rate, and sensitivity");
        table.Add("Media.Spectrum.Parameters.Title", "Spectrum parameters");
        table.Add("Media.Spectrum.RefreshRate.Description", "How often the spectrum refreshes (5–30 Hz)");
        table.Add("Media.Spectrum.RefreshRate.Title", "Refresh rate");
        table.Add("Media.Spectrum.Sensitivity.Description", "Audio level at which a spectrum bar reaches its full height (10%–400%)");
        table.Add("Media.Spectrum.Sensitivity.Title", "Sensitivity");
        table.Add("Media.Spectrum.Style.Bars", "Bars");
        table.Add("Media.Spectrum.Style.Description", "How the spectrum is painted; it changes neither the bar count nor the width occupied");
        table.Add("Media.Spectrum.Style.MirroredBars", "Mirrored bars");
        table.Add("Media.Spectrum.Style.PixelBars", "Pixel bars");
        table.Add("Media.Spectrum.Style.Title", "Style");
        table.Add("Media.Spectrum.Style.Waveform", "Waveform");
        table.Add("Media.Spectrum.Visible.Description", "A live audio spectrum on the right side of the rest layer");
        table.Add("Media.Spectrum.Visible.Title", "Show spectrum");
        table.Add("Media.Status.AddedToQuickLaunch", "Added to quick launch.");
        table.Add("Media.Status.AlreadyFirst", "The entry is already first in the list.");
        table.Add("Media.Status.AlreadyInQuickLaunch", "This application is already in the quick launch list.");
        table.Add("Media.Status.AlreadyLast", "The entry is already last in the list.");
        table.Add("Media.Status.OnlyExistingFiles", "Only existing EXE or LNK files can be added.");
        table.Add("Media.Status.SourceLaunchUnresolved", "The launch method of this source cannot be resolved; browse for an EXE or LNK file.");

        // ---- Panel ----
        table.Add("Panel.AudioFlyout.AppVolume", "App volume");
        table.Add("Panel.AudioFlyout.Refresh", "Refresh audio status");
        table.Add("Panel.AudioFlyout.SpatialAudio", "Spatial sound");
        table.Add("Panel.CompactMenu.WindowTitle", "Taskbar quick menu");
        table.Add("Panel.FullPanel.NoMedia", "No media");
        table.Add("Panel.FullPanel.LyricsSource", "Lyrics source: {0}");
        table.Add("Panel.FullPanel.RepeatMode", "Repeat mode");
        table.Add("Panel.FullPanel.WindowTitle", "Media full panel");
        table.Add("Panel.Notification.NowPlaying", "Now playing");
        table.Add("Panel.Notification.WindowTitle", "Track-change notification");
        table.Add("Panel.Performance.Memory", "Memory");
        table.Add("Panel.Performance.ProcessMemory", "Process memory");
        table.Add("Panel.QuickLaunch.Empty", "No applications added yet");
        table.Add("Panel.QuickLaunch.Preview", "Quick launch: {0}");
        table.Add("Panel.QuickLaunch.Title", "Quick launch");
        table.Add("Panel.Repeat.All", "Repeat all");
        table.Add("Panel.Repeat.Off", "Repeat off");
        table.Add("Panel.Repeat.One", "Repeat one");
        table.Add("Panel.Repeat.Unavailable", "Repeat unavailable");
        table.Add("Panel.Volume.CurrentAppVolume", "Current app volume");
        table.Add("Panel.Volume.CurrentMedia", "Current media");
        table.Add("Panel.Volume.Tooltip", "Current app volume / Volume mixer");
        table.Add("Panel.Volume.Unavailable", "Unavailable");

        // ---- Search ----
        table.Add("Search.About.Developers.Description", "The developer list, taken from the GitHub contributors list");
        table.Add("Search.About.Licenses.Description", "The open-source packages and derived code this program uses, with their licenses");
        table.Add("Search.About.ProjectInfo.Description", "The repository, the feedback entry, and help");
        table.Add("Search.About.Sponsors.Description", "The sponsor list, read from the file in the repository");
        table.Add("Search.About.Support.Description", "WeChat and Alipay payment codes and the Afdian support link");
        table.Add("Search.Application.Application.Description", "Version information, update checks, automatic updates, launch at sign-in, and the interface language");
        table.Add("Search.Application.Diagnostics.Description", "Open the log folder (logs\\app.log, the file to send when something breaks) or return the working set to the system");
        table.Add("Search.Application.SettingsFile.Description", "Opening the settings folder and resetting every setting");
        table.Add("Application.Header.Subtitle", "Version and updates, interface language, run-at-startup, the settings file, and diagnostics");
        table.Add("Search.Appearance.Fonts.Description", "Latin font, Chinese font, and font weight");
        table.Add("Search.Appearance.MediaBarText.Description", "Color and size of the text on the media bar");
        table.Add("Search.Appearance.ThemeAndBackdrop.Description", "Light or dark appearance, and the window backdrop material");
        table.Add("Search.DisplayModes.ChooseDisplayMode.Description", "Display mode used by the media bar: taskbar, dynamic island, desktop card, or floating ball");
        table.Add("Search.DisplayModes.FullLayer.Description", "Sections of the panel that opens when the media bar is clicked");
        table.Add("Search.DisplayModes.HoverLayer.Description", "Quick controls shown when the pointer enters the media bar");
        table.Add("Search.DisplayModes.IslandAppearance.Description", "Dynamic island background style, opacity, and corner radius; currently read-only");
        table.Add("Search.DisplayModes.MediaBarWidth.Description", "Content-driven or fixed width, and component spacing");
        table.Add("Search.DisplayModes.RestLayer.Description", "Always-visible base layer: information density, content arrangement, alignment, progress display, and the full-panel entry");
        table.Add("Search.DisplayModes.ScreenAndPlacement.Description", "Monitor hosting the media bar and its taskbar placement");
        table.Add("Search.Interaction.InAppRestLayer.Description", "Result of clicking the rest layer: artwork click, text click, and wheel");
        table.Add("Search.Interaction.SharedModifier.Description", "Chord-wheel modifier shared by the media bar and the tray");
        table.Add("Search.Interaction.TrayIcon.Description", "Click and wheel behavior of the tray icon");
        table.Add("Search.Lyrics.Alignment.Description", "Left, center, or right alignment of the lyrics");
        table.Add("Search.Lyrics.Display.Description", "Whether lyrics and a second line are shown, the content of the second line, the syllable reveal, and credit-line filtering");
        table.Add("Search.Lyrics.Sources.Description", "Choose the lyric sources, their priority order, and the search match strictness");
        table.Add("Search.MediaAndNotifications.MediaSource.Description", "Source allow list and detected sources");
        table.Add("Search.MediaAndNotifications.QuickLaunch.Description", "Launching a player from the note glyph when no media is playing");
        table.Add("Search.MediaAndNotifications.RestLayerComponents.Description", "Spectrum and performance components overlaid on the right of the rest layer");
        table.Add("Search.MediaAndNotifications.TrackChangeNotification.Description", "Showing the current track when a new track starts playing");

        // ---- Service ----
        table.Add("Service.MediaSource.Kugou", "Kugou Music");
        table.Add("Service.MediaSource.NetEaseCloudMusic", "NetEase Cloud Music");
        table.Add("Service.MediaSource.QQMusic", "QQ Music");
        table.Add("Service.MediaSource.Unknown", "Unknown source");
        table.Add("Service.Startup.ExecutablePathUnavailable", "The program path could not be determined, so the startup entry cannot be written");
        table.Add("Service.Startup.RegistryKeyUnavailable", "The startup registry key could not be opened");

        // ---- Settings ----
        table.Add("Settings.Legacy.About", "About AFMediaBar");
        table.Add("Settings.Legacy.Personalization", "Personalization");
        table.Add("Settings.Legacy.Theme", "Theme");
        table.Add("Settings.Legacy.ThemeDark", "Dark");
        table.Add("Settings.Legacy.ThemeLight", "Light");
        table.Add("Settings.Search.Placeholder", "Search settings");
        table.Add("Settings.Search.Suggestion.Title", "{0} › {1}");

        // ---- Shell ----
        table.Add("Shell.QuickLaunch.Status.Failed", "The application could not be started; check that it is still available.");
        table.Add("Shell.QuickLaunch.Status.InvalidTarget", "The launch target is no longer valid; add it again on the Media and notifications page.");

        // ---- Startup ----
        table.Add("Startup.SingleInstance.AlreadyRunning", "AF Media Bar is already running. Look for its icon in the notification area at the bottom right, or select the arrow to show hidden icons.");

        // ---- Update ----
        table.Add("Update.Channel.Accelerated", "Accelerated mirror {0}");
        table.Add("Update.Channel.Direct", "GitHub direct");
        table.Add("Update.Install.Blocked.OtherInstances", "Other instances of the application are running");
        table.Add("Update.Install.Blocked.Portable", "Automatic installation is unavailable in a portable copy");
        table.Add("Update.Navigation.Available", "Version v{0} is available");
        table.Add("Update.Navigation.Downloading", "Downloading update {0}%");
        table.Add("Update.Navigation.Ready", "Update ready (v{0})");
        table.Add("Update.Navigation.Verifying", "Verifying the update");
        table.Add("Update.Notification.Body", "v{0} is available (current v{1}). Click to open settings, review the highlights, and download it.");
        table.Add("Update.Notification.Title", "AF Media Bar update available");
        table.Add("Update.Reason.DownloadFailed", "Download failed (network or disk error)");
        table.Add("Update.Reason.DownloadHashMismatch", "Installer verification failed (SHA-256 mismatch, {0} bytes received)");
        table.Add("Update.Reason.DownloadHttp", "Download failed (HTTP {0})");
        table.Add("Update.Reason.DownloadTimeout", "The download timed out");
        table.Add("Update.Reason.ManifestEmpty", "The manifest is empty");
        table.Add("Update.Reason.ManifestEndpointInvalid", "The manifest address is invalid");
        table.Add("Update.Reason.ManifestHttp", "The version manifest could not be reached (HTTP {0})");
        table.Add("Update.Reason.ManifestInvalidJson", "The manifest is not valid JSON");
        table.Add("Update.Reason.ManifestNetwork", "The version manifest could not be reached (network error)");
        table.Add("Update.Reason.ManifestRootNotObject", "The manifest root is not an object");
        table.Add("Update.Reason.ManifestSchemaInvalid", "The manifest's schemaVersion is not a valid version number");
        table.Add("Update.Reason.ManifestSchemaTooNew", "The manifest schemaVersion {0} is newer than {1}, which this application supports");
        table.Add("Update.Reason.ManifestUnreachable", "The version manifest could not be reached");
        table.Add("Update.Reason.ManifestVersionMissing", "The manifest has no version");
        table.Add("Update.Reason.ManifestVersionUnparsable", "The manifest version ({0}) could not be parsed");
        table.Add("Update.Reason.NoUsableSource", "No download address could be used");
        table.Add("Update.Reason.PendingRecordMissing", "The record of the downloaded installer is missing");
        table.Add("Update.Reason.Unknown", "unknown reason");
        table.Add("Update.Reason.VerifyHashMismatch", "The downloaded installer does not match the manifest's SHA-256 and was deleted");
        table.Add("Update.Reason.VerifyUnreadable", "The downloaded installer could not be read and was deleted");
        table.Add("Update.Relative.Days", "{0} days ago");
        table.Add("Update.Relative.Hours", "{0} hours ago");
        table.Add("Update.Relative.JustNow", "just now");
        table.Add("Update.Relative.Minutes", "{0} minutes ago");
        table.Add("Update.Status.Available", "Version v{0} is available (current v{1})");
        table.Add("Update.Status.Checking", "Checking for updates…");
        table.Add("Update.Status.Downloading", "Downloading and verifying the installer {0}%");
        table.Add("Update.Status.Failed", "Update failed: {0}");
        table.Add("Update.Status.Idle", "Not checked for updates yet");
        table.Add("Update.Status.ManualOnly", "Version v{0} is available, but the manifest offers no installer that can be installed automatically");
        table.Add("Update.Status.Ready", "Update ready (v{0}) · installed automatically at the next start, or restart and install now");
        table.Add("Update.Status.ReadyBlocked", "v{0} is downloaded, but {1}; update it manually from the download page");
        table.Add("Update.Status.Skipped", "v{0} skipped (current v{1}) · a manual check still reports it");
        table.Add("Update.Status.UpToDate", "The newest version is installed (v{0})");
        table.Add("Update.Status.Verifying", "Verifying the installer {0}%");
        table.Add("Update.Suffix.Channel", " · {0}");
        table.Add("Update.Suffix.LastCheck", " · Last checked {0}");
        table.Add("Update.Suffix.Mandatory", " · This version is required");
        table.Add("Update.Tray.Available", "Version v{0} is available (click to view)");
        table.Add("Update.Tray.Check", "Check for updates");
        table.Add("Update.Tray.Checking", "Checking for updates…");
        table.Add("Update.Tray.Downloading", "Downloading update {0}%");
        table.Add("Update.Tray.Failed", "Update failed, click to retry");
        table.Add("Update.Tray.Ready", "Update ready (v{0}), click to restart and install");
        table.Add("Update.Tray.Verifying", "Verifying the installer {0}%");

        // ---- Wheel ----
        table.Add("Wheel.Action.CurrentMediaVolume", "Current media volume");
        table.Add("Wheel.Action.MediaSource", "Media source");
        table.Add("Wheel.Hint.Chord", "{0} + wheel: {1}");
        table.Add("Wheel.Hint.Plain", "Plain wheel: {0}");
        table.Add("Wheel.Hint.WithValue", "{0} (now: {1})");
        table.Add("Wheel.Line.WithValue", "{0}: {1}");
    }
}



